# Generated by Django 5.1.4 on 2026-08-28 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('equipment', models.CharField(choices=[('dumbbells', 'Dumbbells'), ('barbells', 'Barbells'), ('kettlebells', 'Kettlebells'), ('bodyweight', 'Bodyweight'), ('bands', 'Resistance Bands'), ('machines', 'Machines'), ('cables', 'Cables')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('primary_muscles', models.JSONField(default=list)),
                ('secondary_muscles', models.JSONField(default=list)),
                ('summary', models.CharField(max_length=240)),
                ('instructions', models.JSONField(default=list, help_text='Ordered how-to steps.')),
                ('form_tips', models.JSONField(default=list)),
                ('common_mistakes', models.JSONField(default=list)),
                ('video_provider', models.CharField(default='youtube', max_length=20)),
                ('video_id', models.CharField(max_length=40)),
                ('video_title', models.CharField(blank=True, max_length=200)),
                ('is_compound', models.BooleanField(default=False)),
                ('beginner_friendly', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('weeks', models.PositiveSmallIntegerField(default=4)),
                ('days_per_week', models.PositiveSmallIntegerField(default=3)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('focus', models.CharField(blank=True, max_length=120)),
                ('equipment_used', models.JSONField(default=list)),
                ('weekly_progression', models.JSONField(default=list, help_text='One short coaching note per week.')),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('goal', models.CharField(choices=[('general', 'Get back into a routine'), ('strength', 'Rebuild strength'), ('muscle', 'Build muscle'), ('conditioning', 'Improve conditioning')], default='general', max_length=20)),
                ('experience', models.CharField(choices=[('returning', 'Returning after a break'), ('beginner', 'Brand new to lifting'), ('experienced', 'Experienced, just been away')], default='returning', max_length=20)),
                ('months_off', models.PositiveSmallIntegerField(default=4)),
                ('days_per_week', models.PositiveSmallIntegerField(default=3)),
                ('unit', models.CharField(choices=[('lb', 'Pounds (lb)'), ('kg', 'Kilograms (kg)')], default='lb', max_length=2)),
                ('onboarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('active_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('focus', models.CharField(blank=True, max_length=160)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.program')),
            ],
            options={
                'ordering': ['day_index'],
                'unique_together': {('program', 'day_index')},
            },
        ),
        migrations.CreateModel(
            name='ProgramSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('sets', models.PositiveSmallIntegerField(default=3)),
                ('rep_scheme', models.CharField(default='8-10', max_length=40)),
                ('rest_seconds', models.PositiveSmallIntegerField(default=90)),
                ('coach_note', models.CharField(blank=True, max_length=240)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.programday')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.exercise')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_on', models.DateField()),
                ('title', models.CharField(blank=True, max_length=140)),
                ('notes', models.TextField(blank=True)),
                ('perceived_effort', models.PositiveSmallIntegerField(blank=True, help_text='RPE 1-10 for the whole session.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.program')),
                ('program_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.programday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField(default=1)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, help_text="In the user's unit.", null=True)),
                ('is_warmup', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_entries', to='api.workout')),
            ],
            options={
                'ordering': ['exercise__name', 'set_number'],
            },
        ),
    ]
