# Generated by Django 5.1.4 on 2026-08-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='chain_key',
            field=models.CharField(blank=True, help_text="Groups a progression ladder, e.g. 'push-up'. Blank = not in a chain.", max_length=40),
        ),
        migrations.AddField(
            model_name='exercise',
            name='chain_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Position within the chain, 1 = easiest.'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_unilateral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='movement_pattern',
            field=models.CharField(choices=[('horizontal_push', 'Horizontal push'), ('horizontal_pull', 'Horizontal pull'), ('vertical_push', 'Vertical push'), ('vertical_pull', 'Vertical pull'), ('squat', 'Squat'), ('hinge', 'Hinge'), ('lunge', 'Lunge / split'), ('core_anti_extension', 'Core · anti-extension'), ('core_anti_rotation', 'Core · anti-rotation'), ('core_anti_lateral', 'Core · anti-lateral'), ('calves', 'Calves'), ('conditioning', 'Conditioning'), ('other', 'Other')], default='other', max_length=24),
        ),
        migrations.AddField(
            model_name='exercise',
            name='needs_anchor',
            field=models.CharField(choices=[('none', 'No anchor needed'), ('door', 'Needs a door anchor'), ('underfoot', 'Loop under the feet'), ('bar', 'Needs a bar')], default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='exercise',
            name='scaling_lever',
            field=models.CharField(blank=True, choices=[('body_angle', 'Body angle'), ('lever_length', 'Lever length'), ('range_of_motion', 'Range of motion'), ('base_of_support', 'Base of support'), ('unilateral', 'Unilateral load'), ('tempo', 'Tempo & time under tension'), ('band_tension', 'Band tension'), ('power', 'Stored elastic energy & power'), ('density', 'Density')], help_text='What makes this step harder than the one below it in its chain.', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='fitness_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Beginner / Intermediate / Advanced — scales every workout.', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='equipment_profile',
            field=models.CharField(choices=[('bodyweight_bands', 'Bodyweight & bands'), ('all', 'Any equipment')], default='all', max_length=20),
        ),
    ]
