# Generated by Django 5.1.4 on 2026-08-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seed_fitness_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='movement_pattern',
            field=models.CharField(choices=[('horizontal_push', 'Horizontal push'), ('horizontal_pull', 'Horizontal pull'), ('vertical_push', 'Vertical push'), ('vertical_pull', 'Vertical pull'), ('squat', 'Squat'), ('hinge', 'Hinge'), ('lunge', 'Lunge / split'), ('core_anti_extension', 'Core · anti-extension'), ('core_anti_rotation', 'Core · anti-rotation'), ('core_anti_lateral', 'Core · anti-lateral'), ('core_rotation', 'Core · rotation'), ('calves', 'Calves'), ('conditioning', 'Conditioning'), ('mobility', 'Mobility & Warm-up'), ('other', 'Other')], default='other', max_length=24),
        ),
    ]
