"""Seed content for the exercise library.

53 exercises across all seven equipment categories. Every entry has a short
demo video (YouTube), written instructions, form tips, and common mistakes.
Videos are embedded via youtube-nocookie.com so nothing tracks the user until
they press play.

`video_id` values point at focused "how to / proper form" demos from
instructional channels (Runna, NASM, Team Evolve, and similar). Swap any
`video_id` here and re-run `python manage.py seed --reset` to update the app.
"""

EXERCISES = [
    # ------------------------------------------------------------------ #
    #  DUMBBELLS
    # ------------------------------------------------------------------ #
    {
        "slug": "dumbbell-bench-press",
        "name": "Dumbbell Bench Press",
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Front Delts", "Triceps"],
        "summary": "The friendliest chest press for a comeback — each arm works on its own.",
        "is_compound": True,
        "video_id": "xhEhjF5ozuY",
        "video_title": "Dumbbell Bench Press Tutorial – Proper Form and Technique",
        "instructions": [
            "Sit on a flat bench with a dumbbell on each thigh, then lie back and use your legs to help lift them to your shoulders.",
            "Set your feet flat, squeeze your shoulder blades together, and press the dumbbells up until your arms are almost straight.",
            "Lower under control until your elbows are just below the bench, elbows tucked to about 45 degrees.",
            "Press back up and stop just short of locking out to keep tension on the chest.",
        ],
        "form_tips": [
            "Keep your wrists stacked over your elbows the whole way.",
            "Drive your feet into the floor for a stable base.",
            "Pick a weight you can control for 10 smooth reps in week one.",
        ],
        "common_mistakes": [
            "Flaring the elbows straight out to the sides.",
            "Bouncing the dumbbells off the chest.",
            "Arching the lower back off the bench to move heavier weight.",
        ],
    },
    {
        "slug": "dumbbell-shoulder-press",
        "name": "Dumbbell Shoulder Press",
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "primary_muscles": ["Shoulders"],
        "secondary_muscles": ["Triceps", "Upper Chest"],
        "summary": "Press overhead to rebuild pressing strength and shoulder stability.",
        "is_compound": True,
        "video_id": "bmy7tIopNt4",
        "video_title": "Standing Dumbbell Shoulder Press (Tutorial + Tips)",
        "instructions": [
            "Sit tall (or stand) holding a dumbbell just outside each shoulder, palms facing forward.",
            "Brace your core and tuck your ribs so you are not leaning back.",
            "Press the dumbbells up and slightly together until your arms are straight.",
            "Lower under control until the dumbbells are back level with your ears.",
        ],
        "form_tips": [
            "Keep elbows slightly in front of the body, not flared wide.",
            "Squeeze your glutes to stop your lower back arching.",
            "Start seated with back support while you rebuild the pattern.",
        ],
        "common_mistakes": [
            "Turning the press into a backward lean / standing incline press.",
            "Only pressing halfway up.",
            "Letting the dumbbells drift forward away from the shoulders.",
        ],
    },
    {
        "slug": "one-arm-dumbbell-row",
        "name": "One-Arm Dumbbell Row",
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "primary_muscles": ["Lats", "Mid Back"],
        "secondary_muscles": ["Biceps", "Rear Delts"],
        "summary": "A supported back row that builds pulling strength and posture.",
        "is_compound": True,
        "video_id": "fURsHPHgssI",
        "video_title": "Single-Arm Dumbbell Row on a Bench: Perfect Form Tutorial",
        "instructions": [
            "Put one knee and the same-side hand on a bench, other foot on the floor.",
            "Let the dumbbell hang straight down with a flat back, roughly parallel to the floor.",
            "Pull the dumbbell to the side of your ribcage, leading with your elbow.",
            "Pause, squeeze your shoulder blade, then lower all the way down.",
        ],
        "form_tips": [
            "Keep your back flat and hips square to the floor.",
            "Think 'elbow to ceiling', not 'lift with the hand'.",
            "Move slowly — no jerking or twisting the torso.",
        ],
        "common_mistakes": [
            "Rounding the upper back at the bottom.",
            "Rotating the torso to heave the weight up.",
            "Shrugging the shoulder toward the ear instead of rowing.",
        ],
    },
    {
        "slug": "dumbbell-romanian-deadlift",
        "name": "Dumbbell Romanian Deadlift",
        "equipment": "dumbbells",
        "difficulty": "intermediate",
        "primary_muscles": ["Hamstrings", "Glutes"],
        "secondary_muscles": ["Lower Back", "Grip"],
        "summary": "A hip hinge that teaches you to load the hamstrings safely.",
        "is_compound": True,
        "video_id": "aa57T45iFSE",
        "video_title": "How to do a Dumbbell Romanian Deadlift | Proper Form | NASM",
        "instructions": [
            "Stand holding a dumbbell in front of each thigh, knees softly bent.",
            "Push your hips straight back and let the dumbbells slide down the front of your legs.",
            "Stop when you feel a strong hamstring stretch, back still flat, around knee height.",
            "Drive your hips forward to stand tall and squeeze your glutes at the top.",
        ],
        "form_tips": [
            "Keep the dumbbells close — almost brushing your legs.",
            "The movement is hips going back, not the torso folding down.",
            "Keep a long, neutral spine from head to hips.",
        ],
        "common_mistakes": [
            "Rounding the lower back to reach lower.",
            "Turning it into a squat by bending the knees a lot.",
            "Going too heavy before the hinge pattern feels natural.",
        ],
    },
    {
        "slug": "dumbbell-goblet-squat",
        "name": "Dumbbell Goblet Squat",
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Core", "Upper Back"],
        "summary": "The best first squat back — the front load keeps you upright and honest.",
        "is_compound": True,
        "video_id": "6mf0oa2GGUc",
        "video_title": "Goblet Squat Tutorial – Proper Form and Technique",
        "instructions": [
            "Hold one dumbbell vertically against your chest, cupping the top end with both hands.",
            "Stand with feet a little wider than shoulders, toes slightly out.",
            "Sit down between your legs, keeping your chest tall and heels planted.",
            "Push through the whole foot to stand back up, squeezing your glutes.",
        ],
        "form_tips": [
            "Keep your elbows inside your knees at the bottom.",
            "Aim for thighs at least parallel if your mobility allows.",
            "Brace your core as if about to be poked in the stomach.",
        ],
        "common_mistakes": [
            "Heels lifting off the floor.",
            "Knees caving inward on the way up.",
            "Leaning forward so the dumbbell drifts away from the chest.",
        ],
    },
    {
        "slug": "dumbbell-lateral-raise",
        "name": "Dumbbell Lateral Raise",
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "primary_muscles": ["Side Delts"],
        "secondary_muscles": ["Traps"],
        "summary": "An isolation move for wider, healthier-feeling shoulders.",
        "is_compound": False,
        "video_id": "ssAo_xwFt5c",
        "video_title": "How to Do Dumbbell Lateral Raises | Proper Form & Technique",
        "instructions": [
            "Stand tall with a light dumbbell in each hand at your sides, slight bend in the elbows.",
            "Lead with your elbows and raise the dumbbells out to the sides.",
            "Stop when your arms are level with your shoulders.",
            "Lower slowly back to your sides with control.",
        ],
        "form_tips": [
            "Keep your thumbs level with or slightly above your pinkies.",
            "Use a weight light enough that you never swing.",
            "Keep your shoulders down away from your ears.",
        ],
        "common_mistakes": [
            "Using momentum from the hips to fling the weight up.",
            "Shrugging so the traps take over.",
            "Raising the arms far above shoulder height.",
        ],
    },
    {
        "slug": "dumbbell-bicep-curl",
        "name": "Dumbbell Biceps Curl",
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "primary_muscles": ["Biceps"],
        "secondary_muscles": ["Forearms"],
        "summary": "The classic arm builder — simple, and easy to progress week to week.",
        "is_compound": False,
        "video_id": "oNrWBzAYu8E",
        "video_title": "Standing Dumbbell Bicep Curl | Proper Technique + Form Tips",
        "instructions": [
            "Stand tall with a dumbbell in each hand, palms facing forward.",
            "Keeping your upper arms pinned to your sides, curl the dumbbells toward your shoulders.",
            "Squeeze the biceps at the top for a beat.",
            "Lower slowly until your arms are fully straight.",
        ],
        "form_tips": [
            "Keep your elbows still — only the forearms move.",
            "Control the lowering phase; it builds as much as the lift.",
            "Stand still: no rocking or leaning back.",
        ],
        "common_mistakes": [
            "Swinging the torso to start the rep.",
            "Letting the elbows drift forward into a partial front raise.",
            "Cutting the range short at the bottom.",
        ],
    },
    {
        "slug": "dumbbell-hammer-curl",
        "name": "Dumbbell Hammer Curl",
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "primary_muscles": ["Biceps", "Forearms"],
        "secondary_muscles": [],
        "summary": "A neutral-grip curl that is kinder to the wrists and elbows.",
        "is_compound": False,
        "video_id": "4BRAf2BajWw",
        "video_title": "Dumbbell Hammer Curls Tutorial | Perfect Technique",
        "instructions": [
            "Stand with a dumbbell in each hand, palms facing your thighs (neutral grip).",
            "Keep your upper arms locked at your sides and curl the dumbbells up.",
            "Stop when your wrists are just above your elbows, then squeeze.",
            "Lower under control for a two to three count.",
        ],
        "form_tips": [
            "Keep the wrists straight and firm — don't let them bend.",
            "No swinging: pick a weight you can strictly control.",
            "Keep shoulders back and down throughout.",
        ],
        "common_mistakes": [
            "Letting the elbows flare out to the sides.",
            "Shrugging the shoulders up to help.",
            "Dropping the weight quickly instead of lowering it.",
        ],
    },
    {
        "slug": "dumbbell-walking-lunge",
        "name": "Dumbbell Walking Lunge",
        "equipment": "dumbbells",
        "difficulty": "intermediate",
        "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Hamstrings", "Core"],
        "summary": "A single-leg builder for balance, control, and everyday strength.",
        "is_compound": True,
        "video_id": "vYfp2t4XgqQ",
        "video_title": "Walking Lunge Tutorial – Proper Form and Technique",
        "instructions": [
            "Stand tall with a dumbbell in each hand at your sides, core braced.",
            "Step forward into a lunge, bending both knees to about 90 degrees.",
            "Stop just before your back knee touches the floor.",
            "Drive through your front foot to stand, then step through with the other leg.",
        ],
        "form_tips": [
            "Keep your chest up and torso tall the whole way.",
            "Take a stride long enough that your front shin stays near vertical.",
            "Go slow and controlled — this is a balance exercise too.",
        ],
        "common_mistakes": [
            "Front knee collapsing inward.",
            "Leaning the torso forward over the front leg.",
            "Rushing the steps and losing balance.",
        ],
    },
    # ------------------------------------------------------------------ #
    #  BARBELLS
    # ------------------------------------------------------------------ #
    {
        "slug": "barbell-back-squat",
        "name": "Barbell Back Squat",
        "equipment": "barbells",
        "difficulty": "intermediate",
        "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Hamstrings", "Core", "Lower Back"],
        "summary": "The foundational lower-body strength lift. Rebuild it slowly.",
        "is_compound": True,
        "video_id": "8PMjqgR8Wa8",
        "video_title": "How to Barbell Back Squat | A Tutorial for Beginners",
        "instructions": [
            "Set the bar on your upper traps in the rack, hands just outside the shoulders.",
            "Un-rack, step back into a stance slightly wider than your shoulders, toes a little out.",
            "Brace your core, sit your hips down and back until your thighs are at least parallel.",
            "Drive through your whole foot to stand, keeping your chest up.",
        ],
        "form_tips": [
            "Start with just the empty bar for a week to relearn the groove.",
            "Keep your knees tracking out over your toes.",
            "Always squat in a rack with the safety pins set.",
        ],
        "common_mistakes": [
            "Knees caving inward as you stand up.",
            "Rounding the lower back at the bottom.",
            "Coming up onto the toes / heels lifting.",
        ],
    },
    {
        "slug": "barbell-front-squat",
        "name": "Barbell Front Squat",
        "equipment": "barbells",
        "difficulty": "advanced",
        "primary_muscles": ["Quads"],
        "secondary_muscles": ["Glutes", "Upper Back", "Core"],
        "summary": "A front-loaded squat that hammers the quads and demands an upright torso.",
        "is_compound": True,
        "video_id": "Q4REDQdplnM",
        "video_title": "Barbell Front Squat Tutorial",
        "instructions": [
            "Rest the bar on the front of your shoulders, elbows high, fingers loosely under the bar.",
            "Un-rack and step back into a shoulder-width stance.",
            "Keeping your elbows up and torso tall, sit straight down.",
            "Drive up through your midfoot without letting the elbows drop.",
        ],
        "form_tips": [
            "Elbows high is the whole game — point them at the far wall.",
            "Only the fingertips need to be under the bar; it rests on the shoulders.",
            "Build wrist and shoulder mobility first if the rack position pinches.",
        ],
        "common_mistakes": [
            "Elbows dropping, which dumps the bar forward.",
            "Rounding forward out of the bottom.",
            "Loading it heavy before the rack position is comfortable.",
        ],
    },
    {
        "slug": "barbell-bench-press",
        "name": "Barbell Bench Press",
        "equipment": "barbells",
        "difficulty": "intermediate",
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Front Delts", "Triceps"],
        "summary": "The main horizontal press for upper-body strength.",
        "is_compound": True,
        "video_id": "HmzhfGUGQRc",
        "video_title": "Barbell Bench Press Tutorial – Proper Form and Technique",
        "instructions": [
            "Lie back with eyes under the bar, feet flat, shoulder blades pinched together.",
            "Grip a little wider than shoulder width and un-rack to straight arms.",
            "Lower the bar under control to the base of your sternum, elbows about 45 degrees.",
            "Press back up and slightly toward the rack until arms are straight.",
        ],
        "form_tips": [
            "Use a spotter or work inside a rack with safety arms.",
            "Keep your wrists straight, bar over the forearm bones.",
            "Keep your shoulder blades tucked and 'set' the entire set.",
        ],
        "common_mistakes": [
            "Bouncing the bar off the chest.",
            "Elbows flaring to 90 degrees, stressing the shoulders.",
            "Hips lifting off the bench to grind a rep.",
        ],
    },
    {
        "slug": "barbell-deadlift",
        "name": "Barbell Deadlift",
        "equipment": "barbells",
        "difficulty": "advanced",
        "primary_muscles": ["Glutes", "Hamstrings", "Lower Back"],
        "secondary_muscles": ["Lats", "Traps", "Grip", "Core"],
        "summary": "A total-body pull. Technique first, load much later.",
        "is_compound": True,
        "video_id": "S5JSZKURFPo",
        "video_title": "Barbell Deadlift Tutorial – Proper Form and Technique",
        "instructions": [
            "Stand with mid-foot under the bar, shins an inch away, feet hip-width.",
            "Hinge down and grip the bar just outside your legs.",
            "Drop your hips, lift your chest, and pull the slack out of the bar.",
            "Push the floor away and stand tall, keeping the bar dragging up your legs.",
        ],
        "form_tips": [
            "Brace hard before every rep, like bracing for a punch.",
            "Keep the bar in contact with your legs the whole way.",
            "Reset your setup between every rep rather than bouncing.",
        ],
        "common_mistakes": [
            "Rounding the lower back as you break the floor.",
            "Hips shooting up first, turning it into a stiff-leg pull.",
            "Jerking the bar off the floor instead of a smooth pull.",
        ],
    },
    {
        "slug": "barbell-romanian-deadlift",
        "name": "Barbell Romanian Deadlift",
        "equipment": "barbells",
        "difficulty": "intermediate",
        "primary_muscles": ["Hamstrings", "Glutes"],
        "secondary_muscles": ["Lower Back", "Lats", "Grip"],
        "summary": "A top-down hip hinge that builds strong, resilient hamstrings.",
        "is_compound": True,
        "video_id": "S5JSZKURFPo",
        "video_title": "Barbell Deadlift & Hinge Tutorial – Proper Form",
        "instructions": [
            "Start standing tall holding the bar at your hips, knees softly bent.",
            "Push your hips back and lower the bar down the front of your thighs.",
            "Stop at a strong hamstring stretch, roughly just below the knee, back flat.",
            "Drive the hips forward to return to standing and squeeze the glutes.",
        ],
        "form_tips": [
            "Keep the bar touching your legs the whole range.",
            "Knees stay in a fixed soft bend — they don't keep bending.",
            "Think 'push the hips to the wall behind you'.",
        ],
        "common_mistakes": [
            "Letting the bar drift away from the body.",
            "Rounding the back to chase more depth.",
            "Bending the knees more to reach the floor (that's a deadlift).",
        ],
    },
    {
        "slug": "barbell-bent-over-row",
        "name": "Barbell Bent-Over Row",
        "equipment": "barbells",
        "difficulty": "intermediate",
        "primary_muscles": ["Lats", "Mid Back"],
        "secondary_muscles": ["Biceps", "Rear Delts", "Lower Back"],
        "summary": "A heavy horizontal pull to balance out all that pressing.",
        "is_compound": True,
        "video_id": "rqTOAM8WoeM",
        "video_title": "Barbell Bent Over Row Tutorial – Proper Form and Technique",
        "instructions": [
            "Hold the bar with an overhand grip just outside your knees.",
            "Hinge forward to roughly 45 degrees with a flat back, knees bent.",
            "Pull the bar to your lower ribs / upper stomach, elbows close to the body.",
            "Lower under control until your arms are straight.",
        ],
        "form_tips": [
            "Lock your torso angle in place — it should not rise as you pull.",
            "Squeeze your shoulder blades together at the top.",
            "Keep your neck neutral, eyes on the floor a few feet ahead.",
        ],
        "common_mistakes": [
            "Standing up with each rep to heave the weight.",
            "Rounding the back.",
            "Using a stance so upright it becomes a shrug.",
        ],
    },
    {
        "slug": "barbell-overhead-press",
        "name": "Barbell Overhead Press",
        "equipment": "barbells",
        "difficulty": "intermediate",
        "primary_muscles": ["Shoulders"],
        "secondary_muscles": ["Triceps", "Upper Chest", "Core"],
        "summary": "Standing press for real overhead strength and a solid core.",
        "is_compound": True,
        "video_id": "JHXtu-ll9Ik",
        "video_title": "Standing Barbell Press Tutorial – Proper Form and Technique",
        "instructions": [
            "Un-rack the bar onto the front of your shoulders, hands just outside shoulder width.",
            "Stand with feet hip-width, squeeze glutes, brace the core.",
            "Press the bar straight up, moving your head back slightly to clear a path.",
            "Once past your forehead, push your head 'through' and lock out overhead.",
        ],
        "form_tips": [
            "Keep the bar over your mid-foot — a vertical bar path.",
            "Squeeze your glutes to stop the lower back arching.",
            "Finish with the bar stacked over your ears, not in front.",
        ],
        "common_mistakes": [
            "Leaning back into a standing incline press.",
            "Pressing the bar around your face instead of moving the head.",
            "Not finishing the lockout fully overhead.",
        ],
    },
    {
        "slug": "barbell-hip-thrust",
        "name": "Barbell Hip Thrust",
        "equipment": "barbells",
        "difficulty": "beginner",
        "primary_muscles": ["Glutes"],
        "secondary_muscles": ["Hamstrings", "Core"],
        "summary": "The most direct glute builder — easy to load and easy to feel.",
        "is_compound": True,
        "video_id": "pF17m_CXfL0",
        "video_title": "Hip Thrust Tutorial – Proper Form and Technique",
        "instructions": [
            "Sit on the floor with your upper back against a bench, a padded bar over your hips.",
            "Plant your feet flat, shins vertical at the top of the movement.",
            "Drive through your heels and push your hips up until your body is flat from knees to shoulders.",
            "Squeeze your glutes hard at the top, then lower with control.",
        ],
        "form_tips": [
            "Tuck your chin and keep your ribs down — don't arch the back to finish.",
            "Push the floor away through your heels.",
            "Pause for a beat at the top of every rep.",
        ],
        "common_mistakes": [
            "Over-arching the lower back instead of squeezing the glutes.",
            "Feet too far forward so the hamstrings take over.",
            "Only pushing halfway up.",
        ],
    },
    # ------------------------------------------------------------------ #
    #  KETTLEBELLS
    # ------------------------------------------------------------------ #
    {
        "slug": "kettlebell-swing",
        "name": "Kettlebell Swing",
        "equipment": "kettlebells",
        "difficulty": "intermediate",
        "primary_muscles": ["Glutes", "Hamstrings"],
        "secondary_muscles": ["Core", "Lats", "Shoulders"],
        "summary": "Explosive hip power and conditioning in one short, brutal set.",
        "is_compound": True,
        "video_id": "kuZPzr_eldA",
        "video_title": "Kettlebell Swings Tutorial – Proper Form and Technique",
        "instructions": [
            "Stand a foot behind the bell, feet shoulder-width, and hinge to grip it with both hands.",
            "Hike the bell back between your legs like a football snap.",
            "Snap your hips forward hard to float the bell to about chest height.",
            "Let it swing back down, catching it with another hip hinge, and repeat.",
        ],
        "form_tips": [
            "The power is a hip snap, not a squat and not an arm lift.",
            "Keep your arms relaxed — they're just ropes.",
            "Finish each rep standing tall with glutes and abs braced.",
        ],
        "common_mistakes": [
            "Squatting the bell up and down.",
            "Lifting with the shoulders/arms.",
            "Letting the bell drop too low and rounding the back.",
        ],
    },
    {
        "slug": "kettlebell-goblet-squat",
        "name": "Kettlebell Goblet Squat",
        "equipment": "kettlebells",
        "difficulty": "beginner",
        "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Core", "Upper Back"],
        "summary": "Same great first squat as the dumbbell version — the handle just sits nicer.",
        "is_compound": True,
        "video_id": "bOSuODsyd6g",
        "video_title": "Goblet Squats – Kettlebell for Beginners",
        "instructions": [
            "Hold the kettlebell by the horns of the handle, close against your chest.",
            "Set feet slightly wider than shoulders, toes turned out a little.",
            "Sit straight down between your legs, elbows brushing the inside of your knees.",
            "Stand back up by pushing the floor away, staying tall.",
        ],
        "form_tips": [
            "Keep the bell glued to your chest the whole rep.",
            "Keep your weight balanced over your mid-foot.",
            "Brace your core before you descend.",
        ],
        "common_mistakes": [
            "Letting the chest fall forward.",
            "Heels rising off the floor.",
            "Knees caving in as you stand.",
        ],
    },
    {
        "slug": "kettlebell-deadlift",
        "name": "Kettlebell Deadlift",
        "equipment": "kettlebells",
        "difficulty": "beginner",
        "primary_muscles": ["Glutes", "Hamstrings"],
        "secondary_muscles": ["Lower Back", "Core", "Grip"],
        "summary": "The safest way to learn the hinge and the deadlift pattern.",
        "is_compound": True,
        "video_id": "BP3uhdsMlS4",
        "video_title": "Kettlebell Deadlift Tutorial – Proper Form and Technique",
        "instructions": [
            "Stand over the bell with feet hip-width, bell between your arches.",
            "Push your hips back and hinge down to grip the handle with both hands.",
            "Flatten your back, take a breath, and brace.",
            "Stand up by driving your hips forward, then hinge back down to place it.",
        ],
        "form_tips": [
            "Arms stay straight — they're just hooks.",
            "Keep the bell close to your body on the way up and down.",
            "Finish tall with a glute squeeze, no back arch.",
        ],
        "common_mistakes": [
            "Rounding the back to reach the handle.",
            "Squatting the weight up instead of hinging.",
            "Yanking the bell off the floor.",
        ],
    },
    {
        "slug": "kettlebell-clean",
        "name": "Kettlebell Clean",
        "equipment": "kettlebells",
        "difficulty": "advanced",
        "primary_muscles": ["Glutes", "Hamstrings", "Shoulders"],
        "secondary_muscles": ["Core", "Traps", "Biceps"],
        "summary": "Gets the bell to your shoulder to start presses and squats.",
        "is_compound": True,
        "video_id": "ZJuFcYWgHdQ",
        "video_title": "How to Do the Kettlebell Clean (Step-by-Step for Beginners)",
        "instructions": [
            "Start with the bell on the floor slightly outside one foot.",
            "Hinge, grip it with one hand, and hike it back between your legs.",
            "Snap the hips and guide the bell up close to your body, elbow tucking in.",
            "Let the bell 'roll' around the wrist into the racked position at your shoulder — don't let it flip and bang.",
        ],
        "form_tips": [
            "Keep the bell close, like zipping up a jacket.",
            "Loosen your grip as the bell comes up so it rotates smoothly.",
            "Practice with a light bell until the catch is soft.",
        ],
        "common_mistakes": [
            "Letting the bell arc far out then crash onto the forearm.",
            "Gripping too hard so the bell flips over the hand.",
            "Using the arm to curl the bell up instead of the hips.",
        ],
    },
    {
        "slug": "kettlebell-overhead-press",
        "name": "Kettlebell Overhead Press",
        "equipment": "kettlebells",
        "difficulty": "intermediate",
        "primary_muscles": ["Shoulders"],
        "secondary_muscles": ["Triceps", "Core"],
        "summary": "A single-arm press — the offset load makes your core work hard.",
        "is_compound": True,
        "video_id": "Wo1xE5Wp8DQ",
        "video_title": "The Correct Form for Kettlebell Overhead Press",
        "instructions": [
            "Start with the kettlebell racked at one shoulder, bell resting on the back of the forearm.",
            "Stand tall with ribs stacked over hips and glutes squeezed.",
            "Press the bell straight up until your arm is fully locked out, biceps by your ear.",
            "Lower under control back to the racked position.",
        ],
        "form_tips": [
            "Keep your wrist neutral and straight under the bell.",
            "Brace your core hard — the weight is trying to bend you sideways.",
            "Keep the elbow tucked as you start the press.",
        ],
        "common_mistakes": [
            "Leaning away from the bell to press it up.",
            "Letting the wrist bend back under the load.",
            "Not locking out fully at the top.",
        ],
    },
    {
        "slug": "turkish-get-up",
        "name": "Turkish Get-Up",
        "equipment": "kettlebells",
        "difficulty": "advanced",
        "primary_muscles": ["Shoulders", "Core"],
        "secondary_muscles": ["Glutes", "Quads", "Hips"],
        "summary": "A slow, full-body stability drill. Master it light — it's worth it.",
        "is_compound": True,
        "video_id": "5kb9Blkrj2w",
        "video_title": "The Turkish Get Up (step by step)",
        "instructions": [
            "Lie on your back, press a light bell up with one arm, same-side knee bent.",
            "Roll up onto your free elbow, then your hand, keeping the bell locked overhead.",
            "Bridge your hips up and sweep your straight leg back into a half-kneeling position.",
            "Stand up, then reverse every step slowly to return to the floor.",
        ],
        "form_tips": [
            "Keep your eyes on the bell until you are standing.",
            "Practice with a shoe balanced on your fist before you add weight.",
            "Move one deliberate step at a time — there is no rush.",
        ],
        "common_mistakes": [
            "Rushing and losing the vertical arm.",
            "Skipping the elbow-then-hand sequence.",
            "Starting too heavy before the pattern is grooved.",
        ],
    },
    # ------------------------------------------------------------------ #
    #  BODYWEIGHT
    # ------------------------------------------------------------------ #
    {
        "slug": "push-up",
        "name": "Push-Up",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Front Delts", "Triceps", "Core"],
        "summary": "A whole upper body and core in one move, anywhere, no gear.",
        "is_compound": True,
        "video_id": "WDIpL0pjun0",
        "video_title": "How to do a Push-Up | Proper Form & Technique | NASM",
        "instructions": [
            "Start in a plank with hands a little wider than your shoulders, body in a straight line.",
            "Brace your core and squeeze your glutes.",
            "Bend your elbows to about 45 degrees and lower until your chest is just off the floor.",
            "Push the floor away to return to the top.",
        ],
        "form_tips": [
            "Keep a straight line from head to heels — no sagging hips.",
            "Move your chest and hips together as one unit.",
            "If full range is too hard, raise your hands (see Incline Push-Up).",
        ],
        "common_mistakes": [
            "Hips sagging toward the floor.",
            "Only doing a partial range at the top.",
            "Elbows flaring straight out to 90 degrees.",
        ],
    },
    {
        "slug": "incline-push-up",
        "name": "Incline Push-Up",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Front Delts", "Triceps", "Core"],
        "summary": "A push-up with your hands raised — the perfect week-one starting point.",
        "is_compound": True,
        "video_id": "0JUrOH--Kdk",
        "video_title": "How to do an Incline Push-Up | Proper Form & Technique | NASM",
        "instructions": [
            "Place your hands on a sturdy bench, table, or wall, a bit wider than your shoulders.",
            "Step your feet back so your body forms a straight, leaning line.",
            "Lower your chest toward the surface with elbows about 45 degrees.",
            "Press back up to straight arms.",
        ],
        "form_tips": [
            "The higher the surface, the easier — lower it as you get stronger.",
            "Keep your body rigid from head to heels.",
            "Full range beats big numbers with a short range.",
        ],
        "common_mistakes": [
            "Letting the hips pike up or sag down.",
            "Choosing a wobbly surface.",
            "Rushing reps instead of controlling the lower.",
        ],
    },
    {
        "slug": "bodyweight-squat",
        "name": "Bodyweight Squat",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Core", "Hamstrings"],
        "summary": "Rebuild the squat pattern with zero load before you add weight.",
        "is_compound": True,
        "video_id": "P-yaD24bUE8",
        "video_title": "Bodyweight Squat Tutorial – Proper Form and Technique",
        "instructions": [
            "Stand with feet shoulder-width apart, toes slightly turned out.",
            "Reach your arms forward as a counterbalance.",
            "Sit your hips down and back, keeping your heels down and chest tall.",
            "Descend as far as you comfortably can, then stand back up.",
        ],
        "form_tips": [
            "Push your knees out in line with your toes.",
            "Keep your weight spread across the whole foot.",
            "Only go as deep as you can keep a flat back.",
        ],
        "common_mistakes": [
            "Heels lifting off the floor.",
            "Knees caving inward.",
            "Rounding the lower back at the bottom.",
        ],
    },
    {
        "slug": "bodyweight-walking-lunge",
        "name": "Bodyweight Walking Lunge",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Hamstrings", "Core"],
        "summary": "Single-leg strength and balance with no equipment needed.",
        "is_compound": True,
        "video_id": "VHPsWQNC6WM",
        "video_title": "Walking Lunge Exercise Tutorial – Proper Form and Technique",
        "instructions": [
            "Stand tall with your hands on your hips or by your sides.",
            "Step forward and bend both knees toward 90 degrees.",
            "Keep your front shin near vertical and torso upright.",
            "Push through the front foot to stand, then step through with the other leg.",
        ],
        "form_tips": [
            "Look ahead, not down, to help your balance.",
            "Control the descent — don't drop into the bottom.",
            "Hold a wall lightly at first if balance is shaky.",
        ],
        "common_mistakes": [
            "Front knee sliding far past the toes.",
            "Torso pitching forward.",
            "Back knee slamming into the floor.",
        ],
    },
    {
        "slug": "plank",
        "name": "Front Plank",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Core"],
        "secondary_muscles": ["Shoulders", "Glutes"],
        "summary": "Teach your core to stay stiff and protect your spine.",
        "is_compound": False,
        "video_id": "mwlp75MS6Rg",
        "video_title": "How to do a Plank | Proper Form & Technique | NASM",
        "instructions": [
            "Set your forearms on the floor with elbows directly under your shoulders.",
            "Step your feet back so your body is a straight line from head to heels.",
            "Squeeze your glutes and pull your belly button toward your spine.",
            "Hold for time, breathing steadily, then rest.",
        ],
        "form_tips": [
            "Keep your hips level with your shoulders — no sagging or piking.",
            "Look at the floor to keep your neck neutral.",
            "Stop the set when your form breaks, not when you're exhausted.",
        ],
        "common_mistakes": [
            "Hips sagging toward the floor.",
            "Butt piking up into an inverted V.",
            "Holding your breath.",
        ],
    },
    {
        "slug": "side-plank",
        "name": "Side Plank",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Obliques", "Core"],
        "secondary_muscles": ["Glutes", "Shoulders"],
        "summary": "Builds the side-core strength that keeps your torso from tipping.",
        "is_compound": False,
        "video_id": "iNbH7_edNI8",
        "video_title": "Side Plank Tutorial – Proper Form and Technique",
        "instructions": [
            "Lie on your side with your elbow under your shoulder and legs stacked.",
            "Lift your hips until your body is a straight line from head to feet.",
            "Squeeze your glutes and brace your core.",
            "Hold for time, then switch sides.",
        ],
        "form_tips": [
            "Stack your shoulder directly over your elbow.",
            "Keep your hips pushed forward, not rolling back.",
            "Drop to a bent-knee version if the full hold is too much.",
        ],
        "common_mistakes": [
            "Hips sagging toward the floor.",
            "Rotating the chest toward the ground.",
            "Elbow placed ahead of the shoulder.",
        ],
    },
    {
        "slug": "glute-bridge",
        "name": "Glute Bridge",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Glutes"],
        "secondary_muscles": ["Hamstrings", "Core"],
        "summary": "Wake up glutes that have been sitting dormant at a desk.",
        "is_compound": False,
        "video_id": "L9KZfxT654Y",
        "video_title": "Glute Bridge Tutorial – Proper Form and Technique",
        "instructions": [
            "Lie on your back, knees bent, feet flat and about hip-width apart.",
            "Tuck your ribs down and press your lower back lightly into the floor.",
            "Drive through your heels and lift your hips until your body is flat from knees to shoulders.",
            "Squeeze your glutes at the top, then lower with control.",
        ],
        "form_tips": [
            "Push the movement with your glutes, not your lower back.",
            "Keep a straight line — don't over-arch at the top.",
            "Pause and squeeze for a beat on every rep.",
        ],
        "common_mistakes": [
            "Arching the lower back to finish the rep.",
            "Pushing through the toes instead of the heels.",
            "Feet too far away so the hamstrings cramp.",
        ],
    },
    {
        "slug": "bird-dog",
        "name": "Bird Dog",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Core", "Lower Back"],
        "secondary_muscles": ["Glutes", "Shoulders"],
        "summary": "A gentle anti-rotation drill that builds a stable, pain-resistant back.",
        "is_compound": False,
        "video_id": "ZdAHe9_HeEw",
        "video_title": "How to do a Bird Dog | Proper Form & Technique | NASM",
        "instructions": [
            "Start on all fours, hands under shoulders and knees under hips.",
            "Brace your core so your spine is neutral.",
            "Reach one arm forward and the opposite leg back until both are level with your torso.",
            "Return under control and switch sides.",
        ],
        "form_tips": [
            "Keep your hips level — imagine balancing a glass of water on your lower back.",
            "Move slowly; the control is the point.",
            "Only reach as far as you can without twisting.",
        ],
        "common_mistakes": [
            "Rotating the hips as the leg lifts.",
            "Lifting the leg higher than the torso and arching the back.",
            "Rushing through reps.",
        ],
    },
    {
        "slug": "dead-bug",
        "name": "Dead Bug",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Core"],
        "secondary_muscles": ["Hip Flexors"],
        "summary": "Teaches your core to stay braced while your arms and legs move.",
        "is_compound": False,
        "video_id": "bxn9FBrt4-A",
        "video_title": "How to do a Dead Bug | Proper Form & Technique | NASM",
        "instructions": [
            "Lie on your back with arms reaching at the ceiling and knees stacked over hips, bent 90 degrees.",
            "Press your lower back flat into the floor and hold it there.",
            "Slowly lower one arm overhead and the opposite leg toward the floor.",
            "Return to the start and switch sides, keeping the back flat the whole time.",
        ],
        "form_tips": [
            "Exhale as you extend the arm and leg.",
            "Only go as far as you can keep your lower back pinned down.",
            "Keep the movement slow and quiet.",
        ],
        "common_mistakes": [
            "Lower back arching up off the floor.",
            "Holding your breath.",
            "Moving fast and losing the brace.",
        ],
    },
    {
        "slug": "mountain-climbers",
        "name": "Mountain Climbers",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Core"],
        "secondary_muscles": ["Shoulders", "Quads", "Hip Flexors"],
        "summary": "A simple cardio burst you can add to the end of any session.",
        "is_compound": True,
        "video_id": "CQk4MHY2_Tc",
        "video_title": "Mountain Climber Tutorial – Proper Form and Technique",
        "instructions": [
            "Start in a strong push-up plank, wrists under shoulders.",
            "Keep a straight line from head to heels and brace your core.",
            "Drive one knee toward your chest, then switch legs.",
            "Continue alternating at a controlled, steady pace.",
        ],
        "form_tips": [
            "Keep your hips low and level — don't let them bounce up.",
            "Move the legs straight in and out, not side to side.",
            "Start slow; speed can come later.",
        ],
        "common_mistakes": [
            "Hips piking up toward the ceiling.",
            "Rounding the upper back.",
            "Going so fast that form falls apart.",
        ],
    },
    # ------------------------------------------------------------------ #
    #  RESISTANCE BANDS
    # ------------------------------------------------------------------ #
    {
        "slug": "band-pull-apart",
        "name": "Band Pull-Apart",
        "equipment": "bands",
        "difficulty": "beginner",
        "primary_muscles": ["Rear Delts", "Upper Back"],
        "secondary_muscles": ["Traps"],
        "summary": "A 60-second posture and shoulder-health fix. Do it every session.",
        "is_compound": False,
        "video_id": "WqdNDTTe-9g",
        "video_title": "Resistance Band Pull Apart",
        "instructions": [
            "Hold a light band in front of you at shoulder height, hands a bit wider than shoulders.",
            "Keep your arms straight and elbows locked.",
            "Pull the band apart until your arms form a T, squeezing your shoulder blades together.",
            "Return slowly to the start with control.",
        ],
        "form_tips": [
            "Keep your ribs down and shoulders away from your ears.",
            "Pinch your shoulder blades like you're holding a pencil between them.",
            "Use a band light enough to keep the arms straight.",
        ],
        "common_mistakes": [
            "Bending the elbows to cheat the range.",
            "Shrugging the shoulders up.",
            "Letting the band snap back quickly.",
        ],
    },
    {
        "slug": "band-bent-over-row",
        "name": "Band Bent-Over Row",
        "equipment": "bands",
        "difficulty": "beginner",
        "primary_muscles": ["Lats", "Mid Back"],
        "secondary_muscles": ["Biceps", "Rear Delts"],
        "summary": "A joint-friendly back row you can do anywhere with one band.",
        "is_compound": True,
        "video_id": "tcMmJ3c5P8c",
        "video_title": "Band Bent Over Row – Proper Form & Technique",
        "instructions": [
            "Stand on the middle of the band, feet shoulder-width, a handle in each hand.",
            "Hinge forward to about 45 degrees with a flat back and braced core.",
            "Pull the handles to your lower ribs, leading with your elbows.",
            "Squeeze your shoulder blades together, then extend the arms with control.",
        ],
        "form_tips": [
            "Keep your torso angle fixed — don't stand up as you pull.",
            "Keep elbows close to your sides.",
            "Step wider on the band for more resistance.",
        ],
        "common_mistakes": [
            "Rounding the back.",
            "Using the legs and back to jerk the handles up.",
            "Shrugging instead of rowing.",
        ],
    },
    {
        "slug": "band-chest-press",
        "name": "Band Chest Press",
        "equipment": "bands",
        "difficulty": "beginner",
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Front Delts", "Triceps"],
        "summary": "A pressing option with constant tension and no bench needed.",
        "is_compound": True,
        "video_id": "6-86jEAXA08",
        "video_title": "How To: Standing Resistance Band Chest Press",
        "instructions": [
            "Anchor the band behind you at chest height (a door anchor works well).",
            "Face away, a handle in each hand at chest level, elbows bent, one foot forward for balance.",
            "Press your hands forward until your arms are almost straight.",
            "Return slowly, keeping tension, until your hands are back by your chest.",
        ],
        "form_tips": [
            "Keep your shoulders down and back the whole time.",
            "Don't lock the elbows hard at the end — keep a soft bend.",
            "Step further forward to increase the resistance.",
        ],
        "common_mistakes": [
            "Arching the back to push harder.",
            "Letting the elbows drop below shoulder height.",
            "Rushing the return and losing tension.",
        ],
    },
    {
        "slug": "band-squat",
        "name": "Band Squat",
        "equipment": "bands",
        "difficulty": "beginner",
        "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Core"],
        "summary": "Adds gentle load to the squat pattern — great for home days.",
        "is_compound": True,
        "video_id": "Eaqr79zvqIw",
        "video_title": "How To: Resistance Band Squat",
        "instructions": [
            "Stand on the middle of a loop band, feet shoulder-width apart.",
            "Bring the top of the band up to your shoulders, elbows up.",
            "Sit your hips down and back, keeping your chest tall and heels down.",
            "Drive through your feet to stand, pushing your knees out against the band.",
        ],
        "form_tips": [
            "Let the band cue your knees to track outward.",
            "Keep the tension by not fully relaxing at the top.",
            "Use a heavier band or a wider stance for more challenge.",
        ],
        "common_mistakes": [
            "Knees caving in despite the band.",
            "Heels lifting.",
            "Leaning the chest forward.",
        ],
    },
    {
        "slug": "band-lateral-walk",
        "name": "Band Lateral Walk",
        "equipment": "bands",
        "difficulty": "beginner",
        "primary_muscles": ["Glute Medius", "Glutes"],
        "secondary_muscles": ["Quads"],
        "summary": "Fires up the side-glutes that stabilise your knees and hips.",
        "is_compound": False,
        "video_id": "9MuZrYJddcQ",
        "video_title": "Lateral Walk Tutorial – Proper Form and Technique",
        "instructions": [
            "Loop a mini band around your legs just above the knees (or ankles for more).",
            "Set a quarter-squat stance: knees bent, hips back, chest up.",
            "Step sideways, leading with one foot and keeping tension on the band.",
            "Follow with the other foot but never let your feet come closer than hip-width.",
        ],
        "form_tips": [
            "Keep your toes pointing forward the whole time.",
            "Stay low — don't bob up and down as you step.",
            "Take small, controlled steps.",
        ],
        "common_mistakes": [
            "Standing up tall between steps.",
            "Letting the trailing foot snap in and kill the tension.",
            "Feet turning out to the sides.",
        ],
    },
    {
        "slug": "band-face-pull",
        "name": "Band Face Pull",
        "equipment": "bands",
        "difficulty": "beginner",
        "primary_muscles": ["Rear Delts", "Upper Back"],
        "secondary_muscles": ["Rotator Cuff", "Traps"],
        "summary": "The best single move for undoing desk posture and cranky shoulders.",
        "is_compound": False,
        "video_id": "AlTGQrDOd98",
        "video_title": "Banded Face Pulls Tutorial – Proper Form and Technique",
        "instructions": [
            "Anchor a band at about face height and hold one end in each hand.",
            "Step back until there's tension, arms straight out in front, thumbs pointing back.",
            "Pull the band toward your face, splitting your hands apart as you go.",
            "Lead with high elbows and squeeze the rear delts, then return slowly.",
        ],
        "form_tips": [
            "Keep your elbows at or above shoulder height.",
            "Don't jut your head forward to meet the band.",
            "Pause and squeeze at the end of each rep.",
        ],
        "common_mistakes": [
            "Using a band so heavy the elbows drop.",
            "Turning it into a straight row to the chest.",
            "Leaning back and using bodyweight instead of the upper back.",
        ],
    },
    {
        "slug": "band-bicep-curl",
        "name": "Band Biceps Curl",
        "equipment": "bands",
        "difficulty": "beginner",
        "primary_muscles": ["Biceps"],
        "secondary_muscles": ["Forearms"],
        "summary": "Constant-tension curls that are easy on the elbows.",
        "is_compound": False,
        "video_id": "0Q5AxBF6f0M",
        "video_title": "Bicep Curl (bands) | Technique and 3 Most Common Mistakes",
        "instructions": [
            "Stand on the middle of the band with a handle in each hand, palms forward.",
            "Keep your elbows pinned to your sides.",
            "Curl the handles up toward your shoulders, squeezing the biceps.",
            "Lower slowly until your arms are straight, keeping tension.",
        ],
        "form_tips": [
            "Keep your wrists straight and your elbows still.",
            "Stand on more of the band for extra resistance.",
            "Control the lowering — don't let the band yank your arms down.",
        ],
        "common_mistakes": [
            "Elbows drifting forward.",
            "Leaning back to start the curl.",
            "Letting the band snap back at the bottom.",
        ],
    },
    # ------------------------------------------------------------------ #
    #  MACHINES
    # ------------------------------------------------------------------ #
    {
        "slug": "leg-press",
        "name": "Leg Press",
        "equipment": "machines",
        "difficulty": "beginner",
        "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Hamstrings"],
        "summary": "Load the legs safely without needing balance or a spotter.",
        "is_compound": True,
        "video_id": "XNvaNipSycI",
        "video_title": "Leg Press Tutorial",
        "instructions": [
            "Sit back into the machine with your feet shoulder-width on the platform, mid-foot.",
            "Extend your legs to lift the sled and release the safety handles.",
            "Lower the platform under control until your knees reach about 90 degrees.",
            "Press back up through your whole foot without snapping the knees straight.",
        ],
        "form_tips": [
            "Keep your lower back and hips flat against the pad.",
            "Don't let your knees cave inward.",
            "Leave a soft bend in the knees at the top.",
        ],
        "common_mistakes": [
            "Lowering so far your hips curl up off the seat.",
            "Locking the knees hard at the top.",
            "Placing hands on the knees during the press.",
        ],
    },
    {
        "slug": "leg-extension",
        "name": "Leg Extension",
        "equipment": "machines",
        "difficulty": "beginner",
        "primary_muscles": ["Quads"],
        "secondary_muscles": [],
        "summary": "Isolates the quads — handy for rebuilding after knee-shy time off.",
        "is_compound": False,
        "video_id": "xAUvXdHu1sI",
        "video_title": "How to do the Leg Extension properly (in 80 seconds)",
        "instructions": [
            "Adjust the seat so your knees line up with the machine's pivot point.",
            "Set the shin pad just above your ankles and hold the handles.",
            "Straighten your legs smoothly, squeezing the quads at the top.",
            "Lower under control; don't let the weight stack slam.",
        ],
        "form_tips": [
            "Keep your back against the pad and don't bounce.",
            "Pause briefly at full extension.",
            "Start light — this move can feel intense on the knees.",
        ],
        "common_mistakes": [
            "Swinging the torso to fling the weight up.",
            "Seat set wrong so the knee sits ahead of the pivot.",
            "Dropping the weight quickly on the way down.",
        ],
    },
    {
        "slug": "seated-leg-curl",
        "name": "Seated Leg Curl",
        "equipment": "machines",
        "difficulty": "beginner",
        "primary_muscles": ["Hamstrings"],
        "secondary_muscles": ["Calves"],
        "summary": "Direct hamstring work to balance all the quad and glute training.",
        "is_compound": False,
        "video_id": "t9sTSr-JYSs",
        "video_title": "Beginner's Guide: Seated Leg Curl",
        "instructions": [
            "Sit with your back flat against the pad and the leg pad resting on your lower shins.",
            "Lower the thigh pad so it's snug just above your knees.",
            "Curl your heels down and under toward the seat, squeezing the hamstrings.",
            "Return slowly to straight legs without letting the stack crash.",
        ],
        "form_tips": [
            "Keep your torso still — only the knees bend.",
            "Squeeze for a beat at the bottom of the curl.",
            "Keep your feet in a neutral position, toes relaxed.",
        ],
        "common_mistakes": [
            "Lifting the hips off the seat to get more range.",
            "Using momentum instead of a controlled curl.",
            "Setting the thigh pad too loose so your legs lift out.",
        ],
    },
    {
        "slug": "chest-press-machine",
        "name": "Chest Press Machine",
        "equipment": "machines",
        "difficulty": "beginner",
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Front Delts", "Triceps"],
        "summary": "A guided press so you can push a little without a spotter.",
        "is_compound": True,
        "video_id": "gNBU7hmW2EU",
        "video_title": "Chest Press Machine Tutorial | Beginner's Guide to Gym Machines",
        "instructions": [
            "Set the seat so the handles line up with the middle of your chest.",
            "Sit back with your shoulder blades pinched and feet flat.",
            "Press the handles forward until your arms are almost straight.",
            "Return slowly until your hands are back level with your chest.",
        ],
        "form_tips": [
            "Keep your back against the pad — don't lunge forward off it.",
            "Keep wrists straight and elbows a touch below the shoulders.",
            "Stop just short of a hard lockout.",
        ],
        "common_mistakes": [
            "Seat too low, turning it into a shoulder press.",
            "Shrugging the shoulders up to the ears.",
            "Letting the weight stack bang between reps.",
        ],
    },
    {
        "slug": "lat-pulldown",
        "name": "Lat Pulldown",
        "equipment": "machines",
        "difficulty": "beginner",
        "primary_muscles": ["Lats"],
        "secondary_muscles": ["Biceps", "Mid Back", "Rear Delts"],
        "summary": "Build the pulling strength that leads toward your first pull-up.",
        "is_compound": True,
        "video_id": "AOpi-p0cJkc",
        "video_title": "Beginner's Guide: Lat Pulldown",
        "instructions": [
            "Set the thigh pad snug and grip the bar a bit wider than shoulder width.",
            "Sit tall with a slight backward lean and your chest up.",
            "Pull the bar to the top of your chest, driving your elbows down and back.",
            "Return slowly until your arms are fully straight and your shoulders stretch up.",
        ],
        "form_tips": [
            "Start the pull by dropping your shoulder blades down.",
            "Keep the lean slight and fixed — don't row with your whole body.",
            "Bring the bar to your collarbone, not behind your neck.",
        ],
        "common_mistakes": [
            "Using a big backward swing to yank the bar down.",
            "Pulling the bar behind the neck.",
            "Only doing a half rep and never fully straightening the arms.",
        ],
    },
    {
        "slug": "seated-row-machine",
        "name": "Seated Row Machine",
        "equipment": "machines",
        "difficulty": "beginner",
        "primary_muscles": ["Mid Back", "Lats"],
        "secondary_muscles": ["Biceps", "Rear Delts"],
        "summary": "Chest-supported rowing — all back, no lower-back strain.",
        "is_compound": True,
        "video_id": "OeLb503NZHk",
        "video_title": "Seated Cable Row Tutorial: Build a Strong Back with Proper Form",
        "instructions": [
            "Set the chest pad so you can reach the handles with straight arms.",
            "Sit tall with your chest against the pad and feet planted.",
            "Pull the handles to your torso, driving your elbows straight back.",
            "Squeeze your shoulder blades together, then extend the arms with control.",
        ],
        "form_tips": [
            "Keep your chest on the pad the whole set.",
            "Think about pulling with your elbows, not your hands.",
            "Pause and squeeze at the end of each pull.",
        ],
        "common_mistakes": [
            "Leaning back off the pad to move more weight.",
            "Rounding the shoulders forward at the start.",
            "Rushing the return.",
        ],
    },
    {
        "slug": "shoulder-press-machine",
        "name": "Shoulder Press Machine",
        "equipment": "machines",
        "difficulty": "beginner",
        "primary_muscles": ["Shoulders"],
        "secondary_muscles": ["Triceps"],
        "summary": "Overhead pressing on rails — a safe way back to pressing weight.",
        "is_compound": True,
        "video_id": "e5gJP7quyGk",
        "video_title": "Shoulder Press Machine | Proper Technique + Form Tips",
        "instructions": [
            "Set the seat so the handles start at about shoulder height.",
            "Sit back with your back flat against the pad, feet planted.",
            "Press the handles straight up until your arms are nearly straight.",
            "Lower under control back to shoulder height.",
        ],
        "form_tips": [
            "Keep your ribs down — don't arch off the backrest.",
            "Keep your head in a neutral position, not craned forward.",
            "Choose a neutral grip if it feels better on the shoulders.",
        ],
        "common_mistakes": [
            "Seat too high or low, changing the press angle awkwardly.",
            "Arching the lower back to finish the press.",
            "Partial reps that never reach a full lockout.",
        ],
    },
    # ------------------------------------------------------------------ #
    #  CABLES
    # ------------------------------------------------------------------ #
    {
        "slug": "seated-cable-row",
        "name": "Seated Cable Row",
        "equipment": "cables",
        "difficulty": "beginner",
        "primary_muscles": ["Mid Back", "Lats"],
        "secondary_muscles": ["Biceps", "Rear Delts"],
        "summary": "Smooth, constant-tension rowing for a stronger back and better posture.",
        "is_compound": True,
        "video_id": "EU7bOadUsNI",
        "video_title": "Seated Cable Row – Proper Form & Technique",
        "instructions": [
            "Sit with a slight knee bend, feet on the platform, and grab the handle.",
            "Sit tall with a flat back and arms extended, feeling a stretch in your back.",
            "Pull the handle to your stomach, driving your elbows straight back.",
            "Squeeze your shoulder blades, then return slowly to a full stretch.",
        ],
        "form_tips": [
            "Let your shoulder blades move: stretch forward at the front, squeeze at the back.",
            "Keep the torso mostly still — a tiny lean is fine, a big swing is not.",
            "Keep your chest up and shoulders down.",
        ],
        "common_mistakes": [
            "Rocking back and forth with the lower back.",
            "Rounding forward to reach at the front.",
            "Yanking with the arms and never using the back.",
        ],
    },
    {
        "slug": "cable-chest-fly",
        "name": "Cable Chest Fly",
        "equipment": "cables",
        "difficulty": "intermediate",
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Front Delts"],
        "summary": "Isolates the chest with tension through the whole range.",
        "is_compound": False,
        "video_id": "ovFc-5YdcXw",
        "video_title": "How to Perform Cable Flys | Proper Form and Tips",
        "instructions": [
            "Set both pulleys to around shoulder height and take a handle in each hand.",
            "Step forward into a staggered stance with a slight forward lean.",
            "Keep a fixed soft bend in your elbows and open your arms wide until you feel a chest stretch.",
            "Bring the handles together in front of your chest, squeezing the pecs.",
        ],
        "form_tips": [
            "Keep the elbow angle locked — it's a fly, not a press.",
            "Lead the movement with your upper arms, not your hands.",
            "Keep your shoulder blades back and down.",
        ],
        "common_mistakes": [
            "Bending and straightening the elbows (making it a press).",
            "Using too much weight and shrugging the shoulders forward.",
            "Letting the arms go so far back the shoulder gets pinched.",
        ],
    },
    {
        "slug": "cable-tricep-pushdown",
        "name": "Cable Triceps Pushdown",
        "equipment": "cables",
        "difficulty": "beginner",
        "primary_muscles": ["Triceps"],
        "secondary_muscles": [],
        "summary": "Simple, effective triceps work that spares the elbows.",
        "is_compound": False,
        "video_id": "d-ySLTHUgQA",
        "video_title": "Rope Tricep Pushdowns (Tutorial + Tips)",
        "instructions": [
            "Attach a rope or bar to a high pulley and grip it with your elbows tucked at your sides.",
            "Stand tall with a slight forward lean and a braced core.",
            "Straighten your arms down, pushing the attachment toward your thighs.",
            "Squeeze the triceps, then return under control to about 90 degrees at the elbow.",
        ],
        "form_tips": [
            "Keep your elbows pinned to your sides the whole set.",
            "Only the forearms move — the upper arms stay still.",
            "With a rope, spread the ends apart at the bottom.",
        ],
        "common_mistakes": [
            "Elbows drifting forward so the lats and shoulders take over.",
            "Leaning way over to push with bodyweight.",
            "Short reps that never fully straighten the arms.",
        ],
    },
    {
        "slug": "cable-bicep-curl",
        "name": "Cable Biceps Curl",
        "equipment": "cables",
        "difficulty": "beginner",
        "primary_muscles": ["Biceps"],
        "secondary_muscles": ["Forearms"],
        "summary": "Keeps tension on the biceps even at the bottom of the rep.",
        "is_compound": False,
        "video_id": "5z4y7QRTx1w",
        "video_title": "How to: Cable Bicep Curl | Form Tutorial",
        "instructions": [
            "Attach a bar to a low pulley and hold it with an underhand, shoulder-width grip.",
            "Stand tall a step back from the machine, elbows at your sides.",
            "Curl the bar up toward your shoulders, keeping your upper arms still.",
            "Squeeze at the top, then lower slowly until your arms are straight.",
        ],
        "form_tips": [
            "Keep your elbows pinned and your posture upright.",
            "Don't let the weight stack pull your arms behind your body.",
            "Control the lowering phase fully.",
        ],
        "common_mistakes": [
            "Swinging the torso to start each rep.",
            "Elbows travelling forward and up.",
            "Cutting the bottom of the range short.",
        ],
    },
    {
        "slug": "cable-face-pull",
        "name": "Cable Face Pull",
        "equipment": "cables",
        "difficulty": "beginner",
        "primary_muscles": ["Rear Delts", "Upper Back"],
        "secondary_muscles": ["Rotator Cuff", "Traps"],
        "summary": "Shoulder-health gold. A few sets a week keeps pressing pain-free.",
        "is_compound": False,
        "video_id": "7z65m-qWJrA",
        "video_title": "Cable Face Pull (Exercise Library)",
        "instructions": [
            "Set a rope at about face height and hold one end in each hand, palms facing in.",
            "Step back until there's tension, arms extended, core braced.",
            "Pull the rope toward your face, separating your hands past your ears.",
            "Keep your elbows high, squeeze the rear delts, then return slowly.",
        ],
        "form_tips": [
            "Set the pulley at face height, not all the way at the top.",
            "Keep the elbows level with or above the shoulders.",
            "Squeeze the shoulder blades at the end of each rep.",
        ],
        "common_mistakes": [
            "Letting the elbows drop and turning it into a row.",
            "Jutting the head forward to meet the rope.",
            "Using momentum from the legs and back.",
        ],
    },
    {
        "slug": "cable-woodchop",
        "name": "Cable Woodchop",
        "equipment": "cables",
        "difficulty": "intermediate",
        "primary_muscles": ["Obliques", "Core"],
        "secondary_muscles": ["Shoulders", "Glutes"],
        "summary": "Trains rotational core power for sport and everyday twisting.",
        "is_compound": True,
        "video_id": "Gwcf4TOj1hc",
        "video_title": "Cable Woodchop | Proper Form Tutorial for Core Rotation",
        "instructions": [
            "Set the pulley high and grab the handle with both hands, standing side-on.",
            "Set a wide, athletic stance and brace your core.",
            "Pull the handle down and across your body toward the opposite hip, rotating through your trunk.",
            "Return under control to the start, resisting the pull the whole way.",
        ],
        "form_tips": [
            "Rotate through the ribcage and hips, keeping the arms fairly straight.",
            "Let your back foot pivot as you turn.",
            "Move with control — this is about power, not speed with sloppy form.",
        ],
        "common_mistakes": [
            "Only using the arms and not rotating the torso.",
            "Rounding or over-arching the lower back.",
            "Going too heavy and getting yanked off balance.",
        ],
    },
]
