"""Equipment-based exercise library — dumbbells, barbells, kettlebells,
machines, cables, medicine balls and stability balls.

The bodyweight/bands library lives in moves.py; this is the gym side.

`video_id` / `video_title` are filled by tools/find_videos.py, which searches
YouTube and verifies each candidate is actually playable in an embed. They are
intentionally absent here so a missing video is a loud build failure rather
than a broken player in someone's hands.
"""


def E(slug, name, equipment, difficulty, primary, secondary, summary,
      instructions, tips, mistakes, pattern="other", chain=None,
      unilateral=False):
    """One exercise. `chain` is (chain_key, order, scaling_lever) or None."""
    return {
        "slug": slug,
        "name": name,
        "equipment": equipment,
        "difficulty": difficulty,
        "primary_muscles": primary,
        "secondary_muscles": secondary,
        "summary": summary,
        "instructions": instructions,
        "form_tips": tips,
        "common_mistakes": mistakes,
        "is_compound": len(primary) + len(secondary) >= 3,
        "_pattern": pattern,
        "_chain": chain,
        "_unilateral": unilateral,
    }


DUMBBELLS = [
    E("dumbbell-floor-press", "Dumbbell Floor Press", "dumbbells", "beginner",
      ["Chest"], ["Triceps", "Front Delts"],
      "A pressing start point that protects the shoulder by limiting depth.",
      ["Lie on the floor with knees bent and a dumbbell in each hand.",
       "Press the weights up until the arms are straight over the chest.",
       "Lower until the backs of the upper arms touch the floor, then press again."],
      ["The floor stops you at a safe depth — let the triceps rest on it briefly.",
       "Keep the wrists stacked directly over the elbows."],
      ["Flaring the elbows to 90° — keep them nearer 45° from the body.",
       "Bouncing the arms off the floor to start the next rep."],
      pattern="horizontal_push", chain=("db-press", 1, "range_of_motion")),

    E("dumbbell-incline-press", "Dumbbell Incline Press", "dumbbells", "intermediate",
      ["Upper Chest"], ["Front Delts", "Triceps"],
      "Tilts the press toward the upper chest and shoulders.",
      ["Set a bench to about 30°, sit back with a dumbbell on each thigh.",
       "Kick the weights up to shoulder height, palms facing forward.",
       "Press until the arms are straight, then lower under control to chest level."],
      ["30–45° is enough — steeper turns it into a shoulder press.",
       "Keep the shoulder blades pinned back against the bench."],
      ["Setting the bench too upright and losing the chest entirely.",
       "Clanging the dumbbells together at the top."],
      pattern="horizontal_push", chain=("db-press", 3, "body_angle")),

    E("dumbbell-bench-press-neutral", "Dumbbell Neutral-Grip Press", "dumbbells", "beginner",
      ["Chest"], ["Triceps", "Front Delts"],
      "Palms-facing press — the friendliest option for cranky shoulders.",
      ["Lie on a flat bench holding dumbbells with palms facing each other.",
       "Press straight up, keeping the elbows tucked close to the ribs.",
       "Lower slowly until you feel a light stretch across the chest."],
      ["The neutral grip keeps the shoulder in its happiest position.",
       "Drive the feet into the floor for a stable base."],
      ["Letting the elbows drift wide, which defeats the purpose of the grip.",
       "Bouncing at the bottom instead of controlling the stretch."],
      pattern="horizontal_push", chain=("db-press", 2, "lever_length")),

    E("dumbbell-flye", "Dumbbell Flye", "dumbbells", "intermediate",
      ["Chest"], ["Front Delts"],
      "An isolation move that trains the chest through a long stretch.",
      ["Lie on a flat bench with dumbbells pressed over the chest, palms facing.",
       "With a soft, fixed elbow bend, open the arms out in a wide arc.",
       "Stop when the upper arms are level with the torso, then hug them back together."],
      ["Think about hugging a barrel, not pressing.",
       "Go lighter than you expect — the leverage is brutal at the bottom."],
      ["Bending and straightening the elbows, turning it into a bad press.",
       "Dropping below shoulder level and straining the shoulder capsule."],
      pattern="horizontal_push"),

    E("dumbbell-shoulder-press-seated", "Seated Dumbbell Shoulder Press", "dumbbells", "beginner",
      ["Shoulders"], ["Triceps", "Upper Chest"],
      "Overhead pressing with back support so the spine can relax.",
      ["Sit on an upright bench with dumbbells at shoulder height, palms forward.",
       "Press overhead until the arms are straight but not locked hard.",
       "Lower under control until the elbows are level with the shoulders."],
      ["Keep the ribs down — do not arch the lower back to finish the rep.",
       "Let the dumbbells drift slightly together as they rise."],
      ["Pressing the weights forward instead of straight up.",
       "Dropping the elbows far below shoulder height between reps."],
      pattern="vertical_push", chain=("db-overhead", 1, "base_of_support")),

    E("dumbbell-arnold-press", "Arnold Press", "dumbbells", "intermediate",
      ["Shoulders"], ["Triceps", "Upper Chest"],
      "A rotating overhead press that hits front and side delts together.",
      ["Start seated with dumbbells at chest height, palms facing you.",
       "Press up while rotating the palms to face forward.",
       "Reverse the rotation exactly on the way down."],
      ["Rotate smoothly through the whole press, not all at the top.",
       "Use less weight than a straight shoulder press."],
      ["Rushing the rotation and letting the wrists twist under load.",
       "Arching the back to grind out extra reps."],
      pattern="vertical_push", chain=("db-overhead", 2, "range_of_motion")),

    E("dumbbell-push-press", "Dumbbell Push Press", "dumbbells", "advanced",
      ["Shoulders"], ["Quads", "Triceps", "Core"],
      "A leg-assisted overhead press that trains full-body power.",
      ["Stand with dumbbells at shoulder height, feet hip-width.",
       "Dip a few inches at the knees, then drive explosively through the legs.",
       "Use that momentum to punch the weights overhead, then lower to the shoulders."],
      ["The dip is short and sharp — a few inches, not a squat.",
       "Legs and arms should feel like one continuous motion."],
      ["Dipping so deep it becomes a squat-and-press.",
       "Letting the weights crash back down onto the shoulders."],
      pattern="vertical_push", chain=("db-overhead", 3, "power")),

    E("dumbbell-lateral-raise", "Dumbbell Lateral Raise", "dumbbells", "beginner",
      ["Side Delts"], [],
      "The most direct way to build shoulder width.",
      ["Stand with a light dumbbell in each hand, arms at your sides.",
       "With a slight elbow bend, raise the arms out to the sides.",
       "Stop at shoulder height, then lower slowly."],
      ["Lead with the elbows, not the hands.",
       "Light weight and clean form beats heavy swinging every time."],
      ["Swinging the weights up with body English.",
       "Raising above shoulder height, which hands the work to the traps."],
      pattern="vertical_push"),

    E("dumbbell-rear-delt-flye", "Dumbbell Rear Delt Flye", "dumbbells", "beginner",
      ["Rear Delts"], ["Upper Back"],
      "Balances all the pressing and fixes rounded-shoulder posture.",
      ["Hinge forward at the hips until the torso is near parallel to the floor.",
       "Let light dumbbells hang beneath the shoulders, palms facing.",
       "Open the arms out to the sides, squeezing the shoulder blades lightly."],
      ["Think of pulling the arms apart rather than lifting the weights.",
       "Keep the neck long — do not crane it upward."],
      ["Using so much weight that the lats and traps take over.",
       "Rounding the lower back in the hinge."],
      pattern="horizontal_pull"),

    E("dumbbell-bent-over-row", "Dumbbell Bent-Over Row", "dumbbells", "intermediate",
      ["Lats"], ["Upper Back", "Biceps", "Rear Delts"],
      "A two-arm row that builds the whole back and teaches bracing.",
      ["Hinge at the hips with a flat back, dumbbells hanging at arm's length.",
       "Row both weights toward the lower ribs, elbows close to the body.",
       "Lower under control until the arms are straight."],
      ["Squeeze the shoulder blades together at the top of each rep.",
       "Keep the neck in line with the spine."],
      ["Standing up as you row, turning it into a shrug.",
       "Rounding the lower back under load."],
      pattern="horizontal_pull", chain=("db-row", 2, "base_of_support")),

    E("dumbbell-chest-supported-row", "Chest-Supported Dumbbell Row", "dumbbells", "beginner",
      ["Upper Back"], ["Lats", "Biceps", "Rear Delts"],
      "A row with the bench doing the bracing, so the back muscles do the rest.",
      ["Lie face down on an incline bench set to about 45°.",
       "Let the dumbbells hang straight down from the shoulders.",
       "Row them up toward the hips, then lower fully."],
      ["Because the bench supports you, the lower back is spared entirely.",
       "Pause for a beat at the top of every rep."],
      ["Lifting the chest off the bench to help the weight up.",
       "Cutting the bottom of the rep short."],
      pattern="horizontal_pull", chain=("db-row", 1, "base_of_support")),

    E("dumbbell-goblet-squat-tempo", "Tempo Goblet Squat", "dumbbells", "beginner",
      ["Quads"], ["Glutes", "Core"],
      "A slow goblet squat that drills depth and control before load.",
      ["Hold one dumbbell vertically against the chest with both hands.",
       "Squat down over three slow seconds, keeping the chest tall.",
       "Pause one second at the bottom, then stand up normally."],
      ["The weight at the chest acts as a counterbalance — it helps you sit deeper.",
       "Elbows track inside the knees at the bottom."],
      ["Letting the chest collapse forward as you descend.",
       "Rushing the lowering phase, which is the whole point here."],
      pattern="squat", chain=("db-squat", 1, "tempo")),

    E("dumbbell-front-squat", "Dumbbell Front Squat", "dumbbells", "intermediate",
      ["Quads"], ["Glutes", "Core", "Upper Back"],
      "Two dumbbells racked at the shoulders — heavier than a goblet squat.",
      ["Hold a dumbbell on each shoulder, elbows pointing forward.",
       "Squat down until the thighs are at least parallel to the floor.",
       "Drive through the whole foot to stand."],
      ["Keep the elbows high; dropping them pitches you forward.",
       "Brace the core hard before each descent."],
      ["Letting the weights slide off the shoulders as you fatigue.",
       "Heels lifting at the bottom of the squat."],
      pattern="squat", chain=("db-squat", 2, "band_tension")),

    E("dumbbell-bulgarian-split-squat", "Dumbbell Bulgarian Split Squat", "dumbbells", "advanced",
      ["Quads"], ["Glutes", "Core"],
      "One of the hardest leg exercises there is, and worth every rep.",
      ["Stand a stride in front of a bench and rest the top of the rear foot on it.",
       "Hold a dumbbell in each hand at your sides.",
       "Lower until the front thigh is parallel, then drive up through the front heel."],
      ["Almost all the weight belongs on the front leg.",
       "A longer stance targets the glute; shorter hits the quad."],
      ["Pushing off the back foot to help.",
       "Letting the front knee collapse inward."],
      pattern="lunge", chain=("db-lunge", 3, "base_of_support"), unilateral=True),

    E("dumbbell-walking-lunge", "Dumbbell Walking Lunge", "dumbbells", "intermediate",
      ["Quads"], ["Glutes", "Hamstrings", "Core"],
      "Loaded lunges that travel, adding balance and conditioning.",
      ["Hold a dumbbell in each hand at your sides.",
       "Step forward into a lunge until both knees are near 90°.",
       "Drive through the front heel and step straight into the next lunge."],
      ["Take a long enough step that the front shin stays near vertical.",
       "Keep the torso upright the whole way."],
      ["Short, choppy steps that hammer the front knee.",
       "Letting the back knee crash into the floor."],
      pattern="lunge", chain=("db-lunge", 2, "base_of_support"), unilateral=True),

    E("dumbbell-reverse-lunge", "Dumbbell Reverse Lunge", "dumbbells", "beginner",
      ["Quads"], ["Glutes", "Core"],
      "Stepping backwards is far kinder to the knees than stepping forward.",
      ["Hold dumbbells at your sides, feet hip-width.",
       "Step one foot straight back and lower the back knee toward the floor.",
       "Push through the front heel to return to standing."],
      ["Stepping back lets you control the load onto the front leg.",
       "Keep most of the weight in the front foot throughout."],
      ["Leaning forward over the front thigh.",
       "Taking too short a step and jamming the front knee."],
      pattern="lunge", chain=("db-lunge", 1, "base_of_support"), unilateral=True),

    E("dumbbell-romanian-deadlift-single", "Single-Leg Romanian Deadlift", "dumbbells", "advanced",
      ["Hamstrings"], ["Glutes", "Core", "Upper Back"],
      "A hinge and a balance test in one — outstanding for hamstring strength.",
      ["Hold one dumbbell and stand on the opposite leg.",
       "Hinge forward, letting the free leg rise behind you as a counterweight.",
       "Lower until you feel a strong hamstring stretch, then stand tall."],
      ["Hips stay square to the floor — do not let the free hip open up.",
       "A slight bend in the standing knee is correct."],
      ["Rotating the torso open to reach lower.",
       "Rounding the back instead of hinging at the hip."],
      pattern="hinge", chain=("db-hinge", 3, "unilateral"), unilateral=True),

    E("dumbbell-hip-thrust", "Dumbbell Hip Thrust", "dumbbells", "intermediate",
      ["Glutes"], ["Hamstrings", "Core"],
      "The most direct glute builder you can load with a single dumbbell.",
      ["Sit with the upper back against a bench and a dumbbell across the hips.",
       "Drive through the heels to lift the hips until the torso is parallel to the floor.",
       "Squeeze the glutes hard at the top, then lower under control."],
      ["Tuck the chin and keep the ribs down at lockout.",
       "Shins should be roughly vertical at the top."],
      ["Hyperextending the lower back instead of finishing with the glutes.",
       "Pushing through the toes rather than the heels."],
      pattern="hinge", chain=("db-hinge", 2, "range_of_motion")),

    E("dumbbell-farmers-carry", "Dumbbell Farmer's Carry", "dumbbells", "beginner",
      ["Core"], ["Forearms", "Traps", "Glutes"],
      "Pick up something heavy and walk. Brutally effective, impossible to overthink.",
      ["Hold a heavy dumbbell in each hand at your sides.",
       "Stand tall with the shoulders back and ribs down.",
       "Walk in a straight line with controlled steps for the prescribed distance or time."],
      ["Grip hard and breathe shallowly but steadily.",
       "Do not let the weights swing or bang against your legs."],
      ["Leaning back to counterbalance the load.",
       "Shrugging the shoulders up toward the ears."],
      pattern="core_anti_lateral"),

    E("dumbbell-suitcase-carry", "Suitcase Carry", "dumbbells", "intermediate",
      ["Obliques"], ["Core", "Forearms", "Glutes"],
      "A one-sided carry that forces the side of the core to resist tipping.",
      ["Hold one heavy dumbbell in one hand only.",
       "Stand perfectly upright — resist the pull to that side.",
       "Walk for the prescribed distance, then swap hands."],
      ["The whole point is not leaning; go lighter if you tilt.",
       "Keep both shoulders level throughout."],
      ["Leaning away from the weight to compensate.",
       "Rushing the walk instead of controlling each step."],
      pattern="core_anti_lateral", unilateral=True),

    E("dumbbell-bicep-curl-incline", "Incline Dumbbell Curl", "dumbbells", "intermediate",
      ["Biceps"], [],
      "Curling from behind the body puts the biceps under a deep stretch.",
      ["Sit back on a bench inclined to about 60°, arms hanging straight down.",
       "Curl both dumbbells up without letting the elbows drift forward.",
       "Lower all the way until the arms are fully straight."],
      ["The stretch at the bottom is the reason for this variation — use it.",
       "Keep the upper arms still and behind the torso."],
      ["Swinging the elbows forward to start the curl.",
       "Stopping short of full extension at the bottom."],
      pattern="other"),

    E("dumbbell-hammer-curl", "Hammer Curl", "dumbbells", "beginner",
      ["Biceps"], ["Forearms"],
      "A neutral-grip curl that builds arm thickness and forearm strength.",
      ["Stand with dumbbells at your sides, palms facing each other.",
       "Curl up keeping the palms facing in the whole way.",
       "Lower under control to fully straight arms."],
      ["The neutral grip is usually kinder to the wrists and elbows.",
       "Keep the elbows pinned to your ribs."],
      ["Swinging the torso to generate momentum.",
       "Letting the elbows travel forward as you curl."],
      pattern="other"),

    E("dumbbell-overhead-triceps-extension", "Overhead Triceps Extension", "dumbbells", "beginner",
      ["Triceps"], [],
      "Loads the triceps in the stretched position, where they grow best.",
      ["Hold one dumbbell overhead with both hands cupping the top end.",
       "Keeping the elbows pointing forward, lower the weight behind the head.",
       "Extend back to straight arms without letting the elbows flare."],
      ["Elbows stay narrow and high throughout.",
       "Control the lowering — this is where the work happens."],
      ["Letting the elbows flare out wide.",
       "Going so deep the shoulders start to shrug up."],
      pattern="other"),

    E("dumbbell-skull-crusher", "Dumbbell Skull Crusher", "dumbbells", "intermediate",
      ["Triceps"], [],
      "A lying triceps extension with dumbbells, gentler on the elbows than a bar.",
      ["Lie on a bench with dumbbells pressed over the chest, palms facing.",
       "Bend only at the elbows to lower the weights beside the ears.",
       "Extend back to the start without moving the upper arms."],
      ["The upper arms stay locked in place — only the forearms move.",
       "A slight backward tilt of the upper arms increases the stretch."],
      ["Turning it into a press by moving the shoulders.",
       "Letting the elbows drift apart under fatigue."],
      pattern="other"),

    E("dumbbell-shrug", "Dumbbell Shrug", "dumbbells", "beginner",
      ["Traps"], ["Forearms"],
      "Simple, heavy trap work for the top of the back.",
      ["Stand tall with a heavy dumbbell in each hand.",
       "Shrug the shoulders straight up toward the ears.",
       "Hold for a beat, then lower fully."],
      ["Straight up and down — rolling the shoulders adds nothing.",
       "Pause at the top to make lighter weight feel heavier."],
      ["Rolling the shoulders backwards under heavy load.",
       "Using the biceps to help lift the weight."],
      pattern="other"),

    E("dumbbell-renegade-row", "Renegade Row", "dumbbells", "advanced",
      ["Lats"], ["Core", "Obliques", "Biceps"],
      "A plank and a row at once — the core work is the hard part.",
      ["Start in a push-up position gripping a dumbbell in each hand.",
       "Widen the feet for stability and brace hard.",
       "Row one dumbbell to the ribs without letting the hips rotate, then swap."],
      ["Hips stay dead level — that is the whole exercise.",
       "Use hexagonal dumbbells if you have them; round ones roll."],
      ["Twisting the hips toward the rowing side.",
       "Placing the feet too close together to stay stable."],
      pattern="core_anti_rotation", unilateral=True),

    E("dumbbell-thruster", "Dumbbell Thruster", "dumbbells", "advanced",
      ["Quads"], ["Shoulders", "Glutes", "Core"],
      "A front squat straight into an overhead press — a full-body conditioner.",
      ["Hold dumbbells at the shoulders and squat to parallel.",
       "Drive up explosively out of the squat.",
       "Use that momentum to press the weights overhead in one motion."],
      ["The squat and the press should feel like one continuous move.",
       "Breathe at the top, never at the bottom."],
      ["Pausing between the squat and the press and losing the drive.",
       "Pressing forward instead of straight overhead."],
      pattern="conditioning"),

    E("dumbbell-pullover", "Dumbbell Pullover", "dumbbells", "intermediate",
      ["Lats"], ["Chest", "Triceps", "Core"],
      "An old-school move that opens the ribcage and hits the lats from a new angle.",
      ["Lie on a bench holding one dumbbell over the chest with both hands.",
       "Keeping a slight elbow bend, lower the weight back behind the head.",
       "Pull it back over the chest using the lats."],
      ["Stop lowering when the shoulders reach their comfortable limit.",
       "Keep the ribs down rather than arching to reach further."],
      ["Bending the elbows to turn it into an extension.",
       "Going far too heavy on a move with long leverage."],
      pattern="vertical_pull"),
]
