"""Machine, cable, medicine-ball and stability-ball exercises. Schema in gym.py."""
from .gym import E

MACHINES = [
    E("lat-pulldown", "Lat Pulldown", "machines", "beginner",
      ["Lats"], ["Biceps", "Upper Back"],
      "The scalable way to build the pull-up pattern before you can do pull-ups.",
      ["Sit with the thighs locked under the pad and grip the bar wide.",
       "Pull the bar to the upper chest, driving the elbows down and back.",
       "Return under control until the arms are fully straight."],
      ["Lead with the elbows and finish by squeezing the shoulder blades down.",
       "Lean back only slightly, and keep that angle fixed."],
      ["Swinging the torso back to drag the bar down.",
       "Pulling the bar behind the neck, which stresses the shoulders."],
      pattern="vertical_pull", chain=("machine-pulldown", 1, "band_tension")),

    E("machine-close-grip-pulldown", "Close-Grip Pulldown", "machines", "beginner",
      ["Lats"], ["Biceps", "Upper Back"],
      "A narrow, neutral-grip pulldown that emphasises the lower lats.",
      ["Attach a V-handle and sit with the thighs secured.",
       "Pull the handle to the sternum with the elbows tight to the body.",
       "Return slowly to a full stretch overhead."],
      ["The neutral grip is usually easier on the elbows.",
       "Pause briefly at the chest on every rep."],
      ["Rocking backwards to move more weight.",
       "Shrugging the shoulders up at the top of the stretch."],
      pattern="vertical_pull", chain=("machine-pulldown", 2, "lever_length")),

    E("seated-cable-row", "Seated Row", "machines", "beginner",
      ["Upper Back"], ["Lats", "Biceps", "Rear Delts"],
      "A supported horizontal pull that is hard to do badly.",
      ["Sit tall with the feet braced and a slight knee bend.",
       "Pull the handle to the abdomen, elbows brushing the sides.",
       "Let the arms straighten fully and feel the stretch."],
      ["Keep the torso still and let the arms and back do the work.",
       "Squeeze the shoulder blades together at the finish."],
      ["Rowing with the lower back by leaning far forward and back.",
       "Shrugging the shoulders toward the ears."],
      pattern="horizontal_pull"),

    E("leg-press", "Leg Press", "machines", "beginner",
      ["Quads"], ["Glutes", "Hamstrings"],
      "Heavy leg work with the back fully supported.",
      ["Sit with the feet shoulder-width in the middle of the platform.",
       "Lower the platform until the knees reach about 90 degrees.",
       "Press back up without locking the knees hard."],
      ["Keep the lower back flat against the pad at all times.",
       "Higher foot placement uses more glute and hamstring."],
      ["Letting the lower back round off the pad at the bottom.",
       "Slamming the knees into full lockout."],
      pattern="squat"),

    E("hack-squat", "Hack Squat", "machines", "intermediate",
      ["Quads"], ["Glutes"],
      "A guided squat that lets you push the quads hard with no balance demand.",
      ["Set the shoulders under the pads with the feet mid-platform.",
       "Lower until the thighs are at least parallel.",
       "Drive through the whole foot to press back up."],
      ["The fixed path means you can safely train close to failure.",
       "Keep the whole back flat against the pad."],
      ["Letting the heels lift at the bottom.",
       "Bouncing out of the bottom position."],
      pattern="squat"),

    E("leg-extension", "Leg Extension", "machines", "beginner",
      ["Quads"], [],
      "Direct quad isolation, useful for adding volume without systemic fatigue.",
      ["Sit with the pad resting on the lower shins.",
       "Straighten the knees fully and pause at the top.",
       "Lower slowly to the starting position."],
      ["A one-second squeeze at the top is worth more than extra weight.",
       "Align the knee joint with the machine pivot."],
      ["Swinging the weight up with momentum.",
       "Letting the weight stack crash down between reps."],
      pattern="other"),

    E("lying-leg-curl", "Lying Leg Curl", "machines", "beginner",
      ["Hamstrings"], ["Calves"],
      "Trains the hamstrings at the knee joint, which hinges alone cannot do.",
      ["Lie face down with the pad against the lower calves.",
       "Curl the heels toward the glutes as far as possible.",
       "Lower slowly under full control."],
      ["Keep the hips pressed into the bench throughout.",
       "The lowering phase is where most of the growth happens."],
      ["Lifting the hips to help curl the weight.",
       "Using a range so short the hamstrings barely shorten."],
      pattern="other"),

    E("seated-leg-curl", "Seated Leg Curl", "machines", "beginner",
      ["Hamstrings"], [],
      "A leg curl with the hip flexed, which many find more effective than lying.",
      ["Sit with the pad across the lower shins and the thigh pad secured.",
       "Curl the heels back and under the seat.",
       "Return slowly to straight legs."],
      ["The flexed-hip position stretches the hamstrings more.",
       "Pause briefly at the deepest point of the curl."],
      ["Sliding forward out of the seat as you curl.",
       "Rushing the return and losing the stretch."],
      pattern="other"),

    E("machine-chest-press", "Machine Chest Press", "machines", "beginner",
      ["Chest"], ["Triceps", "Front Delts"],
      "Pressing on a fixed path, ideal for training close to failure alone.",
      ["Set the seat so the handles are level with the mid chest.",
       "Press until the arms are straight without locking hard.",
       "Return slowly until a light stretch is felt."],
      ["Seat height is everything on this machine. Adjust it properly.",
       "Keep the shoulder blades pulled back against the pad."],
      ["Setting the handles too high, which turns it into a shoulder press.",
       "Letting the shoulders roll forward at the end of the press."],
      pattern="horizontal_push"),

    E("machine-shoulder-press", "Machine Shoulder Press", "machines", "beginner",
      ["Shoulders"], ["Triceps"],
      "Overhead pressing with the spine fully supported.",
      ["Set the seat so the handles start at shoulder height.",
       "Press overhead until the arms are almost straight.",
       "Lower under control to the starting position."],
      ["The back support means no lower-back strain at all.",
       "Do not slam into lockout."],
      ["Starting with the handles far below the shoulders.",
       "Arching away from the back pad."],
      pattern="vertical_push"),

    E("pec-deck", "Pec Deck", "machines", "beginner",
      ["Chest"], ["Front Delts"],
      "Chest isolation on a fixed arc, safer than heavy dumbbell flyes.",
      ["Sit with the upper arms against the pads at chest height.",
       "Bring the arms together in front of the chest.",
       "Open slowly until a comfortable stretch is felt."],
      ["Squeeze for a beat where the pads meet.",
       "Stop opening when the chest is stretched, not strained."],
      ["Opening so far that the shoulder capsule takes the load.",
       "Using the hands to push rather than the upper arms."],
      pattern="horizontal_push"),

    E("machine-rear-delt-flye", "Reverse Pec Deck", "machines", "beginner",
      ["Rear Delts"], ["Upper Back"],
      "The easiest way to train the rear delts with good form.",
      ["Sit facing the pad with the arms forward at shoulder height.",
       "Open the arms out and back in a wide arc.",
       "Return slowly under control."],
      ["Think about pulling the arms apart, not lifting the weight.",
       "Keep a soft, fixed elbow bend."],
      ["Using so much weight the traps take over.",
       "Jerking at the end range of the movement."],
      pattern="horizontal_pull"),

    E("assisted-pull-up-machine", "Assisted Pull-Up", "machines", "beginner",
      ["Lats"], ["Biceps", "Upper Back", "Core"],
      "A real pull-up with an adjustable amount of help.",
      ["Set the assistance weight and kneel or stand on the pad.",
       "Pull until the chin clears the bar.",
       "Lower under control to a full hang."],
      ["Reduce the assistance a little every couple of weeks.",
       "More assistance weight means an easier rep."],
      ["Using so much assistance the lats barely work.",
       "Bouncing out of the bottom of the hang."],
      pattern="vertical_pull"),

    E("machine-calf-raise", "Standing Calf Raise", "machines", "beginner",
      ["Calves"], [],
      "Loaded calf work through a full range of motion.",
      ["Set the shoulders under the pads with the balls of the feet on the platform.",
       "Rise onto the toes as high as possible.",
       "Lower the heels below the platform for a full stretch."],
      ["Pause at both the top and the bottom of every rep.",
       "The stretch at the bottom matters as much as the squeeze."],
      ["Bouncing rapidly through a tiny range.",
       "Bending the knees to help the movement."],
      pattern="calves"),

    E("machine-abdominal-crunch", "Machine Crunch", "machines", "beginner",
      ["Core"], ["Obliques"],
      "Loaded trunk flexion, which bodyweight crunches cannot easily provide.",
      ["Sit with the chest against the pad and grip the handles.",
       "Crunch forward by shortening the abs, not pulling with the arms.",
       "Return slowly to the start."],
      ["Curl the ribcage toward the pelvis rather than bending at the hips.",
       "Exhale hard at the bottom of the crunch."],
      ["Pulling with the arms and shoulders.",
       "Hinging at the hips instead of flexing the spine."],
      pattern="core_anti_extension"),

    E("smith-machine-squat", "Smith Machine Squat", "machines", "beginner",
      ["Quads"], ["Glutes", "Core"],
      "A squat on a fixed bar path, useful when training alone.",
      ["Set the bar on the upper back and place the feet slightly forward.",
       "Squat down until the thighs are parallel.",
       "Drive up and re-rack by rotating the bar."],
      ["The fixed path removes the balance demand entirely.",
       "Feet slightly forward keeps the knees comfortable."],
      ["Placing the feet directly under the bar, which strains the knees.",
       "Forgetting to disengage the safety hooks before starting."],
      pattern="squat"),

    E("machine-hip-abduction", "Hip Abduction", "machines", "beginner",
      ["Glutes"], [],
      "Targets the side glutes, which stabilise the knee and hip when you run.",
      ["Sit with the pads against the outside of the knees.",
       "Push the knees apart as far as comfortable.",
       "Return slowly against the resistance."],
      ["Leaning forward slightly biases the upper glute.",
       "Pause for a beat at the widest point."],
      ["Slamming the weight open and letting it snap back.",
       "Using the arms to push the pads outward."],
      pattern="other"),

    E("machine-chest-supported-row", "Machine Chest-Supported Row", "machines", "beginner",
      ["Upper Back"], ["Lats", "Biceps", "Rear Delts"],
      "A rowing machine with a chest pad, removing the lower back entirely.",
      ["Set the chest against the pad and grip the handles.",
       "Row back, driving the elbows past the ribs.",
       "Return to a full stretch under control."],
      ["Because the pad supports you, you can push these very hard.",
       "Squeeze the shoulder blades at the end of each rep."],
      ["Pushing the chest off the pad to move more weight.",
       "Cutting the stretch short at the front."],
      pattern="horizontal_pull"),
]

CABLES = [
    E("cable-face-pull", "Cable Face Pull", "cables", "beginner",
      ["Rear Delts"], ["Upper Back", "Traps"],
      "The single best exercise for undoing hours of desk posture.",
      ["Set a rope at face height and grip both ends.",
       "Pull the rope toward the face, separating the hands as you go.",
       "Finish with the hands beside the ears and elbows high."],
      ["Elbows stay at or above shoulder height throughout.",
       "Think about pulling the rope apart, not just back."],
      ["Pulling toward the chest instead of the face.",
       "Using so much weight the torso leans back."],
      pattern="horizontal_pull"),

    E("cable-triceps-pushdown", "Cable Triceps Pushdown", "cables", "beginner",
      ["Triceps"], [],
      "Constant-tension triceps work that is easy on the elbows.",
      ["Set the cable high and grip a bar or rope.",
       "Keeping the elbows pinned to the ribs, extend the arms fully.",
       "Return under control to about 90 degrees at the elbow."],
      ["The upper arms never move. Only the forearms.",
       "Spread a rope apart at the bottom for a stronger contraction."],
      ["Letting the elbows drift forward and away from the body.",
       "Leaning over the bar to press the weight down with bodyweight."],
      pattern="other"),

    E("cable-lateral-raise", "Cable Lateral Raise", "cables", "intermediate",
      ["Side Delts"], [],
      "A lateral raise with tension at the bottom, where dumbbells have none.",
      ["Stand side-on to a low pulley and grip the handle with the far hand.",
       "Raise the arm out to shoulder height.",
       "Lower slowly against the constant pull."],
      ["The cable keeps tension through the whole range, unlike a dumbbell.",
       "Lead with the elbow, not the hand."],
      ["Swinging the body to start the rep.",
       "Raising far above shoulder height."],
      pattern="vertical_push", unilateral=True),

    E("cable-chest-flye", "Cable Chest Flye", "cables", "intermediate",
      ["Chest"], ["Front Delts"],
      "A flye with even tension from stretch to squeeze.",
      ["Set two pulleys at chest height and hold a handle in each hand.",
       "Step forward into a staggered stance with a soft elbow bend.",
       "Bring the hands together in front of the chest, then open slowly."],
      ["Cross the hands slightly at the end for a stronger contraction.",
       "Change pulley height to bias upper or lower chest."],
      ["Bending and straightening the elbows like a press.",
       "Letting the hands drift behind the shoulders at the stretch."],
      pattern="horizontal_push"),

    E("cable-pallof-press", "Cable Pallof Press", "cables", "beginner",
      ["Core"], ["Obliques"],
      "An anti-rotation press. The core works hardest by refusing to move.",
      ["Stand side-on to a chest-height pulley and hold the handle at the sternum.",
       "Press the handle straight out in front of you.",
       "Resist the pull to twist, then return to the chest."],
      ["The further you step from the machine, the harder it gets.",
       "Brace before pressing, and breathe steadily throughout."],
      ["Allowing the torso to rotate toward the machine.",
       "Using the arms to fight the cable instead of the core."],
      pattern="core_anti_rotation", unilateral=True),

    E("cable-woodchop", "Cable Woodchop", "cables", "intermediate",
      ["Obliques"], ["Core", "Shoulders"],
      "A diagonal rotational pull that trains the core the way sport uses it.",
      ["Set the pulley high and grip the handle with both hands.",
       "Pull down and across the body toward the opposite hip.",
       "Return under control along the same path."],
      ["Rotate through the mid-back and hips, not the lower back.",
       "Pivot the back foot as you rotate."],
      ["Yanking with the arms and leaving the trunk still.",
       "Rounding the lower back at the end of the chop."],
      pattern="core_rotation", unilateral=True),

    E("cable-straight-arm-pulldown", "Straight-Arm Pulldown", "cables", "intermediate",
      ["Lats"], ["Core", "Triceps"],
      "Isolates the lats without the biceps taking over.",
      ["Stand facing a high pulley with a bar at arm's length.",
       "Keeping the arms straight, pull the bar down to the thighs.",
       "Return slowly overhead without shrugging."],
      ["A slight forward hinge increases the range.",
       "Feel the lats, not the triceps, doing the work."],
      ["Bending the elbows and turning it into a pushdown.",
       "Using the whole body to drive the bar down."],
      pattern="vertical_pull"),

    E("cable-hip-abduction", "Cable Hip Abduction", "cables", "beginner",
      ["Glutes"], ["Core"],
      "Standing side-glute work with constant tension.",
      ["Attach an ankle cuff to a low pulley and stand side-on.",
       "Lift the outside leg out to the side without leaning.",
       "Return slowly against the cable."],
      ["Keep the torso upright. Do not lean away from the machine.",
       "Hold the top position briefly on each rep."],
      ["Swinging the leg with momentum.",
       "Leaning the torso to fake extra range."],
      pattern="other", unilateral=True),

    E("cable-kickback-glute", "Cable Glute Kickback", "cables", "beginner",
      ["Glutes"], ["Hamstrings", "Core"],
      "Direct glute work through hip extension.",
      ["Attach an ankle cuff and face the machine, holding on for balance.",
       "Drive the working leg back and up, squeezing the glute.",
       "Return under control without letting the weight touch down."],
      ["Keep the movement at the hip, not the lower back.",
       "A slight forward lean of the torso is fine and stable."],
      ["Arching the lower back to lift the leg higher.",
       "Swinging the leg rather than driving it."],
      pattern="hinge", unilateral=True),

    E("cable-bicep-curl", "Cable Bicep Curl", "cables", "beginner",
      ["Biceps"], ["Forearms"],
      "Curling against constant tension from start to finish.",
      ["Stand facing a low pulley with a bar or handles.",
       "Curl up keeping the elbows at your sides.",
       "Lower fully against the cable resistance."],
      ["The cable keeps tension at the top, unlike a free weight.",
       "Stand a step back so the line of pull stays constant."],
      ["Letting the elbows travel forward.",
       "Leaning back to lift heavier."],
      pattern="other"),

    E("cable-upright-row", "Cable Upright Row", "cables", "intermediate",
      ["Side Delts"], ["Traps", "Biceps"],
      "A vertical pull for the side delts and traps.",
      ["Stand facing a low pulley holding a rope or bar.",
       "Pull upward, leading with the elbows to chest height.",
       "Lower under control."],
      ["A wider grip and a lower finish is far kinder to the shoulders.",
       "Stop pulling at chest height."],
      ["Pulling the hands to the chin with a narrow grip.",
       "Shrugging the shoulders to the ears at the top."],
      pattern="vertical_push"),

    E("cable-crunch", "Cable Crunch", "cables", "intermediate",
      ["Core"], ["Obliques"],
      "Loaded ab work that lets you progress beyond endless bodyweight reps.",
      ["Kneel facing a high pulley holding a rope beside the head.",
       "Crunch down by curling the ribs toward the pelvis.",
       "Return slowly without letting the hips move."],
      ["The hips stay fixed. Only the spine flexes.",
       "Exhale fully at the bottom to shorten the abs completely."],
      ["Hinging at the hips instead of flexing the spine.",
       "Pulling with the arms to move the weight."],
      pattern="core_anti_extension"),

    E("cable-single-arm-row", "Cable Single-Arm Row", "cables", "beginner",
      ["Lats"], ["Upper Back", "Biceps"],
      "A one-sided row that lets each side work through its full range.",
      ["Sit or stand facing a low or mid pulley with one handle.",
       "Row the handle to the ribs, elbow tight to the body.",
       "Let the arm travel fully forward and feel the lat stretch."],
      ["Allow the shoulder to reach forward at the front of the rep.",
       "Keep the torso square and still."],
      ["Rotating the torso to help pull.",
       "Cutting the forward stretch short."],
      pattern="horizontal_pull", unilateral=True),
]

MEDICINE_BALL = [
    E("medicine-ball-slam", "Medicine Ball Slam", "medicine_ball", "beginner",
      ["Core"], ["Lats", "Shoulders", "Glutes"],
      "Lift it overhead, throw it down as hard as you can. Deeply satisfying.",
      ["Stand with the ball at your feet, feet shoulder-width.",
       "Lift it overhead, extending fully through the hips.",
       "Slam it into the floor as hard as possible and catch the bounce or pick it up."],
      ["Use a non-bouncing slam ball if you have one.",
       "Exhale sharply on the slam."],
      ["Rounding the back to pick the ball up between reps.",
       "Slamming with the arms only instead of the whole body."],
      pattern="conditioning"),

    E("medicine-ball-rotational-throw", "Rotational Wall Throw", "medicine_ball", "intermediate",
      ["Obliques"], ["Core", "Shoulders", "Glutes"],
      "Explosive rotation against a wall. Power the core can actually express.",
      ["Stand side-on to a solid wall, a couple of feet away, holding the ball at the hip.",
       "Rotate explosively through the hips and throw the ball into the wall.",
       "Catch the rebound and reset for the next rep."],
      ["The power comes from the hips turning, not the arms.",
       "Pivot the back foot fully on every throw."],
      ["Throwing with the arms while the hips stay square.",
       "Using a bouncy ball that rebounds unpredictably."],
      pattern="core_rotation", unilateral=True),

    E("medicine-ball-chest-pass", "Medicine Ball Chest Pass", "medicine_ball", "beginner",
      ["Chest"], ["Triceps", "Shoulders", "Core"],
      "An explosive horizontal push. Pressing power without a heavy load.",
      ["Stand facing a wall holding the ball at the chest.",
       "Push it away explosively, extending the arms fully.",
       "Catch the rebound at the chest and immediately repeat."],
      ["Absorb the catch by letting the elbows bend.",
       "Stand close enough that the rebound returns to your chest."],
      ["Pushing slowly, which defeats the purpose entirely.",
       "Standing too far back to catch the ball cleanly."],
      pattern="horizontal_push"),

    E("medicine-ball-russian-twist", "Medicine Ball Russian Twist", "medicine_ball", "intermediate",
      ["Obliques"], ["Core"],
      "A seated rotation with load, for the sides of the trunk.",
      ["Sit with the knees bent and heels lightly on the floor, holding the ball.",
       "Lean back to about 45 degrees and brace.",
       "Rotate the ball from hip to hip, turning the shoulders with it."],
      ["Turn the ribcage, not just the arms.",
       "Lifting the feet makes it considerably harder."],
      ["Moving only the arms while the torso stays still.",
       "Rounding the lower back as you lean away."],
      pattern="core_rotation"),

    E("medicine-ball-wall-ball", "Wall Ball", "medicine_ball", "intermediate",
      ["Quads"], ["Shoulders", "Glutes", "Core"],
      "A squat and a throw combined. One of the best conditioning tools there is.",
      ["Hold the ball at the chest and squat to parallel facing a wall.",
       "Drive up explosively and throw the ball to a high target.",
       "Catch it on the way down and flow straight into the next squat."],
      ["Let the catch pull you into the next squat.",
       "Aim for a consistent spot on the wall each rep."],
      ["Pausing between the squat and the throw.",
       "Catching with locked arms instead of absorbing."],
      pattern="conditioning"),

    E("medicine-ball-overhead-slam-lunge", "Med Ball Overhead Lunge", "medicine_ball", "advanced",
      ["Quads"], ["Shoulders", "Core", "Glutes"],
      "Lunging with the ball locked overhead. Brutal on the core and shoulders.",
      ["Press the ball overhead with the arms locked.",
       "Step forward or backward into a lunge, keeping the ball still.",
       "Drive back to standing without letting the arms drift."],
      ["The arms must stay by the ears the whole time.",
       "Go lighter than you think. Overhead is unforgiving."],
      ["Letting the ball drift forward in front of the head.",
       "Arching the lower back to keep the ball up."],
      pattern="lunge", unilateral=True),

    E("medicine-ball-vsit-pass", "Med Ball V-Sit Hold", "medicine_ball", "advanced",
      ["Core"], ["Obliques"],
      "A loaded hollow position. Simple to describe, very hard to hold.",
      ["Sit balanced on the tailbone with the legs raised and knees bent.",
       "Hold the ball out in front of the chest.",
       "Keep the lower back rounded and hold for the prescribed time."],
      ["Lower the legs to make it harder, raise them to make it easier.",
       "Breathe steadily. Do not hold your breath."],
      ["Letting the lower back arch off the hollow shape.",
       "Resting the feet on the floor mid-hold."],
      pattern="core_anti_extension"),

    E("medicine-ball-dead-bug", "Med Ball Dead Bug", "medicine_ball", "beginner",
      ["Core"], ["Obliques"],
      "A dead bug with the ball pressed between opposite hand and knee.",
      ["Lie on your back and press the ball between one hand and the opposite knee.",
       "Extend the free arm and free leg toward the floor.",
       "Return to the start and repeat, then switch sides."],
      ["Press the ball and knee together hard throughout.",
       "The lower back stays flat on the floor at all times."],
      ["Letting the back arch as the free limbs extend.",
       "Rushing through the reps."],
      pattern="core_anti_extension"),
]

STABILITY_BALL = [
    E("stability-ball-hamstring-curl", "Stability Ball Hamstring Curl", "stability_ball", "intermediate",
      ["Hamstrings"], ["Glutes", "Core"],
      "One of the best hamstring exercises requiring no machine at all.",
      ["Lie on your back with the heels on top of the ball.",
       "Lift the hips into a bridge.",
       "Curl the ball toward the glutes with the heels, then push it back out."],
      ["Keep the hips high the entire time. Do not let them sag.",
       "Straightening the legs slowly is the hardest part."],
      ["Letting the hips drop as the ball rolls out.",
       "Rushing so the ball wobbles out of control."],
      pattern="hinge"),

    E("stability-ball-rollout", "Stability Ball Rollout", "stability_ball", "intermediate",
      ["Core"], ["Lats", "Shoulders"],
      "An anti-extension rollout with a friendlier learning curve than a wheel.",
      ["Kneel with the forearms on the ball.",
       "Roll the ball forward, extending the body into a long line.",
       "Pull it back using the abs, not the hips."],
      ["Keep the ribs down and the glutes squeezed throughout.",
       "Roll only as far as you can go without the back arching."],
      ["Letting the lower back sag at full extension.",
       "Pulling back with the hips instead of the abs."],
      pattern="core_anti_extension"),

    E("stability-ball-stir-the-pot", "Stir the Pot", "stability_ball", "advanced",
      ["Core"], ["Shoulders", "Obliques"],
      "A plank on the ball with slow circles. Deceptively brutal.",
      ["Set up in a plank with the forearms on the ball and feet wide.",
       "Keeping the body rigid, draw small circles with the forearms.",
       "Complete equal circles in both directions."],
      ["The body must not move at all. Only the arms travel.",
       "Start with tiny circles and grow them as you improve."],
      ["Letting the hips rock or rotate with the circles.",
       "Making circles so large the form collapses."],
      pattern="core_anti_rotation"),

    E("stability-ball-pike", "Stability Ball Pike", "stability_ball", "advanced",
      ["Core"], ["Shoulders", "Hamstrings"],
      "A push-up position pike that folds the body over the hips.",
      ["Start in a push-up position with the shins on top of the ball.",
       "Keeping the legs straight, lift the hips toward the ceiling.",
       "Roll the ball toward the hands, then lower back to a flat plank."],
      ["Push the floor away with the hands to keep the shoulders stable.",
       "Keep the legs straight for maximum difficulty."],
      ["Bending the knees and turning it into a tuck.",
       "Letting the shoulders collapse toward the ears."],
      pattern="core_anti_extension"),

    E("stability-ball-wall-squat", "Stability Ball Wall Squat", "stability_ball", "beginner",
      ["Quads"], ["Glutes"],
      "The ball rolls down the wall with you, guiding a clean squat path.",
      ["Place the ball between your lower back and a wall.",
       "Walk the feet slightly forward and lean into the ball.",
       "Squat until the thighs are parallel, then press back up."],
      ["An excellent starting point if free squats feel unstable.",
       "Keep the weight in the heels and mid-foot."],
      ["Letting the knees travel far past the toes.",
       "Coming up onto the toes at the bottom."],
      pattern="squat"),

    E("stability-ball-back-extension", "Stability Ball Back Extension", "stability_ball", "beginner",
      ["Lower Back"], ["Glutes", "Hamstrings"],
      "Gentle, supported strengthening for the lower back.",
      ["Lie face down over the ball with the feet braced against a wall.",
       "Let the torso curl over the ball, hands at the temples.",
       "Extend the spine until the body forms a straight line, then lower."],
      ["Stop at a straight line. There is no benefit to arching past it.",
       "Move slowly and deliberately throughout."],
      ["Hyperextending the spine at the top.",
       "Using momentum to swing up."],
      pattern="hinge"),

    E("stability-ball-dumbbell-press", "Stability Ball Dumbbell Press", "stability_ball", "intermediate",
      ["Chest"], ["Triceps", "Core", "Glutes"],
      "A dumbbell press with the bench replaced by an unstable ball.",
      ["Lie back with the upper back and head on the ball, hips lifted.",
       "Hold dumbbells over the chest and press them up.",
       "Lower under control, keeping the hips level throughout."],
      ["The hips must stay up. Treat it as a glute bridge that also presses.",
       "Go lighter than you would on a bench."],
      ["Letting the hips sag between reps.",
       "Using weights heavy enough to destabilise you."],
      pattern="horizontal_push"),

    E("stability-ball-knee-tuck", "Stability Ball Knee Tuck", "stability_ball", "intermediate",
      ["Core"], ["Hip Flexors", "Shoulders"],
      "A plank with the feet on the ball, drawing the knees to the chest.",
      ["Start in a push-up position with the shins on the ball.",
       "Pull the knees toward the chest, rolling the ball forward.",
       "Extend back to a long plank under control."],
      ["Keep the shoulders stacked over the hands.",
       "Do not let the hips pike upward as you tuck."],
      ["Letting the lower back sag in the plank position.",
       "Rushing so the ball skids out from under you."],
      pattern="core_anti_extension"),
]
