"""Barbell and kettlebell exercises. See gym.py for the schema."""
from .gym import E

BARBELLS = [
    E("barbell-back-squat", "Barbell Back Squat", "barbells", "intermediate",
      ["Quads"], ["Glutes", "Hamstrings", "Core"],
      "The classic lower-body strength builder.",
      ["Set the bar across the upper back, not the neck, and unrack it.",
       "Take two steps back, feet shoulder-width, toes slightly out.",
       "Sit down between the hips until at least parallel, then drive up."],
      ["Brace as if about to be punched before every rep.",
       "Knees track over the middle toes, never caving inward."],
      ["Letting the hips shoot up first, turning it into a good morning.",
       "Cutting depth short as the weight climbs."],
      pattern="squat", chain=("bb-squat", 2, "band_tension")),

    E("barbell-front-squat", "Barbell Front Squat", "barbells", "advanced",
      ["Quads"], ["Core", "Upper Back", "Glutes"],
      "Bar in front shifts the load to the quads and punishes any forward lean.",
      ["Rack the bar across the front delts with the elbows high.",
       "Keep the torso as upright as possible and squat down.",
       "Drive up without letting the elbows drop."],
      ["High elbows are non-negotiable — the bar rolls the moment they drop.",
       "A fingertip grip is fine; the shelf is the shoulders, not the hands."],
      ["Dropping the elbows and dumping the bar forward.",
       "Rounding the upper back under the load."],
      pattern="squat", chain=("bb-squat", 3, "body_angle")),

    E("barbell-box-squat", "Barbell Box Squat", "barbells", "beginner",
      ["Quads"], ["Glutes", "Core"],
      "A squat to a box that teaches consistent depth and builds confidence.",
      ["Set a box or bench behind you at roughly parallel height.",
       "Squat back until you sit lightly on the box.",
       "Stand up without rocking or bouncing off it."],
      ["Touch the box, do not collapse onto it.",
       "The box gives every rep identical depth, which is ideal for learning."],
      ["Dropping down and losing core tension on the box.",
       "Rocking backwards to build momentum out of the bottom."],
      pattern="squat", chain=("bb-squat", 1, "range_of_motion")),

    E("barbell-romanian-deadlift", "Barbell Romanian Deadlift", "barbells", "intermediate",
      ["Hamstrings"], ["Glutes", "Upper Back", "Core"],
      "The best hamstring builder in the gym, and a hinge-pattern masterclass.",
      ["Stand holding the bar at hip height, feet hip-width.",
       "Push the hips straight back, sliding the bar down the thighs.",
       "Stop when the hamstrings are fully stretched, then drive the hips forward."],
      ["The bar stays in contact with the legs the whole way.",
       "Knees stay softly bent but fixed. This is a hip hinge, not a squat."],
      ["Rounding the lower back to reach lower.",
       "Bending the knees more to lower the bar further."],
      pattern="hinge", chain=("bb-hinge", 2, "range_of_motion")),

    E("barbell-conventional-deadlift", "Barbell Deadlift", "barbells", "advanced",
      ["Glutes"], ["Hamstrings", "Upper Back", "Core", "Traps"],
      "Lifting a loaded bar off the floor. The whole posterior chain at once.",
      ["Stand with mid-foot under the bar, shins almost touching it.",
       "Hinge down and grip just outside the legs, chest up and back flat.",
       "Push the floor away and stand tall, finishing with the glutes."],
      ["Take the slack out of the bar before you pull.",
       "The bar should travel in a straight vertical line."],
      ["Jerking the bar off the floor with a rounded back.",
       "Hyperextending backwards at lockout."],
      pattern="hinge", chain=("bb-hinge", 3, "range_of_motion")),

    E("barbell-hip-thrust", "Barbell Hip Thrust", "barbells", "intermediate",
      ["Glutes"], ["Hamstrings", "Core"],
      "The heaviest way to load the glutes directly.",
      ["Sit with the upper back on a bench and the bar across the hips on a pad.",
       "Drive through the heels until hips, knees and shoulders form a line.",
       "Squeeze hard at the top, then lower under control."],
      ["Tuck the chin and keep the ribs down at the top.",
       "Pause for a full second at lockout on every rep."],
      ["Arching the lower back to fake extra range.",
       "Letting the knees flare or collapse at the top."],
      pattern="hinge", chain=("bb-hinge", 1, "range_of_motion")),

    E("barbell-bench-press", "Barbell Bench Press", "barbells", "intermediate",
      ["Chest"], ["Triceps", "Front Delts"],
      "The benchmark upper-body pressing lift.",
      ["Lie back with eyes under the bar and grip a little wider than shoulders.",
       "Unrack and lower the bar to the lower chest with elbows around 45 degrees.",
       "Press back up and slightly toward the face."],
      ["Keep the shoulder blades pinched and the feet planted.",
       "Wrists stacked over the elbows, bar low in the palm."],
      ["Flaring the elbows to 90 degrees, which stresses the shoulder.",
       "Bouncing the bar off the chest."],
      pattern="horizontal_push", chain=("bb-press", 2, "band_tension")),

    E("barbell-incline-bench-press", "Barbell Incline Press", "barbells", "intermediate",
      ["Upper Chest"], ["Front Delts", "Triceps"],
      "Tilts the bench press toward the upper chest.",
      ["Set the bench to roughly 30 degrees and grip slightly wider than shoulders.",
       "Lower the bar to just below the collarbone.",
       "Press back up over the upper chest."],
      ["30 degrees is plenty. Steeper becomes a shoulder press.",
       "Keep the shoulder blades retracted against the bench."],
      ["Bouncing the bar off the upper chest.",
       "Lifting the hips off the bench to press more weight."],
      pattern="horizontal_push", chain=("bb-press", 3, "body_angle")),

    E("barbell-overhead-press", "Barbell Overhead Press", "barbells", "intermediate",
      ["Shoulders"], ["Triceps", "Core", "Upper Chest"],
      "Standing strict press. A genuine test of upper-body strength.",
      ["Hold the bar at the front shoulders, hands just outside shoulder width.",
       "Brace the core and squeeze the glutes.",
       "Press straight up, moving the head back slightly, until the bar is overhead."],
      ["Finish with the bar stacked over the mid-foot, not in front.",
       "Squeeze the glutes to stop the lower back arching."],
      ["Leaning back excessively to clear the chin.",
       "Pressing the bar forward around the face."],
      pattern="vertical_push", chain=("bb-overhead", 1, "base_of_support")),

    E("barbell-bent-over-row", "Barbell Bent-Over Row", "barbells", "intermediate",
      ["Lats"], ["Upper Back", "Biceps", "Rear Delts"],
      "The heaviest horizontal pull most people will ever do.",
      ["Hinge to about 45 degrees with a flat back, bar hanging at arm's length.",
       "Row the bar to the lower ribs, elbows driving back.",
       "Lower under control without standing up."],
      ["Hold the torso angle constant for the whole set.",
       "Pull with the elbows, not the hands."],
      ["Standing up progressively as the set goes on.",
       "Jerking the bar with the lower back."],
      pattern="horizontal_pull", chain=("bb-row", 1, "body_angle")),

    E("barbell-pendlay-row", "Pendlay Row", "barbells", "advanced",
      ["Upper Back"], ["Lats", "Biceps"],
      "A row from a dead stop on the floor each rep. Pure back power.",
      ["Set the torso parallel to the floor with the bar on the ground.",
       "Explosively row the bar to the lower chest.",
       "Return it all the way to the floor and reset before the next rep."],
      ["Every rep starts from a dead stop. No bouncing.",
       "The torso must not rise at all during the pull."],
      ["Letting the hips rise to help the bar up.",
       "Failing to touch the floor between reps."],
      pattern="horizontal_pull", chain=("bb-row", 2, "power")),

    E("barbell-good-morning", "Good Morning", "barbells", "advanced",
      ["Hamstrings"], ["Glutes", "Lower Back", "Core"],
      "A hinge with the bar on the back. Humbling and highly effective.",
      ["Set a light bar across the upper back as in a squat.",
       "Push the hips back and hinge the torso toward parallel.",
       "Drive the hips forward to return upright."],
      ["Start far lighter than feels necessary.",
       "Keep the back flat and the knees softly bent."],
      ["Rounding the back at the bottom of the hinge.",
       "Turning it into a squat by bending the knees."],
      pattern="hinge"),

    E("barbell-front-rack-lunge", "Front-Rack Barbell Lunge", "barbells", "advanced",
      ["Quads"], ["Glutes", "Core", "Upper Back"],
      "Lunging with the bar racked in front. A serious core and balance challenge.",
      ["Rack the bar on the front delts with high elbows.",
       "Step back into a lunge, lowering the back knee toward the floor.",
       "Drive through the front heel to stand."],
      ["Keep the elbows high or the bar will pull you forward.",
       "Take a long step to keep the front shin vertical."],
      ["Letting the torso pitch forward.",
       "Stepping too short and stressing the front knee."],
      pattern="lunge", unilateral=True),

    E("barbell-landmine-press", "Landmine Press", "barbells", "beginner",
      ["Shoulders"], ["Upper Chest", "Triceps", "Core"],
      "An angled press that suits shoulders which dislike vertical pressing.",
      ["Wedge one end of a barbell into a corner or landmine holder.",
       "Hold the free end at shoulder height with one hand.",
       "Press up and slightly forward along the arc, then lower."],
      ["The arc sits between a bench press and an overhead press.",
       "Brace the core to stop the torso twisting."],
      ["Twisting the whole body to push the weight.",
       "Letting the elbow flare wide at the bottom."],
      pattern="vertical_push", unilateral=True),

    E("barbell-shrug", "Barbell Shrug", "barbells", "beginner",
      ["Traps"], ["Forearms"],
      "Heavy, direct trap work.",
      ["Hold the bar at arm's length in front of the thighs.",
       "Shrug the shoulders straight up as high as possible.",
       "Pause, then lower fully to a full stretch."],
      ["Use straps if grip fails before the traps do.",
       "Pure vertical movement. No rolling."],
      ["Bending the arms to help the lift.",
       "Bouncing the weight with the knees."],
      pattern="other"),

    E("barbell-curl", "Barbell Curl", "barbells", "beginner",
      ["Biceps"], ["Forearms"],
      "The simplest way to load the biceps heavily.",
      ["Stand holding the bar at shoulder width, palms up.",
       "Curl to shoulder height keeping the elbows at your sides.",
       "Lower under control to fully straight arms."],
      ["Keep the elbows still. They are a hinge, not a lever.",
       "An EZ bar is kinder if your wrists complain."],
      ["Swinging the torso to start each rep.",
       "Stopping short of full extension."],
      pattern="other"),

    E("barbell-close-grip-bench", "Close-Grip Bench Press", "barbells", "intermediate",
      ["Triceps"], ["Chest", "Front Delts"],
      "A bench press variation that makes the triceps the prime mover.",
      ["Grip the bar at roughly shoulder width, no narrower.",
       "Lower to the lower chest keeping the elbows tucked close.",
       "Press back up, focusing on locking out with the triceps."],
      ["Shoulder-width is close enough. Narrower just hurts the wrists.",
       "Elbows stay tight to the ribs throughout."],
      ["Gripping so narrow the wrists bend painfully.",
       "Letting the elbows flare out mid-press."],
      pattern="horizontal_push", chain=("bb-press", 1, "lever_length")),

    E("barbell-hip-hinge-rack-pull", "Rack Pull", "barbells", "intermediate",
      ["Upper Back"], ["Glutes", "Hamstrings", "Traps"],
      "A deadlift starting from knee height, letting you overload the top half.",
      ["Set the bar on rack pins at about knee height.",
       "Grip it as for a deadlift with a flat back and braced core.",
       "Drive the hips forward to lock out, then lower to the pins."],
      ["The shortened range lets you handle more than a full deadlift.",
       "Reset your brace between every rep."],
      ["Yanking the bar and losing the flat back.",
       "Leaning back excessively at lockout."],
      pattern="hinge"),
]

KETTLEBELLS = [
    E("kettlebell-goblet-squat", "Kettlebell Goblet Squat", "kettlebells", "beginner",
      ["Quads"], ["Glutes", "Core"],
      "The friendliest loaded squat there is.",
      ["Hold the bell by the horns against the chest.",
       "Squat between the hips, keeping the chest tall.",
       "Drive through the whole foot to stand."],
      ["The front load acts as a counterweight and helps you sit deeper.",
       "Elbows brush the inside of the knees at the bottom."],
      ["Letting the bell drift away from the chest.",
       "Rounding the upper back as you descend."],
      pattern="squat"),

    E("kettlebell-swing", "Kettlebell Swing", "kettlebells", "intermediate",
      ["Glutes"], ["Hamstrings", "Core", "Shoulders"],
      "An explosive hip hinge. Power and conditioning in one movement.",
      ["Stand with the bell a foot in front of you and hinge to grip it.",
       "Hike it back between the legs, then snap the hips forward hard.",
       "Let the bell float to chest height, then guide it back down."],
      ["The arms are ropes. The hips do all the work.",
       "Snap the glutes hard and stand tall at the top."],
      ["Squatting the bell up instead of hinging.",
       "Lifting with the shoulders rather than the hips."],
      pattern="hinge", chain=("kb-swing", 1, "power")),

    E("kettlebell-single-arm-swing", "Single-Arm Kettlebell Swing", "kettlebells", "advanced",
      ["Glutes"], ["Hamstrings", "Core", "Obliques"],
      "A one-handed swing that adds a heavy anti-rotation demand.",
      ["Set up as for a two-hand swing but grip with one hand.",
       "Hinge, hike and snap the hips as normal.",
       "Resist the pull to rotate as the bell rises, then swap hands."],
      ["Keep the shoulders square to the front throughout.",
       "The free arm can mirror the working arm for balance."],
      ["Letting the torso twist toward the working side.",
       "Gripping so tight the forearm fails before the hips."],
      pattern="hinge", chain=("kb-swing", 2, "unilateral"), unilateral=True),

    E("kettlebell-clean", "Kettlebell Clean", "kettlebells", "advanced",
      ["Glutes"], ["Shoulders", "Core", "Traps"],
      "Bringing the bell from the floor to the rack position in one motion.",
      ["Hike the bell back between the legs as in a swing.",
       "Snap the hips and guide the bell close to the body.",
       "Rotate the hand around the bell so it lands softly on the forearm."],
      ["Keep the bell close. A wide arc means it will bang your wrist.",
       "Think of pulling the bell into the rack, not swinging it up."],
      ["Letting the bell flip over and crash onto the wrist.",
       "Using the arm instead of the hips to move the bell."],
      pattern="hinge", unilateral=True),

    E("kettlebell-turkish-get-up", "Turkish Get-Up", "kettlebells", "advanced",
      ["Core"], ["Shoulders", "Glutes", "Obliques"],
      "A slow, deliberate journey from lying to standing under load.",
      ["Lie on your back with one arm pressing the bell straight up.",
       "Roll to the opposite elbow, then the hand, and bridge the hips up.",
       "Sweep the leg through to a lunge and stand, then reverse every step."],
      ["The eyes stay on the bell for most of the movement.",
       "Learn it with a shoe balanced on the fist before adding weight."],
      ["Rushing the transitions instead of owning each position.",
       "Letting the pressing arm bend at any point."],
      pattern="core_anti_lateral", unilateral=True),

    E("kettlebell-front-rack-carry", "Kettlebell Front-Rack Carry", "kettlebells", "intermediate",
      ["Core"], ["Shoulders", "Upper Back", "Glutes"],
      "Carrying weight at the chest forces the whole trunk to stay braced.",
      ["Clean one or two bells to the rack position at the chest.",
       "Stand tall with the ribs down and elbows in.",
       "Walk in a straight line for the prescribed distance."],
      ["Breathe shallowly but do not hold your breath.",
       "Keep the wrists straight, not bent back."],
      ["Leaning back to support the front load.",
       "Letting the elbows drift out and down."],
      pattern="core_anti_extension"),

    E("kettlebell-halo", "Kettlebell Halo", "kettlebells", "beginner",
      ["Shoulders"], ["Core", "Upper Back"],
      "A shoulder mobility drill that doubles as a warm-up.",
      ["Hold the bell upside down by the horns at chest height.",
       "Circle it around the head, staying close to the skull.",
       "Complete equal circles in both directions."],
      ["Keep the ribs down. Do not arch as the bell passes behind.",
       "Go slowly and stay close to the head."],
      ["Using a bell far too heavy for a mobility drill.",
       "Letting the lower back arch as the bell passes behind."],
      pattern="mobility"),

    E("kettlebell-windmill", "Kettlebell Windmill", "kettlebells", "advanced",
      ["Obliques"], ["Shoulders", "Hamstrings", "Core"],
      "A loaded side bend that builds shoulder stability and hip mobility together.",
      ["Press one bell overhead and turn the feet away from that arm.",
       "Keeping the overhead arm locked, hinge sideways and reach the free hand down.",
       "Stand back up while keeping the eyes on the bell."],
      ["The overhead arm stays perfectly vertical throughout.",
       "The movement is a hinge to the side, not a pure bend."],
      ["Bending the overhead elbow.",
       "Rounding the spine to reach the floor."],
      pattern="core_anti_lateral", unilateral=True),

    E("kettlebell-snatch", "Kettlebell Snatch", "kettlebells", "advanced",
      ["Glutes"], ["Shoulders", "Core", "Traps"],
      "Floor to overhead in one explosive movement.",
      ["Hike the bell back and snap the hips as in a swing.",
       "As the bell rises, pull it in close and punch the hand through.",
       "Finish with the arm locked overhead and the bell on the forearm."],
      ["Punch through late so the bell does not flip onto the wrist.",
       "Master the swing and clean before attempting this."],
      ["Letting the bell arc wide and crash down onto the forearm.",
       "Muscling it up with the shoulder instead of the hips."],
      pattern="conditioning", unilateral=True),

    E("kettlebell-suitcase-deadlift", "Kettlebell Suitcase Deadlift", "kettlebells", "beginner",
      ["Glutes"], ["Hamstrings", "Obliques", "Core"],
      "A one-sided deadlift that teaches bracing against a tipping load.",
      ["Stand with one bell beside the foot.",
       "Hinge down with a flat back and grip it.",
       "Stand tall without letting the torso tilt toward the bell."],
      ["Both shoulders stay level for the entire rep.",
       "Brace the opposite side of the core hard."],
      ["Leaning sideways toward the weight.",
       "Rounding the back to reach the handle."],
      pattern="hinge", unilateral=True),

    E("kettlebell-goblet-reverse-lunge", "Goblet Reverse Lunge", "kettlebells", "beginner",
      ["Quads"], ["Glutes", "Core"],
      "A loaded reverse lunge with the bell held at the chest for balance.",
      ["Hold the bell at the chest by the horns.",
       "Step one foot back and lower the knee toward the floor.",
       "Drive through the front heel to return to standing."],
      ["The front load helps you stay upright.",
       "Keep most of the weight in the front foot."],
      ["Letting the torso fold forward.",
       "Taking too short a step backwards."],
      pattern="lunge", unilateral=True),

    E("kettlebell-overhead-press", "Kettlebell Overhead Press", "kettlebells", "intermediate",
      ["Shoulders"], ["Triceps", "Core"],
      "Pressing from the rack position, where the bell sits on the forearm.",
      ["Clean the bell to the rack position at the shoulder.",
       "Press overhead, rotating the palm to face forward.",
       "Lower back to the rack under control."],
      ["The offset load makes the core work far harder than a dumbbell.",
       "Keep the ribs down and the glutes tight."],
      ["Arching the lower back to finish the press.",
       "Letting the bell hang away from the forearm."],
      pattern="vertical_push", unilateral=True),
]
