"""Extra bodyweight & resistance-band exercises for the dedicated section.

These fill out the progression chains defined in ``chains.py``. Content only —
movement pattern, chain position and scaling lever are applied from chains.py at
seed time. Videos are focused "how to / proper form" demos on YouTube.
"""

MOVES = [
    # ---------- Horizontal push ----------
    {
        "slug": "wall-push-up",
        "name": "Wall Push-Up",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Front Delts", "Triceps"],
        "summary": "The gentlest way into pressing — learn the plank line with almost no load.",
        "is_compound": True,
        "video_id": "dhjjqFfUVlg",
        "video_title": "Wall Push-Up",
        "instructions": [
            "Stand a foot or two back from a wall, hands on it at shoulder height and width.",
            "Straighten your body into one line from head to heels, core braced.",
            "Bend your elbows to about 45 degrees and bring your chest toward the wall.",
            "Press back to straight arms. Step further from the wall to make it harder.",
        ],
        "form_tips": [
            "Keep your body rigid — no sagging or piking at the hips.",
            "Move your chest and hips together as one unit.",
            "The further your feet are from the wall, the harder it gets.",
        ],
        "common_mistakes": [
            "Bending only at the hips instead of the elbows.",
            "Letting the head drop forward.",
            "Standing too close so there's almost no range.",
        ],
    },
    {
        "slug": "knee-push-up",
        "name": "Knee Push-Up",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Front Delts", "Triceps", "Core"],
        "summary": "A full-range push-up from the knees — the bridge to your first floor push-up.",
        "is_compound": True,
        "video_id": "WDIpL0pjun0",
        "video_title": "How to do a Push-Up (with regressions) | NASM",
        "instructions": [
            "Kneel and place your hands a little wider than your shoulders.",
            "Walk your hands forward so your body is a straight line from knees to head.",
            "Lower your chest all the way to the floor, elbows about 45 degrees.",
            "Press back up to straight arms without letting your hips sag.",
        ],
        "form_tips": [
            "Hips in line with your shoulders — don't pike up.",
            "Go all the way down; full range beats extra reps.",
            "Cross your ankles and lift your feet for a cleaner line.",
        ],
        "common_mistakes": [
            "Bending at the hips so only the shoulders move.",
            "Half reps at the top.",
            "Hands too far back, under the chest instead of the shoulders.",
        ],
    },
    {
        "slug": "decline-push-up",
        "name": "Decline Push-Up",
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "primary_muscles": ["Upper Chest", "Chest"],
        "secondary_muscles": ["Front Delts", "Triceps", "Core"],
        "summary": "Feet elevated shifts the load onto the upper chest and shoulders.",
        "is_compound": True,
        "video_id": "SKPab2YC8BE",
        "video_title": "How To: Decline Push-Up",
        "instructions": [
            "Set up in a push-up position with your feet on a chair, step or low bench.",
            "Hands slightly wider than your shoulders, body in a straight line.",
            "Lower your chest toward the floor, elbows tucked to about 45 degrees.",
            "Press back up, keeping your hips level with your shoulders.",
        ],
        "form_tips": [
            "The higher the feet, the harder — start low.",
            "Brace your core so your lower back doesn't arch.",
            "Keep your neck neutral, eyes down.",
        ],
        "common_mistakes": [
            "Hips sagging or piking.",
            "Only lowering halfway.",
            "Feet on something unstable.",
        ],
    },
    {
        "slug": "deficit-push-up",
        "name": "Deficit Push-Up",
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Front Delts", "Triceps"],
        "summary": "Hands raised so your chest drops below them — extra range and a loaded stretch.",
        "is_compound": True,
        "video_id": "bKqlcTE9F1Q",
        "video_title": "Deficit Push-up Tutorial",
        "instructions": [
            "Place each hand on a sturdy raised surface — books, low blocks, or parallettes.",
            "Set a straight body line with hands under your shoulders.",
            "Lower until your chest sinks below the level of your hands.",
            "Press back up to straight arms, staying rigid throughout.",
        ],
        "form_tips": [
            "Start with a small deficit (2–4 inches) and build up.",
            "Control the bottom — that's the whole point of the move.",
            "Keep the raised surfaces stable and even.",
        ],
        "common_mistakes": [
            "Bouncing out of the stretched bottom position.",
            "Letting the shoulders shrug up toward the ears.",
            "Hips dropping as you fatigue.",
        ],
    },
    {
        "slug": "archer-push-up",
        "name": "Archer Push-Up",
        "equipment": "bodyweight",
        "difficulty": "advanced",
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Front Delts", "Triceps", "Core"],
        "summary": "Most of your weight goes onto one arm while the other stays straight as an outrigger.",
        "is_compound": True,
        "video_id": "L109Ad4zCR4",
        "video_title": "Archer Push Ups Tutorial With Correct Form",
        "instructions": [
            "Start in a push-up with your hands roughly twice shoulder-width apart.",
            "Bend one arm and lean your weight heavily onto it, keeping the other arm straight.",
            "Lower until your chest nears the floor on the working side.",
            "Press back to the centre and repeat on the other side.",
        ],
        "form_tips": [
            "Lean toward the working arm — don't just go straight up and down.",
            "Keep your body aligned from feet to head.",
            "Use it as a drop-set partner: archer reps, then finish with full push-ups.",
        ],
        "common_mistakes": [
            "Bending the 'straight' arm and turning it into a wide push-up.",
            "Hips twisting toward the floor.",
            "Not leaning enough, so the load stays split.",
        ],
    },
    {
        "slug": "pike-push-up",
        "name": "Pike Push-Up",
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "primary_muscles": ["Shoulders"],
        "secondary_muscles": ["Triceps", "Upper Chest"],
        "summary": "An inverted-V press that turns the push-up into overhead shoulder work.",
        "is_compound": True,
        "video_id": "pHR5yG6xBps",
        "video_title": "Pike Push Up Tutorial For Beginners (With Progressions)",
        "instructions": [
            "From a push-up position, walk your feet in and lift your hips into an upside-down V.",
            "Hands a little wider than shoulders, head between your arms.",
            "Bend your elbows and lower the top of your head toward the floor.",
            "Press back up until your arms are straight.",
        ],
        "form_tips": [
            "The more vertical your torso, the more it hits the shoulders.",
            "Elevate your feet on a step to make it harder.",
            "Keep your legs as straight as your hamstrings allow.",
        ],
        "common_mistakes": [
            "Letting the hips drop so it becomes a regular push-up.",
            "Flaring the elbows straight out.",
            "Looking forward instead of keeping the neck neutral.",
        ],
    },
    # ---------- Vertical push (band) ----------
    {
        "slug": "band-overhead-press",
        "name": "Band Overhead Press",
        "equipment": "bands",
        "difficulty": "beginner",
        "primary_muscles": ["Shoulders"],
        "secondary_muscles": ["Triceps", "Core"],
        "summary": "Press a band overhead — constant tension, easy on the shoulders, scalable by band.",
        "is_compound": True,
        "video_id": "rtqZLw8IeyU",
        "video_title": "Resistance Band Single Arm Overhead Press",
        "instructions": [
            "Stand on the middle of the band, feet hip-width, a handle at each shoulder.",
            "Stack your ribs over your hips and brace your core and glutes.",
            "Press the handles straight up until your arms are fully extended.",
            "Lower under control back to shoulder height.",
        ],
        "form_tips": [
            "Keep your wrists straight and stacked over your elbows.",
            "Step wider on the band or use a heavier band for more resistance.",
            "Don't lean back — press the band, don't arch around it.",
        ],
        "common_mistakes": [
            "Turning it into a backward-leaning standing incline press.",
            "Pressing only halfway up.",
            "Letting the band snap the arms down on the way back.",
        ],
    },
    # ---------- Vertical pull (band) ----------
    {
        "slug": "band-lat-pulldown",
        "name": "Band Lat Pulldown",
        "equipment": "bands",
        "difficulty": "beginner",
        "primary_muscles": ["Lats"],
        "secondary_muscles": ["Biceps", "Mid Back"],
        "summary": "Anchor a band high and pull down — the closest thing to a lat pulldown with no machine.",
        "is_compound": True,
        "video_id": "o5bXFrdw5iI",
        "video_title": "Resistance Band Lat Pulldown",
        "instructions": [
            "Anchor a band above head height — a door anchor at the top, or over a sturdy bar.",
            "Kneel or stand tall facing the anchor, an end of the band in each hand, arms overhead.",
            "Pull your elbows down and back toward your ribs, squeezing your shoulder blades.",
            "Return slowly until your arms are fully straight and your shoulders stretch up.",
        ],
        "form_tips": [
            "Start the pull by dropping your shoulder blades, not by bending the elbows.",
            "Keep a tall spine and a slight backward lean, fixed.",
            "Step back from the anchor for more tension.",
        ],
        "common_mistakes": [
            "Using a big body swing to yank the band down.",
            "Shrugging the shoulders up at the top.",
            "Half reps that never let the lats stretch.",
        ],
    },
    {
        "slug": "band-straight-arm-pulldown",
        "name": "Band Straight-Arm Pulldown",
        "equipment": "bands",
        "difficulty": "intermediate",
        "primary_muscles": ["Lats"],
        "secondary_muscles": ["Core", "Rear Delts"],
        "summary": "A long-lever lat move that also teaches you to brace against a pull.",
        "is_compound": False,
        "video_id": "5gHyAq4O-sQ",
        "video_title": "Resistance Band Straight Arm Lat Pulldown (At Home)",
        "instructions": [
            "Anchor a band at about chest or head height and face it.",
            "Hold the band with both hands, arms straight out in front, slight elbow bend.",
            "Keeping your arms nearly straight, pull the band down in an arc to your thighs.",
            "Return slowly, resisting the band, and brace so your torso doesn't get pulled forward.",
        ],
        "form_tips": [
            "Lock a soft elbow bend and keep it fixed the whole rep.",
            "Squeeze your abs to stop your lower back arching.",
            "Feel the lats, not the triceps, doing the work.",
        ],
        "common_mistakes": [
            "Bending and straightening the elbows (that's a pushdown).",
            "Leaning the whole torso forward and back.",
            "Letting the ribs flare and the back arch.",
        ],
    },
    # ---------- Squat / lunge ----------
    {
        "slug": "split-squat",
        "name": "Split Squat",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Hamstrings", "Core"],
        "summary": "A static lunge — both feet stay planted so you can focus on one leg at a time.",
        "is_compound": True,
        "video_id": "yhMiMbc2O2M",
        "video_title": "Split Squat / Static Lunge Tutorial",
        "instructions": [
            "Step one foot forward and one back into a stable split stance, torso tall.",
            "Bend both knees straight down until your back knee nearly touches the floor.",
            "Keep your front shin close to vertical and your weight through the front heel.",
            "Drive through the front foot to stand, then finish all reps before switching legs.",
        ],
        "form_tips": [
            "Both knees bend together — think 'down', not 'forward'.",
            "Keep your front knee tracking over your toes, not caving in.",
            "Hold a wall or chair lightly if your balance is shaky.",
        ],
        "common_mistakes": [
            "Leaning the torso forward over the front leg.",
            "Front knee sliding far past the toes.",
            "Pushing off the back foot instead of loading the front leg.",
        ],
    },
    {
        "slug": "reverse-lunge",
        "name": "Reverse Lunge",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Hamstrings", "Core"],
        "summary": "Step back into the lunge — kinder on the knees than a forward lunge and easy to balance.",
        "is_compound": True,
        "video_id": "ALl174GTuoY",
        "video_title": "Reverse Lunge Form for Beginners (Step-by-Step)",
        "instructions": [
            "Stand tall, then take a controlled step straight back with one foot.",
            "Lower until both knees are bent about 90 degrees, back knee near the floor.",
            "Keep your torso upright and your weight on the front foot.",
            "Drive through the front heel to step back to standing, then alternate.",
        ],
        "form_tips": [
            "Step back far enough that your front shin stays near vertical.",
            "Look ahead, not down, for balance.",
            "Lower with control — don't drop the back knee onto the floor.",
        ],
        "common_mistakes": [
            "Short step so the front knee jams forward.",
            "Torso pitching forward.",
            "Front knee caving inward on the way up.",
        ],
    },
    {
        "slug": "bulgarian-split-squat",
        "name": "Bulgarian Split Squat",
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Hamstrings", "Core", "Adductors"],
        "summary": "Back foot elevated — one of the hardest things you can do to a leg with no equipment.",
        "is_compound": True,
        "video_id": "ygT5pIDXKjQ",
        "video_title": "Bulgarian Split Squat Tutorial (Proper Technique & Form)",
        "instructions": [
            "Stand a stride in front of a bench or chair; rest the top of your back foot on it.",
            "Set your front foot far enough forward that the knee stays over the mid-foot.",
            "Lower straight down until your back knee is just off the floor.",
            "Drive through the front foot to stand. Finish all reps, then switch.",
        ],
        "form_tips": [
            "A slight forward torso lean biases the glute; staying vertical biases the quad.",
            "Keep the front heel planted the whole time.",
            "Hold a doorframe lightly for balance while you learn it.",
        ],
        "common_mistakes": [
            "Front foot too close, so the knee shoots forward and the heel lifts.",
            "Pushing off the back foot instead of loading the front leg.",
            "Losing balance and rushing the reps.",
        ],
    },
    {
        "slug": "cossack-squat",
        "name": "Cossack Squat",
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "primary_muscles": ["Quads", "Glutes", "Adductors"],
        "secondary_muscles": ["Hamstrings", "Core"],
        "summary": "A deep side-to-side squat that builds single-leg strength and hip mobility together.",
        "is_compound": True,
        "video_id": "shYSWbqBJPM",
        "video_title": "Cossack Squat Tutorial & Progressions",
        "instructions": [
            "Stand with your feet well wider than your shoulders, toes slightly out.",
            "Shift your weight onto one leg and sit down into it, keeping that heel planted.",
            "Let the other leg straighten, toes up, as you descend as far as your hips allow.",
            "Push back to the centre and shift to the other side.",
        ],
        "form_tips": [
            "Keep your chest lifted and core tight so your back doesn't round.",
            "Only go as deep as you can control — depth comes with practice.",
            "Hold your hands out front or a light support as a counterweight.",
        ],
        "common_mistakes": [
            "Bending-leg heel lifting off the floor.",
            "Rounding the back to reach lower.",
            "Knee caving inward on the working leg.",
        ],
    },
    {
        "slug": "box-pistol-squat",
        "name": "Box Pistol Squat",
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Hamstrings", "Core", "Hip Flexors"],
        "summary": "A single-leg squat down to a box or chair — the doorway to a full pistol.",
        "is_compound": True,
        "video_id": "WPd7KXNA0k4",
        "video_title": "How to: Box Pistol Squat",
        "instructions": [
            "Stand in front of a box or chair, balancing on one leg, other leg extended forward.",
            "Sit your hips back and down under control until you touch the box.",
            "Keep the free leg and both arms reaching forward as a counterweight.",
            "Stand back up through the working heel without pushing off the box.",
        ],
        "form_tips": [
            "Use a higher box to regress, lower to progress.",
            "Keep the working heel flat — elevate it slightly if your ankles are tight.",
            "Touch the box lightly; don't crash and rebound.",
        ],
        "common_mistakes": [
            "Dropping onto the box and bouncing up.",
            "Heel lifting off the floor.",
            "Knee caving in as you stand.",
        ],
    },
    {
        "slug": "pistol-squat",
        "name": "Pistol Squat",
        "equipment": "bodyweight",
        "difficulty": "advanced",
        "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Hamstrings", "Core", "Hip Flexors", "Calves"],
        "summary": "A full-depth squat on one leg — the benchmark for lower-body strength without weights.",
        "is_compound": True,
        "video_id": "vq5-vdgJc0I",
        "video_title": "How to Get Your First PISTOL SQUAT (Step-by-Step Progression)",
        "instructions": [
            "Balance on one leg with the other extended straight in front, arms forward.",
            "Sit back and down slowly, keeping the working heel flat and chest up.",
            "Descend until the back of your thigh meets your calf.",
            "Drive straight back up without letting the free foot touch down.",
        ],
        "form_tips": [
            "Slow eccentrics (5s down to a box) build the strength to stand back up.",
            "Hold a light band or doorframe for assistance while you develop it.",
            "Keep the extended leg as straight and high as your mobility allows.",
        ],
        "common_mistakes": [
            "Heel popping up and the weight shifting to the toes.",
            "Knee collapsing inward under load.",
            "Falling backward at the bottom instead of controlling the descent.",
        ],
    },
    {
        "slug": "wall-sit",
        "name": "Wall Sit",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Quads"],
        "secondary_muscles": ["Glutes", "Core"],
        "summary": "An isometric quad burner you can do anywhere — hold time is the progression.",
        "is_compound": False,
        "video_id": "JQ2JBphtUk8",
        "video_title": "Wall Sit | Proper Form Tutorial for Leg Endurance",
        "instructions": [
            "Stand with your back flat against a wall, feet about hip-width and a step forward.",
            "Slide down the wall until your thighs are parallel to the floor.",
            "Knees stacked over your ankles, weight in your heels.",
            "Hold for time, breathing steadily, then slide back up.",
        ],
        "form_tips": [
            "Aim for a 90-degree bend at the knees and hips.",
            "Keep your whole back in contact with the wall.",
            "Progress by adding 5–10 seconds each week.",
        ],
        "common_mistakes": [
            "Knees drifting past the toes (feet too close to the wall).",
            "Weight on the toes instead of the heels.",
            "Holding your breath.",
        ],
    },
    # ---------- Hinge ----------
    {
        "slug": "band-good-morning",
        "name": "Band Good Morning",
        "equipment": "bands",
        "difficulty": "beginner",
        "primary_muscles": ["Hamstrings", "Glutes"],
        "secondary_muscles": ["Lower Back", "Core"],
        "summary": "A standing hip hinge loaded across the shoulders by a band — teaches the RDL pattern safely.",
        "is_compound": True,
        "video_id": "fJA39ZOVaEQ",
        "video_title": "How To Do Banded Good Mornings",
        "instructions": [
            "Stand on the middle of a band, feet shoulder-width, and loop the top over the back of your shoulders.",
            "Soften your knees and brace your core.",
            "Push your hips straight back, letting your torso hinge forward with a flat back.",
            "Stop at a strong hamstring stretch, then drive your hips forward to stand tall.",
        ],
        "form_tips": [
            "Hips travel back, not the chest folding down.",
            "Keep a fixed soft knee bend — the knees don't keep bending.",
            "Keep the band settled on muscle, not on your neck.",
        ],
        "common_mistakes": [
            "Rounding the lower back to reach further.",
            "Turning it into a squat by bending the knees.",
            "Standing on too little band so there's no resistance.",
        ],
    },
    {
        "slug": "band-pull-through",
        "name": "Band Pull-Through",
        "equipment": "bands",
        "difficulty": "beginner",
        "primary_muscles": ["Glutes", "Hamstrings"],
        "secondary_muscles": ["Core", "Lower Back"],
        "summary": "The workhorse loaded hip hinge for band training — all glute, no lower-back strain.",
        "is_compound": True,
        "video_id": "NO-NevrDrjE",
        "video_title": "Banded Pull Through | Movement Demo",
        "instructions": [
            "Anchor a band low behind you; face away and pass the band between your legs, a handle in each hand.",
            "Step forward until there's tension, feet a little wider than hip-width.",
            "Hinge your hips back with a flat back, hands sliding down between your thighs.",
            "Snap your hips forward and squeeze your glutes to stand tall.",
        ],
        "form_tips": [
            "Keep your shins near vertical so the glutes do the work, not the quads.",
            "Arms stay long like straps — don't row the band with your arms.",
            "Finish standing tall with ribs down, not leaning back.",
        ],
        "common_mistakes": [
            "Squatting the weight up instead of hinging.",
            "Bending the elbows and turning it into a row.",
            "Over-arching the lower back at the top.",
        ],
    },
    {
        "slug": "single-leg-rdl",
        "name": "Single-Leg Romanian Deadlift",
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "primary_muscles": ["Hamstrings", "Glutes"],
        "secondary_muscles": ["Lower Back", "Core", "Calves"],
        "summary": "A one-legged hip hinge that builds hamstring strength, balance and symmetry at once.",
        "is_compound": True,
        "video_id": "gz9l8UA_KXs",
        "video_title": "How to Perform Single Leg Romanian Deadlifts | Bodyweight Tutorial",
        "instructions": [
            "Stand on one leg with a soft knee bend, hips square, spine long.",
            "Hinge at the hip, reaching your free leg straight back in line with your torso.",
            "Lower until you feel a strong hamstring stretch or your torso is near parallel.",
            "Drive the standing hip forward to return to tall, squeezing the glute.",
        ],
        "form_tips": [
            "Move slowly — this is a balance exercise as much as a strength one.",
            "Keep your hips level; don't let the back hip open to the ceiling.",
            "Touch a wall or chair with one hand while you build the balance.",
        ],
        "common_mistakes": [
            "Rounding the back to reach the floor.",
            "Twisting the hips open instead of staying square.",
            "Bending the standing knee like a squat.",
        ],
    },
    # ---------- Core ----------
    {
        "slug": "hollow-body-hold",
        "name": "Hollow Body Hold",
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "primary_muscles": ["Core"],
        "secondary_muscles": ["Hip Flexors", "Quads"],
        "summary": "The gymnastics core position — full-body tension with your lower back glued to the floor.",
        "is_compound": False,
        "video_id": "0yPin8hSc8o",
        "video_title": "Hollow Body Hold | Proper Form Tutorial for Core Stability",
        "instructions": [
            "Lie on your back, press your lower back flat into the floor and hold it there.",
            "Lift your shoulder blades and head slightly off the floor.",
            "Raise your straight legs a few inches, arms reaching past your head.",
            "Hold this dish shape, breathing shallowly. Bend the knees or drop the arms to regress.",
        ],
        "form_tips": [
            "Lower back pressed down is the one rule that matters.",
            "The lower your arms and legs, the harder — raise them to make it easier.",
            "Start with 10–20 second holds and build up.",
        ],
        "common_mistakes": [
            "Lower back arching up off the floor.",
            "Holding your breath and tensing the neck.",
            "Legs so low the back pops up.",
        ],
    },
    {
        "slug": "superman",
        "name": "Superman / Prone Back Raise",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Lower Back", "Mid Back"],
        "secondary_muscles": ["Glutes", "Rear Delts", "Hamstrings"],
        "summary": "Trains the whole back of the body to hold you upright — a counter to all that sitting.",
        "is_compound": False,
        "video_id": "JU0BKGxdL40",
        "video_title": "Superman - Back extension",
        "instructions": [
            "Lie face down, arms extended past your head, legs straight.",
            "Brace your glutes and gently lift your arms, chest and legs a few inches off the floor.",
            "For a back-row feel, pull your elbows down toward your ribs and squeeze your shoulder blades.",
            "Hold briefly, then lower with control.",
        ],
        "form_tips": [
            "Lift with a gentle range — this is not a max spinal extension.",
            "Keep your neck long; look at the floor, not forward.",
            "Squeeze the glutes to share the load with the lower back.",
        ],
        "common_mistakes": [
            "Cranking the neck up and back.",
            "Jerking into the top position.",
            "Over-extending the lower back instead of a small, controlled lift.",
        ],
    },
    {
        "slug": "band-pallof-press",
        "name": "Band Pallof Press",
        "equipment": "bands",
        "difficulty": "beginner",
        "primary_muscles": ["Core", "Obliques"],
        "secondary_muscles": ["Glutes", "Shoulders"],
        "summary": "Press a band straight out while it tries to twist you — pure anti-rotation core strength.",
        "is_compound": False,
        "video_id": "P16SQlmWj1o",
        "video_title": "Banded Pallof Press | Proper Form Tutorial for Core Stability",
        "instructions": [
            "Anchor a band at chest height and stand side-on to it, both hands holding the end at your sternum.",
            "Set a shoulder-width stance, brace your core, ribs down.",
            "Press the band straight out in front of you and resist its pull to rotate you.",
            "Hold for a beat, then bring it back to your chest. Finish reps, then face the other way.",
        ],
        "form_tips": [
            "Move slowly — the anti-rotation is the exercise.",
            "Step further from the anchor for more challenge.",
            "Keep your hips and shoulders square to the front the whole time.",
        ],
        "common_mistakes": [
            "Letting the band twist your torso toward the anchor.",
            "Pressing with the shoulders shrugged.",
            "Holding your breath instead of bracing and breathing.",
        ],
    },
    {
        "slug": "single-leg-calf-raise",
        "name": "Single-Leg Calf Raise",
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "primary_muscles": ["Calves"],
        "secondary_muscles": ["Feet", "Ankles"],
        "summary": "Full-range calf work on one leg — bodyweight is plenty of load here.",
        "is_compound": False,
        "video_id": "td7TMmbV8wI",
        "video_title": "Single Leg Calf Raise Exercise Tutorial - Proper Form and Technique",
        "instructions": [
            "Stand on the ball of one foot on the edge of a step, holding a wall for balance.",
            "Let your heel drop below the step for a full stretch.",
            "Press up onto your toes as high as you can and pause at the top.",
            "Lower slowly back into the stretch. Finish reps, then switch legs.",
        ],
        "form_tips": [
            "Full range: deep stretch at the bottom, high squeeze at the top.",
            "Use the wall only for balance, not to take weight.",
            "Keep the working knee straight but not locked.",
        ],
        "common_mistakes": [
            "Tiny bouncy reps with no real range.",
            "Rolling onto the outside of the foot.",
            "Rushing the lowering phase.",
        ],
    },
    # ---------- Conditioning ----------
    {
        "slug": "burpee",
        "name": "Burpee",
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "primary_muscles": ["Full Body"],
        "secondary_muscles": ["Chest", "Quads", "Core", "Shoulders"],
        "summary": "The classic full-body conditioning move — scale it down to a step-back, up to a jump.",
        "is_compound": True,
        "video_id": "wGvBfVeCNko",
        "video_title": "Burpees for Beginners (STEP BY STEP GUIDE!)",
        "instructions": [
            "From standing, squat down and place your hands on the floor.",
            "Step or jump your feet back into a plank (add a push-up here to make it harder).",
            "Step or jump your feet back up to your hands.",
            "Stand up — add a jump with the hands overhead for the full version.",
        ],
        "form_tips": [
            "Beginner: step back and step in, no jump, hands on a chair.",
            "Keep a flat back in the plank position — don't let the hips sag.",
            "Land softly through the whole foot on the jump.",
        ],
        "common_mistakes": [
            "Sagging or piking the hips in the plank.",
            "Landing stiff-legged from the jump.",
            "Going so fast the form falls apart.",
        ],
    },
    {
        "slug": "skater-hops",
        "name": "Skater Hops",
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "primary_muscles": ["Glutes", "Quads"],
        "secondary_muscles": ["Calves", "Core", "Adductors"],
        "summary": "Lateral bounds that build single-leg power, ankle and knee stability, and a bit of cardio.",
        "is_compound": True,
        "video_id": "9_jLW6VkU8A",
        "video_title": "Speed Skaters Exercise (Skater Hops): Proper Form",
        "instructions": [
            "Start balanced on one leg with a slight knee and hip bend.",
            "Push off sideways and bound onto the other foot, swinging the trailing leg behind.",
            "Land softly on a bent leg and pause until you're balanced.",
            "Bound back the other way. Slow and controlled beats fast and sloppy.",
        ],
        "form_tips": [
            "Land soft — absorb the hop through the hip, knee and ankle.",
            "Don't let the landing knee cave inward.",
            "Use your arms for balance and momentum.",
        ],
        "common_mistakes": [
            "Landing stiff-legged.",
            "Knee collapsing in on landing.",
            "Rushing so you never actually balance between hops.",
        ],
    },

    # ================================================================== #
    #  EXPANSION — push the library so there's a move for every situation
    # ================================================================== #

    # ---------- Horizontal push ----------
    {
        "slug": "diamond-push-up", "name": "Diamond Push-Up", "equipment": "bodyweight",
        "difficulty": "intermediate", "primary_muscles": ["Triceps", "Chest"],
        "secondary_muscles": ["Front Delts", "Core"],
        "summary": "Hands together under your chest — the same push-up, far more triceps.",
        "is_compound": True, "video_id": "0LZF3OY87uU",
        "video_title": "Close Grip / Diamond Push-Up | Proper Form Tutorial",
        "instructions": [
            "Set up in a plank and bring your hands together so thumbs and index fingers form a triangle.",
            "Keep your body in a straight line and your elbows tucked close to your ribs.",
            "Lower until your chest touches your hands, then press back up.",
        ],
        "form_tips": [
            "Elbows brush your sides — don't let them flare.",
            "Regress to knees or an incline if your wrists complain.",
            "Full range: chest to hands every rep.",
        ],
        "common_mistakes": [
            "Elbows flaring out to the sides.",
            "Hips sagging as the triceps tire.",
            "Only doing a half rep.",
        ],
    },
    {
        "slug": "wide-push-up", "name": "Wide Push-Up", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Chest"],
        "secondary_muscles": ["Front Delts"],
        "summary": "Hands wide to bias the chest and get a deeper stretch each rep.",
        "is_compound": True, "video_id": "maQiLUrTDWo", "video_title": "Wide Push-Up Tutorial",
        "instructions": [
            "Place your hands noticeably wider than your shoulders.",
            "Keep a straight body line and brace your core.",
            "Lower with control until your chest nears the floor, then press up.",
        ],
        "form_tips": [
            "Retract your shoulder blades as you descend.",
            "Don't go so wide that your shoulders feel pinched.",
            "Keep the hips level with the shoulders throughout.",
        ],
        "common_mistakes": [
            "Hips sagging or piking.",
            "Elbows flaring to a hard 90 degrees.",
            "Going so wide it stresses the shoulder joint.",
        ],
    },
    {
        "slug": "spiderman-push-up", "name": "Spiderman Push-Up", "equipment": "bodyweight",
        "difficulty": "intermediate", "primary_muscles": ["Chest"],
        "secondary_muscles": ["Core", "Obliques", "Triceps", "Hip Flexors"],
        "summary": "A push-up with a knee-to-elbow drive — chest, core and hips in one move.",
        "is_compound": True, "video_id": "HnrnLfymru0",
        "video_title": "Spider-Man Push Up Tutorial",
        "instructions": [
            "Start in a strong push-up position, body in a straight line.",
            "As you lower, drive one knee up toward the same-side elbow.",
            "As you press back up, return the foot to the start. Alternate sides.",
        ],
        "form_tips": [
            "Keep your hips level — don't let them rotate toward the floor.",
            "The knee should arrive by the bottom of the push-up.",
            "Move slowly; the coordination is the challenge.",
        ],
        "common_mistakes": [
            "Hips twisting as the knee comes up.",
            "Rushing so the push-up range gets short.",
            "Letting the back arch.",
        ],
    },
    {
        "slug": "clap-push-up", "name": "Clap Push-Up", "equipment": "bodyweight",
        "difficulty": "advanced", "primary_muscles": ["Chest"],
        "secondary_muscles": ["Front Delts", "Triceps"],
        "summary": "An explosive push-up where your hands leave the floor — builds pressing power.",
        "is_compound": True, "video_id": "MH4gcTKQiEc",
        "video_title": "How to do a Plyometric Push-Up | NASM",
        "instructions": [
            "Lower into a push-up with your body rigid, arms forming an arrow, not a T.",
            "Press up as explosively as you can so your hands leave the floor.",
            "Clap, then land on soft elbows and immediately absorb into the next rep.",
        ],
        "form_tips": [
            "Only attempt this once you can do 20+ clean push-ups.",
            "Land with bent elbows to absorb force.",
            "Keep the body a rigid plank the whole time.",
        ],
        "common_mistakes": [
            "Piking the hips to get airtime.",
            "Landing on locked-out elbows.",
            "Losing the straight body line mid-air.",
        ],
    },
    {
        "slug": "band-floor-press", "name": "Band Floor Press", "equipment": "bands",
        "difficulty": "beginner", "primary_muscles": ["Chest"],
        "secondary_muscles": ["Triceps", "Front Delts"],
        "summary": "A lying press with a band around your back — pressing strength with no bench, no floor push-up.",
        "is_compound": True, "video_id": "h1uU13KkCXw",
        "video_title": "How To Do: Resistance Band Floor Press",
        "instructions": [
            "Lie on your back, knees bent, and pass a band under your upper back, an end in each hand.",
            "Start with elbows on the floor at about 45 degrees, hands above your chest.",
            "Press the band straight up until your arms are almost straight, then lower under control.",
        ],
        "form_tips": [
            "Keep your lower back flat — don't arch to press harder.",
            "Control the lowering phase; that's where the muscle works.",
            "Choke up on the band or use a heavier band for more resistance.",
        ],
        "common_mistakes": [
            "Arching the back off the floor.",
            "Flaring the elbows to a hard 90 degrees.",
            "Letting the band yank the arms down.",
        ],
    },
    {
        "slug": "band-pullover", "name": "Band Pullover", "equipment": "bands",
        "difficulty": "beginner", "primary_muscles": ["Lats"],
        "secondary_muscles": ["Chest", "Triceps", "Core"],
        "summary": "A lying lat move that also opens up the shoulders and ribcage.",
        "is_compound": False, "video_id": "I3b8FyV9vZQ",
        "video_title": "Pullover with a Resistance Band",
        "instructions": [
            "Anchor a band low behind your head (or hold it taut) and lie on your back, knees bent.",
            "Hold the band with straight arms reaching back overhead.",
            "Keeping the arms nearly straight, pull the band in an arc toward your thighs.",
            "Return slowly to the overhead stretch.",
        ],
        "form_tips": [
            "Lock a soft elbow bend and keep it fixed.",
            "Keep your ribs down so the back doesn't arch.",
            "Feel the lats, not the shoulders, doing the work.",
        ],
        "common_mistakes": [
            "Bending and straightening the elbows.",
            "Flaring the ribs and arching the lower back.",
            "Going so far overhead the shoulders pinch.",
        ],
    },

    # ---------- Horizontal pull ----------
    {
        "slug": "band-seated-row", "name": "Band Seated Row", "equipment": "bands",
        "difficulty": "beginner", "primary_muscles": ["Mid Back", "Lats"],
        "secondary_muscles": ["Biceps", "Rear Delts"],
        "summary": "Sit down, loop the band around your feet, and row — a back builder with zero setup.",
        "is_compound": True, "video_id": "TBNt2DBvkl4",
        "video_title": "How To: Resistance Band Seated Row",
        "instructions": [
            "Sit tall with legs extended, a band looped around the arches of your feet, an end in each hand.",
            "Start with arms straight and a slight forward reach of the shoulder blades.",
            "Drive your elbows back close to your body, squeezing your shoulder blades together.",
            "Return slowly to a full stretch.",
        ],
        "form_tips": [
            "Keep your chest up and back flat — no rounding.",
            "Pull with the elbows, not the hands.",
            "Sit further back or double the band for more tension.",
        ],
        "common_mistakes": [
            "Rounding the shoulders forward at the start.",
            "Leaning way back to move the band.",
            "Shrugging instead of rowing.",
        ],
    },
    {
        "slug": "band-reverse-fly", "name": "Band Reverse Fly", "equipment": "bands",
        "difficulty": "beginner", "primary_muscles": ["Rear Delts", "Upper Back"],
        "secondary_muscles": ["Traps"],
        "summary": "Isolates the rear delts — a small move with a big effect on posture.",
        "is_compound": False, "video_id": "cyihFNmsq-A",
        "video_title": "How To: Resistance Band Reverse Fly",
        "instructions": [
            "Hold a band in front of you at shoulder height, an end in each hand, palms down.",
            "Set a slight bend in your elbows and keep it fixed.",
            "Pull your hands apart and back until your arms form a wide T, squeezing the shoulder blades.",
            "Return slowly with control.",
        ],
        "form_tips": [
            "Keep your shoulders down, away from your ears.",
            "Lead with the pinky side of the hand.",
            "Use a light band — form beats tension here.",
        ],
        "common_mistakes": [
            "Bending the elbows to cheat the range.",
            "Shrugging the traps up.",
            "Arching the lower back to lean into it.",
        ],
    },

    # ---------- Vertical push ----------
    {
        "slug": "band-arnold-press", "name": "Band Arnold Press", "equipment": "bands",
        "difficulty": "intermediate", "primary_muscles": ["Shoulders"],
        "secondary_muscles": ["Triceps", "Upper Chest"],
        "summary": "An overhead press with a rotation — hits all three heads of the shoulder.",
        "is_compound": True, "video_id": "SzXjcbblehs", "video_title": "Band Arnold Press",
        "instructions": [
            "Stand on the band, start with hands in front of your shoulders, palms facing you, elbows down.",
            "As you press up, rotate your palms to face forward.",
            "Finish with arms straight overhead, then reverse the rotation on the way down.",
        ],
        "form_tips": [
            "Keep your core braced and ribs down — don't lean back.",
            "Rotate smoothly through the middle of the press.",
            "Keep the wrists stacked over the elbows at lockout.",
        ],
        "common_mistakes": [
            "Leaning back to press the band up.",
            "Rushing the rotation.",
            "Shrugging the shoulders at the top.",
        ],
    },
    {
        "slug": "wall-walk", "name": "Wall Walk", "equipment": "bodyweight",
        "difficulty": "advanced", "primary_muscles": ["Shoulders", "Core"],
        "secondary_muscles": ["Triceps", "Upper Back"],
        "summary": "Walk your feet up a wall into a handstand hold — the bridge to overhead bodyweight strength.",
        "is_compound": True, "video_id": "2-3wv5kLNnw",
        "video_title": "The Complete Handstand Guide | From Absolute Beginner",
        "instructions": [
            "Start in a push-up position with your feet against the base of a wall.",
            "Walk your hands toward the wall as your feet climb up it.",
            "Go as vertical as you can control, hold briefly, then walk back down.",
        ],
        "form_tips": [
            "Keep your arms locked straight the whole time.",
            "Only go as high as you can come back down under control.",
            "Squeeze your ribs and glutes so you don't over-arch.",
        ],
        "common_mistakes": [
            "Bending the elbows and collapsing.",
            "Over-arching the lower back near vertical.",
            "Rushing up with no plan to get down.",
        ],
    },

    # ---------- Squat / lunge ----------
    {
        "slug": "prisoner-squat", "name": "Prisoner Squat", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Core", "Upper Back"],
        "summary": "A bodyweight squat with hands behind your head — forces an upright, strong torso.",
        "is_compound": True, "video_id": "UYbsgiiZgao",
        "video_title": "How to do a Prisoner Squat | Proper Form & Technique | NASM",
        "instructions": [
            "Stand with feet shoulder-width, toes slightly out, fingers laced behind your head.",
            "Pull your elbows back to open your chest.",
            "Sit your hips down and back to at least parallel, keeping your torso tall.",
            "Drive through your whole foot to stand.",
        ],
        "form_tips": [
            "Keep your elbows wide and chest proud the whole rep.",
            "Push your knees out in line with your toes.",
            "Keep your weight through the mid-foot.",
        ],
        "common_mistakes": [
            "Elbows collapsing forward.",
            "Chest falling toward the floor.",
            "Heels lifting.",
        ],
    },
    {
        "slug": "sumo-squat", "name": "Sumo Squat", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Glutes", "Adductors"],
        "secondary_muscles": ["Quads", "Hamstrings"],
        "summary": "A wide-stance squat that brings the inner thighs and glutes into the party.",
        "is_compound": True, "video_id": "E_VDwURp8as",
        "video_title": "The Squat You NEED To Be Doing! (Sumo Squat)",
        "instructions": [
            "Stand with your feet well wider than shoulder-width, toes turned out about 30 degrees.",
            "Keep your chest up and core braced.",
            "Sit straight down, knees tracking over your toes, until your thighs are parallel.",
            "Drive up through your heels and squeeze your glutes at the top.",
        ],
        "form_tips": [
            "Point your knees the same direction as your toes.",
            "Keep your torso as upright as you can.",
            "Push the floor apart with your feet as you stand.",
        ],
        "common_mistakes": [
            "Knees caving inward.",
            "Leaning the chest forward.",
            "Feet too narrow to feel the inner thighs.",
        ],
    },
    {
        "slug": "jump-squat", "name": "Jump Squat", "equipment": "bodyweight",
        "difficulty": "intermediate", "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Calves", "Hamstrings", "Core"],
        "summary": "An explosive squat that trains power and gets your heart rate up fast.",
        "is_compound": True, "video_id": "tZSYZdtbONc",
        "video_title": "How to do a Squat Jump | Proper Form & Technique | NASM",
        "instructions": [
            "Start in a shoulder-width stance and drop into a quarter-to-half squat.",
            "Explode up, extending hips, knees and ankles, and swing your arms for momentum.",
            "Land softly through the whole foot and immediately absorb into the next squat.",
        ],
        "form_tips": [
            "Land quiet — soft knees and hips absorb the force.",
            "Keep your chest up on both the jump and the landing.",
            "Warm up your legs first; this is high-impact.",
        ],
        "common_mistakes": [
            "Landing stiff-legged.",
            "Knees caving in on the landing.",
            "Rounding forward as you jump.",
        ],
    },
    {
        "slug": "shrimp-squat", "name": "Shrimp Squat", "equipment": "bodyweight",
        "difficulty": "advanced", "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Hamstrings", "Core", "Calves"],
        "summary": "A single-leg squat where you hold your back foot — a pistol alternative with a different balance demand.",
        "is_compound": True, "video_id": "xfl7SDj0Gzs",
        "video_title": "Shrimp Squat | Tutorial & Progressions",
        "instructions": [
            "Stand on one leg, bend the other knee and hold that foot behind you with the same-side hand.",
            "Sit down slowly, keeping the standing heel flat and chest tall.",
            "Lower until your back knee lightly touches the floor, then drive back up.",
        ],
        "form_tips": [
            "Reach your free arm forward as a counterweight.",
            "Regress by lowering to a stack of books or a low box.",
            "Keep the working knee tracking over the toes.",
        ],
        "common_mistakes": [
            "Heel lifting off the floor.",
            "Crashing the back knee down.",
            "Knee caving inward under load.",
        ],
    },
    {
        "slug": "bear-crawl", "name": "Bear Crawl", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Core", "Shoulders"],
        "secondary_muscles": ["Quads", "Triceps", "Upper Back"],
        "summary": "Crawl on hands and toes with knees hovering — a full-body anti-rotation drill that doubles as conditioning.",
        "is_compound": True, "video_id": "_li8Mi8grTU",
        "video_title": "Bear Crawl Exercise Tutorial - Proper Form and Technique",
        "instructions": [
            "Set up on hands and toes, knees an inch off the floor and under your hips, back flat.",
            "Move the opposite hand and foot together a small step forward.",
            "Keep your hips low and level — no swaying side to side. Crawl forward, then back.",
        ],
        "form_tips": [
            "Imagine balancing a cup of water on your lower back.",
            "Small steps keep it controlled.",
            "Wrists under shoulders, weight spread across the whole hand.",
        ],
        "common_mistakes": [
            "Hips rocking side to side.",
            "Butt piking up toward the ceiling.",
            "Big lunging steps that break the control.",
        ],
    },
    {
        "slug": "forward-lunge", "name": "Forward Lunge", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Hamstrings", "Core"],
        "summary": "Step forward into the lunge — a little more demanding to control than the reverse version.",
        "is_compound": True, "video_id": "B7VQJiVv3xw",
        "video_title": "How To Do A Forward Lunge | Exercise Demonstration",
        "instructions": [
            "Stand tall, hands on your hips, core braced.",
            "Step one foot forward and bend both knees toward 90 degrees.",
            "Keep your front knee over your ankle and your torso upright.",
            "Push back through the front foot to return to standing, then alternate.",
        ],
        "form_tips": [
            "Take a long enough step that the front shin stays near vertical.",
            "Lower with control — don't fall into the bottom.",
            "Look ahead for balance.",
        ],
        "common_mistakes": [
            "Front knee jamming far past the toes.",
            "Torso pitching forward.",
            "Front knee caving inward.",
        ],
    },
    {
        "slug": "lateral-lunge", "name": "Lateral Lunge", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Glutes", "Quads", "Adductors"],
        "secondary_muscles": ["Hamstrings", "Core"],
        "summary": "Step out to the side and sit into one hip — trains a direction most programs ignore.",
        "is_compound": True, "video_id": "gwWv7aPcD88",
        "video_title": "How To Series | Lateral Lunge",
        "instructions": [
            "Stand tall, then take a wide step directly out to one side.",
            "Sit back and down into that hip, bending the knee, keeping the other leg straight.",
            "Both feet point forward; keep your chest up.",
            "Push back to standing and repeat, or alternate sides.",
        ],
        "form_tips": [
            "Push your hips back as you bend the working knee.",
            "Keep the straight leg's foot flat on the floor.",
            "Only go as deep as you can keep a flat back.",
        ],
        "common_mistakes": [
            "Working knee travelling past the toes.",
            "Rounding the back to reach lower.",
            "Feet turning out instead of pointing forward.",
        ],
    },
    {
        "slug": "curtsy-lunge", "name": "Curtsy Lunge", "equipment": "bodyweight",
        "difficulty": "intermediate", "primary_muscles": ["Glutes", "Quads"],
        "secondary_muscles": ["Adductors", "Hamstrings", "Core"],
        "summary": "Step one leg diagonally behind the other — great for the side-glutes and hip control.",
        "is_compound": True, "video_id": "yv0gSJLFhJE",
        "video_title": "Curtsy Lunge. Proper form and technique tutorial.",
        "instructions": [
            "Stand tall, then step one foot back and across behind the other into a 'curtsy'.",
            "Bend both knees, keeping your front knee tracking over your shoes.",
            "Keep your chest lifted and hips facing forward.",
            "Push through the front foot to return, then alternate sides.",
        ],
        "form_tips": [
            "Keep your hips square — resist the twist.",
            "Most of the weight stays on the front leg.",
            "Go slow; the crossover challenges balance.",
        ],
        "common_mistakes": [
            "Hips rotating open toward the back leg.",
            "Front knee caving inward.",
            "Leaning the torso forward.",
        ],
    },
    {
        "slug": "jumping-lunge", "name": "Jumping Lunge", "equipment": "bodyweight",
        "difficulty": "advanced", "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Hamstrings", "Calves", "Core"],
        "summary": "Explode out of a lunge and switch legs mid-air — power and conditioning in one.",
        "is_compound": True, "video_id": "_5kDxC0flg0",
        "video_title": "How to do a Lunge Jump | Proper Form & Technique | NASM",
        "instructions": [
            "Start in a split stance, both knees bent toward 90 degrees.",
            "Drive up explosively and switch your legs in the air.",
            "Land softly back in a lunge on the other side and immediately absorb into the next rep.",
        ],
        "form_tips": [
            "Land quiet with the front shin near vertical.",
            "Keep your torso upright the whole time.",
            "Master reverse lunges and split squats before adding the jump.",
        ],
        "common_mistakes": [
            "Front knee slamming forward on the landing.",
            "Landing stiff-legged.",
            "Losing the upright torso mid-air.",
        ],
    },
    {
        "slug": "step-up", "name": "Step-Up", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Hamstrings", "Calves", "Core"],
        "summary": "Step onto a sturdy chair or box one leg at a time — simple, scalable single-leg strength.",
        "is_compound": True, "video_id": "vOiHvzj5XhA",
        "video_title": "Step Up Tutorial - Proper Form and Technique",
        "instructions": [
            "Stand facing a knee-height sturdy box, bench or bottom stair.",
            "Place one whole foot on the surface and drive through that heel to stand up on it.",
            "Step back down softly with control. Finish reps, then switch legs.",
        ],
        "form_tips": [
            "Drive through the heel of the top foot to load the glute.",
            "Minimise the push-off from the bottom foot.",
            "Lower a higher step to regress, raise it to progress.",
        ],
        "common_mistakes": [
            "Pushing hard off the trailing foot.",
            "Letting the top knee cave inward.",
            "Bouncing off the bottom.",
        ],
    },

    # ---------- Hinge / glutes ----------
    {
        "slug": "single-leg-glute-bridge", "name": "Single-Leg Glute Bridge", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Glutes"],
        "secondary_muscles": ["Hamstrings", "Core"],
        "summary": "A glute bridge on one leg — twice the load and a check on side-to-side balance.",
        "is_compound": False, "video_id": "VUl8R0kn6v4",
        "video_title": "Single Leg Glute Bridge Tutorial - Proper Form and Technique",
        "instructions": [
            "Lie on your back, one knee bent with the foot flat, the other leg extended.",
            "Press your ribs down and brace your core.",
            "Drive through the planted heel to lift your hips until your body is straight from knee to shoulder.",
            "Squeeze the glute at the top, then lower with control. Finish reps, then switch.",
        ],
        "form_tips": [
            "Keep your hips level — don't let one side drop.",
            "Push the movement with your glute, not your lower back.",
            "Pause and squeeze for a beat each rep.",
        ],
        "common_mistakes": [
            "Hips tilting or twisting.",
            "Arching the back to finish the lift.",
            "Pushing through the toes instead of the heel.",
        ],
    },
    {
        "slug": "frog-pump", "name": "Frog Pump", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Glutes"],
        "secondary_muscles": ["Hamstrings"],
        "summary": "A bridge with soles of the feet together — one of the best pure glute-activation drills.",
        "is_compound": False, "video_id": "L0nEfiTMTBI",
        "video_title": "How To Do A Frog Pump Glute Bridge",
        "instructions": [
            "Lie on your back, press the soles of your feet together and let your knees fall open.",
            "Pull your heels in toward your body.",
            "Press through the outer edges of your feet and squeeze your glutes to lift your hips.",
            "Hold the squeeze for a beat, then lower.",
        ],
        "form_tips": [
            "Keep the range small — it's all about the glute squeeze.",
            "Ribs stay down; don't arch the back.",
            "Do these as a warm-up before squats and hinges.",
        ],
        "common_mistakes": [
            "Arching the lower back instead of squeezing the glutes.",
            "Letting the knees drift up instead of open.",
            "Rushing the reps.",
        ],
    },
    {
        "slug": "band-hip-thrust", "name": "Band Hip Thrust", "equipment": "bands",
        "difficulty": "beginner", "primary_muscles": ["Glutes"],
        "secondary_muscles": ["Hamstrings", "Core"],
        "summary": "A shoulders-elevated hip thrust with a loop band over the hips — the most direct glute builder at home.",
        "is_compound": True, "video_id": "pF17m_CXfL0",
        "video_title": "Hip Thrust Tutorial – Proper Form and Technique",
        "instructions": [
            "Sit with your upper back against a couch or bench, a loop band over your hips and pinned under your hands.",
            "Plant your feet flat, shins vertical at the top.",
            "Drive through your heels and push your hips up until your body is flat from knees to shoulders.",
            "Squeeze your glutes hard at the top, then lower with control.",
        ],
        "form_tips": [
            "Tuck your chin and keep your ribs down — squeeze, don't arch.",
            "Pause at the top of every rep.",
            "Push a mini band around the knees too, to fight the knees caving in.",
        ],
        "common_mistakes": [
            "Over-arching the lower back at the top.",
            "Feet too far forward so the hamstrings take over.",
            "Only pushing halfway up.",
        ],
    },
    {
        "slug": "band-donkey-kick", "name": "Band Donkey Kick", "equipment": "bands",
        "difficulty": "beginner", "primary_muscles": ["Glutes"],
        "secondary_muscles": ["Hamstrings", "Core"],
        "summary": "A kneeling glute isolation with a band around the knees — pure burn, joint-friendly.",
        "is_compound": False, "video_id": "A0iUAb4xUck",
        "video_title": "How to Do Donkey Kicks with Resistance Bands",
        "instructions": [
            "Get on all fours with a loop band around your legs just above the knees, back flat.",
            "Keeping one knee bent at 90 degrees, press that foot toward the ceiling.",
            "Stop when your thigh is in line with your torso — no higher.",
            "Lower slowly against the band. Finish reps, then switch.",
        ],
        "form_tips": [
            "Keep your core tight and back neutral — don't arch to lift higher.",
            "Squeeze the glute at the top.",
            "Control the way down; don't let the band snap the leg back.",
        ],
        "common_mistakes": [
            "Kicking so high the lower back arches.",
            "Rotating the hips open.",
            "Using momentum instead of the glute.",
        ],
    },
    {
        "slug": "b-stance-rdl", "name": "B-Stance Romanian Deadlift", "equipment": "bodyweight",
        "difficulty": "intermediate", "primary_muscles": ["Hamstrings", "Glutes"],
        "secondary_muscles": ["Lower Back", "Core"],
        "summary": "A staggered-stance hinge — most of the load on the front leg, but far easier to balance than a full single-leg RDL.",
        "is_compound": True, "video_id": "6ijhguezxC0", "video_title": "B Stance RDL Tutorial",
        "instructions": [
            "Stand with feet hip-width, then slide one foot back so its toe lines up with the other heel.",
            "Put about 90% of your weight on the front leg; the back foot is a kickstand for balance.",
            "Push your hips back and hinge forward with a flat back.",
            "Feel the front hamstring stretch, then drive the hips forward to stand.",
        ],
        "form_tips": [
            "The back leg only helps with balance — don't push through it.",
            "Keep a fixed soft bend in the front knee.",
            "Keep the movement in your hips, spine long.",
        ],
        "common_mistakes": [
            "Splitting the weight evenly between both legs.",
            "Rounding the lower back.",
            "Turning it into a squat by bending the knees.",
        ],
    },

    # ---------- Core: anti-extension / flexion ----------
    {
        "slug": "reverse-crunch", "name": "Reverse Crunch", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Core"],
        "secondary_muscles": ["Hip Flexors"],
        "summary": "Curl your hips toward your ribs — a lower-ab move that spares the neck.",
        "is_compound": False, "video_id": "ue6j6k0Vgbc",
        "video_title": "Reverse Crunch | Core & Ab Strength Exercise Tutorial",
        "instructions": [
            "Lie on your back, hands by your sides, knees bent so thighs are vertical.",
            "Press your lower back into the floor.",
            "Use your abs to curl your hips and knees up toward your chest.",
            "Lower slowly without letting the back arch.",
        ],
        "form_tips": [
            "Small, controlled range — no swinging the legs.",
            "Keep the lower back pinned down the whole time.",
            "Exhale as you curl up.",
        ],
        "common_mistakes": [
            "Using momentum to throw the legs.",
            "Letting the lower back arch off the floor.",
            "Pulling with the hip flexors instead of curling with the abs.",
        ],
    },
    {
        "slug": "lying-leg-raise", "name": "Lying Leg Raise", "equipment": "bodyweight",
        "difficulty": "intermediate", "primary_muscles": ["Core"],
        "secondary_muscles": ["Hip Flexors"],
        "summary": "Raise straight legs to 90 degrees and lower with control — a lower-ab and core-control classic.",
        "is_compound": False, "video_id": "zJukDl0Lv4U",
        "video_title": "Leg Raises | Step by Step Tutorial | Proper Form and Technique",
        "instructions": [
            "Lie on your back, hands tucked under your glutes, legs straight.",
            "Press your lower back into the floor and keep it there.",
            "Raise your legs together until they're vertical, then lower slowly.",
            "Stop lowering before your back lifts off the floor.",
        ],
        "form_tips": [
            "Bend the knees to regress; keep them straighter to progress.",
            "Roll your pelvis under slightly at the top.",
            "Lower only as far as your back stays flat.",
        ],
        "common_mistakes": [
            "Lower back arching as the legs drop.",
            "Using momentum to swing the legs up.",
            "Yanking with the hip flexors.",
        ],
    },
    {
        "slug": "v-up", "name": "V-Up", "equipment": "bodyweight",
        "difficulty": "advanced", "primary_muscles": ["Core"],
        "secondary_muscles": ["Hip Flexors", "Quads"],
        "summary": "Lift your torso and straight legs to meet in a V — a demanding full-range ab move.",
        "is_compound": False, "video_id": "DfVArP2V6kg",
        "video_title": "V-Ups Tutorial For Beginners (4 Variations Covered)",
        "instructions": [
            "Lie flat, arms extended past your head, legs straight, body long.",
            "Exhale and lift your torso and legs at the same time, reaching your hands toward your feet.",
            "Balance briefly on your glutes, then lower everything with control.",
        ],
        "form_tips": [
            "Bend the knees or do tuck-ups to regress.",
            "Keep the movement smooth — no jack-knifing with momentum.",
            "Keep your lower back from over-rounding at the top.",
        ],
        "common_mistakes": [
            "Throwing the arms for momentum.",
            "Crashing back down instead of lowering.",
            "Bending the legs when you meant to keep them straight.",
        ],
    },
    {
        "slug": "hollow-rock", "name": "Hollow Rock", "equipment": "bodyweight",
        "difficulty": "advanced", "primary_muscles": ["Core"],
        "secondary_muscles": ["Hip Flexors"],
        "summary": "Hold the hollow shape and rock — adds a dynamic challenge to the gymnastics core position.",
        "is_compound": False, "video_id": "gas_AFCRPxY", "video_title": "How To: Hollow Rock",
        "instructions": [
            "Get into a hollow hold: lower back pressed down, shoulders and legs a few inches off the floor.",
            "Keeping the shape rigid, rock forward and back from your upper back to your hips.",
            "Keep the rock small; hands and feet never touch the floor.",
        ],
        "form_tips": [
            "The lower back stays glued down the whole time.",
            "Rock from the shape, not by breaking at the hips.",
            "Master the static hollow hold first.",
        ],
        "common_mistakes": [
            "Lower back popping off the floor.",
            "Bending at the hips to create the rock.",
            "Big, uncontrolled rocking.",
        ],
    },
    {
        "slug": "plank-shoulder-taps", "name": "Plank Shoulder Taps", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Core", "Obliques"],
        "secondary_muscles": ["Shoulders"],
        "summary": "A plank where you tap each shoulder — the anti-rotation demand goes way up.",
        "is_compound": False, "video_id": "eT93C-xUZI8",
        "video_title": "How to Do Plank Shoulder Taps | Core Stability Exercise",
        "instructions": [
            "Set up in a tall plank, hands under shoulders, feet about shoulder-width for stability.",
            "Shift your weight slightly and lift one hand to tap the opposite shoulder.",
            "Return it and repeat on the other side, keeping your hips still.",
        ],
        "form_tips": [
            "Widen your feet to make it easier, narrow them to make it harder.",
            "Squeeze your glutes so the hips don't rock.",
            "Slow taps — the stillness is the exercise.",
        ],
        "common_mistakes": [
            "Hips swaying side to side.",
            "Rushing the taps.",
            "Piking the hips up.",
        ],
    },

    # ---------- Core: rotation / anti-rotation ----------
    {
        "slug": "bicycle-crunch", "name": "Bicycle Crunch", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Core", "Obliques"],
        "secondary_muscles": ["Hip Flexors"],
        "summary": "Alternating elbow-to-knee with a pedalling motion — hits the obliques hard.",
        "is_compound": False, "video_id": "kDPxFoCmb-w", "video_title": "Bicycle Crunch Tutorial",
        "instructions": [
            "Lie on your back, hands lightly behind your head, legs lifted, knees bent 90 degrees.",
            "Bring one knee toward your chest as you rotate the opposite elbow toward it.",
            "Switch sides in a smooth pedalling motion, extending the other leg out.",
        ],
        "form_tips": [
            "Rotate from the ribs, not by yanking the neck.",
            "Keep the movement controlled — quality over speed.",
            "The extended leg stays off the floor.",
        ],
        "common_mistakes": [
            "Pulling on the head and straining the neck.",
            "Racing through reps with no rotation.",
            "Letting the lower back arch.",
        ],
    },
    {
        "slug": "russian-twist", "name": "Russian Twist", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Obliques", "Core"],
        "secondary_muscles": ["Hip Flexors"],
        "summary": "Sit back, lift your feet, and rotate side to side — a simple rotational core builder.",
        "is_compound": False, "video_id": "fPxO-FA8acM",
        "video_title": "Russian Twist | Proper Form Tutorial for Rotational Core Strength",
        "instructions": [
            "Sit with knees bent, lean back to about 45 degrees, keeping your back flat.",
            "Lift your feet off the floor (or keep them down to regress).",
            "Rotate your torso to touch the floor beside one hip, then the other.",
        ],
        "form_tips": [
            "Rotate through the trunk, not just the arms.",
            "Keep your chest up and back long — no rounding.",
            "Slow and controlled beats fast and floppy.",
        ],
        "common_mistakes": [
            "Rounding the lower back.",
            "Only swinging the arms.",
            "Going so fast the range disappears.",
        ],
    },

    # ---------- Core: anti-lateral ----------
    {
        "slug": "copenhagen-plank", "name": "Copenhagen Plank", "equipment": "bodyweight",
        "difficulty": "advanced", "primary_muscles": ["Adductors", "Obliques"],
        "secondary_muscles": ["Core", "Glutes"],
        "summary": "A side plank with the top leg on a bench — brutal, protective inner-thigh strength.",
        "is_compound": False, "video_id": "48wlc5zn02A",
        "video_title": "Copenhagen Plank | Proper Form Tutorial for Adductor Strength",
        "instructions": [
            "Set up in a side plank with your top shin or ankle resting on a chair or bench.",
            "Let the bottom leg hang under the bench.",
            "Lift your hips so your body is one straight line, squeezing the top inner thigh.",
            "Hold for time, then switch sides.",
        ],
        "form_tips": [
            "Regress by resting the top knee (bent) on the bench instead of the ankle.",
            "Keep your body in one line — no sagging or piking.",
            "Start with short holds; this move gets sore fast.",
        ],
        "common_mistakes": [
            "Hips sagging toward the floor.",
            "Going straight to the long-lever (ankle) version.",
            "Holding too long, too soon, and tweaking the groin.",
        ],
    },

    # ---------- Calves ----------
    {
        "slug": "standing-calf-raise", "name": "Standing Calf Raise", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Calves"],
        "secondary_muscles": ["Feet", "Ankles"],
        "summary": "The simplest calf builder — do them off a step for full range.",
        "is_compound": False, "video_id": "KRJIKsY02nE",
        "video_title": "Standing Calf Raise Tutorial for Beginners",
        "instructions": [
            "Stand with the balls of your feet on the edge of a step, heels hanging off.",
            "Let your heels drop below the step for a stretch.",
            "Press up onto your toes as high as you can and pause at the top.",
            "Lower slowly back into the stretch.",
        ],
        "form_tips": [
            "Full range: deep stretch, high squeeze.",
            "Keep your knees straight but not locked.",
            "Progress to one leg at a time when this feels easy.",
        ],
        "common_mistakes": [
            "Tiny bouncy reps with no real range.",
            "Rushing the lowering phase.",
            "Rolling onto the outer edge of the foot.",
        ],
    },

    # ---------- Conditioning ----------
    {
        "slug": "jumping-jacks", "name": "Jumping Jacks", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Full Body"],
        "secondary_muscles": ["Calves", "Shoulders", "Core"],
        "summary": "The warm-up everyone knows — gets blood moving and joints ready in 30 seconds.",
        "is_compound": True, "video_id": "uLVt6u15L98",
        "video_title": "How to do a Jumping Jack | Proper Form & Technique | NASM",
        "instructions": [
            "Start standing tall, feet together, arms at your sides.",
            "Jump your feet out wide as you sweep your arms overhead.",
            "Jump back to the start. Keep a steady, springy rhythm.",
        ],
        "form_tips": [
            "Land softly through the balls of your feet.",
            "Keep a slight bend in the knees.",
            "Step-jacks (no jump) are a fine low-impact option.",
        ],
        "common_mistakes": [
            "Landing hard and flat-footed.",
            "Locking the knees.",
            "Half-raising the arms.",
        ],
    },
    {
        "slug": "high-knees", "name": "High Knees", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Hip Flexors", "Core"],
        "secondary_muscles": ["Quads", "Calves"],
        "summary": "Run in place driving your knees high — quick cardio and hip-flexor work.",
        "is_compound": True, "video_id": "OpN2Y712k6Y",
        "video_title": "High Knees - Step-by-Step Guide",
        "instructions": [
            "Stand tall with feet hip-width apart.",
            "Drive one knee up toward hip height, then quickly switch, staying on the balls of your feet.",
            "Pump your arms in time with your legs.",
        ],
        "form_tips": [
            "Stay tall — don't lean back as you lift the knees.",
            "Land softly and quietly.",
            "March the knees up slowly to regress.",
        ],
        "common_mistakes": [
            "Leaning back to get the knees up.",
            "Heavy, flat-footed landings.",
            "Barely lifting the knees.",
        ],
    },
    {
        "slug": "tuck-jump", "name": "Tuck Jump", "equipment": "bodyweight",
        "difficulty": "advanced", "primary_muscles": ["Quads", "Calves"],
        "secondary_muscles": ["Glutes", "Core"],
        "summary": "Jump and pull your knees to your chest — a high-intensity power and conditioning move.",
        "is_compound": True, "video_id": "FY15qEqRcMc",
        "video_title": "Tuck Jumps – Power & Explosiveness",
        "instructions": [
            "Stand with feet hip-width, dip into a quarter squat.",
            "Explode straight up and pull your knees toward your chest.",
            "Land softly in a quarter squat and immediately reset.",
        ],
        "form_tips": [
            "Land quiet with soft knees and hips.",
            "Keep your chest up; don't fold forward to reach the knees.",
            "Warm up thoroughly — this is high-impact.",
        ],
        "common_mistakes": [
            "Landing stiff-legged.",
            "Piking the torso down to meet the knees.",
            "Doing them fatigued, which wrecks the landing mechanics.",
        ],
    },
    {
        "slug": "inchworm-walkout", "name": "Inchworm Walkout", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Core", "Shoulders"],
        "secondary_muscles": ["Hamstrings", "Chest"],
        "summary": "Fold, walk your hands out to a plank, walk them back — a full-body warm-up and core drill.",
        "is_compound": True, "video_id": "jmkHd1orkBw",
        "video_title": "Inchworm Walk Out",
        "instructions": [
            "Stand tall, hinge forward and place your hands on the floor, legs as straight as comfortable.",
            "Walk your hands forward until you're in a solid plank.",
            "Optionally add a push-up, then walk your hands back to your feet and stand up.",
        ],
        "form_tips": [
            "Actually put weight on your hands — no 'air walking'.",
            "Keep your hips level in the plank, no sag.",
            "Pause a beat in the fold and in the plank.",
        ],
        "common_mistakes": [
            "Rushing and skipping the walk-back.",
            "Hips sagging in the plank.",
            "Bouncing up instead of a controlled stand.",
        ],
    },
    {
        "slug": "band-lateral-raise", "name": "Band Lateral Raise", "equipment": "bands",
        "difficulty": "beginner", "primary_muscles": ["Side Delts"],
        "secondary_muscles": ["Traps"],
        "summary": "Raise the band out to the sides for wider shoulders — constant tension, joint-friendly.",
        "is_compound": False, "video_id": "gfEyrmxbCbw",
        "video_title": "How To: Resistance Band Lateral Raise",
        "instructions": [
            "Stand on the middle of the band, an end in each hand at your sides.",
            "Keep a slight bend in your elbows.",
            "Raise your hands out to the sides, leading with the elbows, to about shoulder height.",
            "Lower slowly with control.",
        ],
        "form_tips": [
            "Keep your shoulders down, away from your ears.",
            "Thumbs level with or slightly above the pinkies.",
            "Stop at shoulder height — no higher.",
        ],
        "common_mistakes": [
            "Shrugging so the traps take over.",
            "Using body swing to start the rep.",
            "Raising the arms above shoulder height.",
        ],
    },
    {
        "slug": "band-upright-row", "name": "Band Upright Row", "equipment": "bands",
        "difficulty": "beginner", "primary_muscles": ["Side Delts", "Traps"],
        "secondary_muscles": ["Biceps", "Upper Back"],
        "summary": "Pull the band up the front of your body — hits the side delts and upper traps.",
        "is_compound": False, "video_id": "4engp4e6KzU",
        "video_title": "Resistance Band Upright Row – Perfect Form Guide",
        "instructions": [
            "Stand on the band, hands close together in front of your thighs.",
            "Pull the band straight up the front of your body, leading with your elbows.",
            "Stop when your hands reach chest height and your elbows are level with your shoulders.",
            "Lower slowly.",
        ],
        "form_tips": [
            "Keep the band close to your body.",
            "Elbows lead and stay higher than the wrists.",
            "If your shoulders pinch, stop lower and widen the grip.",
        ],
        "common_mistakes": [
            "Pulling the elbows above the shoulders (shoulder impingement risk).",
            "Letting the band drift away from the body.",
            "Using a jerky, momentum-driven pull.",
        ],
    },
    {
        "slug": "band-overhead-tricep-extension", "name": "Band Overhead Triceps Extension",
        "equipment": "bands", "difficulty": "beginner", "primary_muscles": ["Triceps"],
        "secondary_muscles": [],
        "summary": "Extend the band overhead to target the long head of the triceps.",
        "is_compound": False, "video_id": "Yi_zNoIsNcc",
        "video_title": "Band Overhead Tricep Extension",
        "instructions": [
            "Stand on the band, bring your hands behind your head with elbows pointing up.",
            "Brace your core and keep your upper arms still.",
            "Extend your elbows to press the band overhead until your arms are nearly straight.",
            "Lower slowly behind your head.",
        ],
        "form_tips": [
            "Elbows point at the ceiling and stay there.",
            "Keep your ribs down — don't arch to press.",
            "Keep constant tension; don't rest at the bottom.",
        ],
        "common_mistakes": [
            "Elbows flaring forward.",
            "Arching the lower back.",
            "Only doing a partial range.",
        ],
    },
    {
        "slug": "band-tricep-kickback", "name": "Band Triceps Kickback", "equipment": "bands",
        "difficulty": "beginner", "primary_muscles": ["Triceps"],
        "secondary_muscles": ["Rear Delts"],
        "summary": "Hinge over and press the band straight back — constant tension right where the triceps lock out.",
        "is_compound": False, "video_id": "d-ySLTHUgQA",
        "video_title": "Triceps Kickback / Pushdown — Band Tutorial",
        "instructions": [
            "Stand on the band and hinge your torso forward to about 45 degrees, flat back.",
            "Tuck your upper arms against your sides, elbows bent 90 degrees.",
            "Straighten your elbows to press the band back, squeezing the triceps.",
            "Return slowly to 90 degrees.",
        ],
        "form_tips": [
            "Upper arms stay pinned — only the forearms move.",
            "Squeeze for a beat at full extension.",
            "Keep a neutral spine; don't round the back.",
        ],
        "common_mistakes": [
            "Upper arms drifting as you press.",
            "Rounding the lower back.",
            "Swinging the weight instead of controlling it.",
        ],
    },

    # ---------- Mobility & warm-up ----------
    {
        "slug": "worlds-greatest-stretch", "name": "World's Greatest Stretch", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Hips", "Thoracic Spine"],
        "secondary_muscles": ["Hamstrings", "Shoulders", "Glutes"],
        "summary": "One flowing move that opens the hips, hamstrings and upper back — the ideal pre-workout stretch.",
        "is_compound": True, "video_id": "T6j7BpxeqqU",
        "video_title": "World's Greatest Stretch | Tutorial",
        "instructions": [
            "From a plank, step one foot up outside the same-side hand into a deep lunge.",
            "Drop the back knee if you need to; keep a long spine.",
            "Reach the inside hand's elbow toward your instep, then rotate that arm up to the ceiling, following it with your eyes.",
            "Return the hand down, step back to plank, and switch sides.",
        ],
        "form_tips": [
            "Move slowly and breathe into each position.",
            "Keep the front knee tracking over the foot.",
            "Only rotate as far as feels open, not forced.",
        ],
        "common_mistakes": [
            "Rushing through instead of holding each phase.",
            "Rounding the back in the lunge.",
            "Forcing the rotation.",
        ],
    },
    {
        "slug": "cat-cow", "name": "Cat–Cow", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Spine"],
        "secondary_muscles": ["Core", "Neck"],
        "summary": "Slow spinal flexion and extension on all fours — wakes up the back before you load it.",
        "is_compound": False, "video_id": "xyNwxiuERXc",
        "video_title": "Cat–Cow Stretch | Proper Form Tutorial for Spinal Mobility",
        "instructions": [
            "Start on all fours, hands under shoulders, knees under hips.",
            "Inhale and drop your belly, lifting your chest and tailbone (cow).",
            "Exhale and round your spine toward the ceiling, tucking your chin and tailbone (cat).",
            "Flow slowly between the two with your breath.",
        ],
        "form_tips": [
            "Let the movement travel the whole spine, not just the lower back.",
            "Move with your breath — slow and smooth.",
            "Keep your arms straight and shoulders away from your ears.",
        ],
        "common_mistakes": [
            "Only moving the lower back.",
            "Rushing the reps.",
            "Sagging into the shoulders in the 'cow' position.",
        ],
    },
    {
        "slug": "downward-dog", "name": "Downward Dog", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Hamstrings", "Calves"],
        "secondary_muscles": ["Shoulders", "Lats", "Spine"],
        "summary": "An inverted-V stretch for the whole back line — hamstrings, calves and shoulders at once.",
        "is_compound": True, "video_id": "ulZr-S0cFOI",
        "video_title": "How to Do Downward Dog | Proper Form & Technique for Beginners",
        "instructions": [
            "Start on all fours, hands slightly ahead of your shoulders.",
            "Tuck your toes and lift your hips up and back into an upside-down V.",
            "Press the floor away, lengthen your spine, and let your heels sink toward the floor.",
            "Bend the knees as much as you need to keep the back long.",
        ],
        "form_tips": [
            "A long spine matters more than straight legs — bend the knees freely.",
            "Spread your fingers and press through the whole hand.",
            "Relax your neck; let your head hang.",
        ],
        "common_mistakes": [
            "Rounding the back to force the heels down.",
            "Shrugging the shoulders up to the ears.",
            "Putting all the weight in the wrists.",
        ],
    },
    {
        "slug": "deep-squat-hold", "name": "Deep Squat Hold", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Hips", "Ankles"],
        "secondary_muscles": ["Adductors", "Glutes", "Spine"],
        "summary": "Sit in the bottom of a squat and breathe — restores the hip and ankle range squatting needs.",
        "is_compound": False, "video_id": "0wzrgyAurT8", "video_title": "How to Deep Squat Hold",
        "instructions": [
            "Stand with feet a little wider than shoulders, toes slightly out.",
            "Sit all the way down into a squat, keeping your whole foot on the floor.",
            "Use your elbows to gently press your knees out and lift your chest.",
            "Hold, breathing slowly. Hold a support in front of you if you'd tip backward.",
        ],
        "form_tips": [
            "Heels stay down — put a rolled towel under them if needed.",
            "Start with 20–30 seconds and build toward a couple of minutes.",
            "Relax into it; this is a rest position in much of the world.",
        ],
        "common_mistakes": [
            "Heels lifting off the floor.",
            "Rounding the back and collapsing forward.",
            "Forcing depth your ankles can't give yet.",
        ],
    },
    {
        "slug": "thoracic-open-book", "name": "Thoracic Open Book", "equipment": "bodyweight",
        "difficulty": "beginner", "primary_muscles": ["Thoracic Spine"],
        "secondary_muscles": ["Chest", "Shoulders"],
        "summary": "A side-lying rotation that frees up the upper back — fixes the stiffness that wrecks overhead and rotation work.",
        "is_compound": False, "video_id": "5TdmVlQe64c",
        "video_title": "How to Do T-Spine Rotation (Open Book) | Thoracic Mobility",
        "instructions": [
            "Lie on your side, knees stacked and bent 90 degrees, arms stretched out in front, palms together.",
            "Keeping the knees down, sweep the top arm up and over to the other side, following it with your eyes.",
            "Let your chest open toward the ceiling, then return the arm slowly.",
            "Finish reps, then switch sides.",
        ],
        "form_tips": [
            "Keep the bottom knee pinned down — the rotation comes from the upper back.",
            "Exhale as you open up.",
            "Move slowly and pause at end range.",
        ],
        "common_mistakes": [
            "Letting the knees lift and rolling the hips.",
            "Forcing the arm down with momentum.",
            "Holding your breath.",
        ],
    },
]
